/* Generated by modconv 2 */

glabel shortcutElevator_collision
colInit
colVertexInit 8
colVertex -65, 0, 64
colVertex -65, 0, -65
colVertex 64, 0, -65
colVertex 64, 0, 64
colVertex -65, 8, 64
colVertex 64, 8, 64
colVertex 64, 8, -65
colVertex -65, 8, -65

colTriInit SURFACE_DEFAULT, 12
colTri      0,      1,      2
colTri      2,      3,      0
colTri      4,      5,      6
colTri      6,      7,      4
colTri      0,      3,      5
colTri      5,      4,      0
colTri      3,      2,      6
colTri      6,      5,      3
colTri      2,      1,      7
colTri      7,      6,      2
colTri      1,      0,      4
colTri      4,      7,      1
colTriStop
colEnd
