/* Generated by modconv 2 */

shortcutElevator_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
shortcutElevator_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

shortcutElevator_texture_0:
.incbin "actors/shortcutElevator/elevatorTile.rgba16"

shortcutElevator_vertex_0: /* 11 vertices out of 15 */
vertex   -262,      0,    262,   4064,    -32,   0xff, 0xff, 0xff, 0xff
vertex   -262,      0,   -262,   4063,  -4128,   0xff, 0xff, 0xff, 0xff
vertex    262,      0,   -262,    -32,  -4127,   0xff, 0xff, 0xff, 0xff
vertex    262,      0,    262,    -32,    -32,   0xff, 0xff, 0xff, 0xff
vertex   -262,     35,    262,    -32,    -32,   0xff, 0xff, 0xff, 0xff
vertex    262,     35,    262,   4063,    -32,   0xff, 0xff, 0xff, 0xff
vertex    262,     34,   -262,   4064,  -4127,   0xff, 0xff, 0xff, 0xff
vertex   -262,     34,   -262,    -32,  -4128,   0xff, 0xff, 0xff, 0xff
vertex   -262,      0,    262,    -32,  -1583,   0xff, 0xff, 0xff, 0xff
vertex    262,      0,    262,   4063,  -1583,   0xff, 0xff, 0xff, 0xff
vertex    262,     35,    262,   4063,  -1856,   0xff, 0xff, 0xff, 0xff

shortcutElevator_vertex_1: /* 11 vertices out of 15 */
vertex    262,     35,    262,   4063,  -1856,   0xff, 0xff, 0xff, 0xff
vertex   -262,     35,    262,    -32,  -1856,   0xff, 0xff, 0xff, 0xff
vertex   -262,      0,    262,    -32,  -1583,   0xff, 0xff, 0xff, 0xff
vertex    262,      0,    262,    -32,  -1583,   0xff, 0xff, 0xff, 0xff
vertex    262,      0,   -262,   4063,  -1583,   0xff, 0xff, 0xff, 0xff
vertex    262,     34,   -262,   4063,  -1856,   0xff, 0xff, 0xff, 0xff
vertex    262,     35,    262,    -32,  -1856,   0xff, 0xff, 0xff, 0xff
vertex    262,      0,   -262,    -32,  -1583,   0xff, 0xff, 0xff, 0xff
vertex   -262,      0,   -262,   4063,  -1583,   0xff, 0xff, 0xff, 0xff
vertex   -262,     34,   -262,   4063,  -1856,   0xff, 0xff, 0xff, 0xff
vertex    262,     34,   -262,    -32,  -1856,   0xff, 0xff, 0xff, 0xff

shortcutElevator_vertex_2: /* 4 vertices out of 6 */
vertex   -262,      0,   -262,    -32,  -1583,   0xff, 0xff, 0xff, 0xff
vertex   -262,      0,    262,   4063,  -1583,   0xff, 0xff, 0xff, 0xff
vertex   -262,     35,    262,   4063,  -1856,   0xff, 0xff, 0xff, 0xff
vertex   -262,     34,   -262,    -32,  -1856,   0xff, 0xff, 0xff, 0xff

/* Render order: 1 */

glabel shortcutElevator_dl_opaque
gsSPClearGeometryMode G_LIGHTING
/* 07 - Default */
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock shortcutElevator_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSPVertex shortcutElevator_vertex_0, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex shortcutElevator_vertex_1, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex shortcutElevator_vertex_2, 4, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPEndDisplayList
