/* Generated by modconv 2 */

glabel fogDoor_collision
colInit
colVertexInit 8
colVertex -132, 252, -10
colVertex 131, 252, -10
colVertex 131, 0, -10
colVertex -132, 0, -10
colVertex 131, 252, 0
colVertex -132, 252, 0
colVertex -132, 0, 0
colVertex 131, 0, 0

colTriInit SURFACE_DEFAULT, 12
colTri      0,      1,      2
colTri      0,      2,      3
colTri      0,      4,      1
colTri      4,      0,      5
colTri      3,      5,      0
colTri      5,      3,      6
colTri      3,      2,      6
colTri      7,      6,      2
colTri      4,      7,      1
colTri      1,      7,      2
colTri      4,      5,      7
colTri      5,      6,      7
colTriStop
colEnd
