/* Generated by modconv 2 */

glabel fogDoor_geo
    geo_culling_radius 1500
        geo_open_node
            geo_scale 0x00, 16384
            geo_open_node
                geo_display_list LAYER_OPAQUE fogDoor_dl_opaque
            geo_close_node
        geo_close_node
    geo_end
