/* Generated by modconv 2 */

fogDoor_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
fogDoor_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

fogDoor_texture_0:
.incbin "actors/fogDoor/fogDoor.rgba16"

fogDoor_vertex_0: /* 11 vertices out of 15 */
vertex   -534,   1022,    -37,   2266,  -2039,   0x00, 0x00, 0x81, 0x00
vertex    534,   1022,    -37,   -861,  -2039,   0x00, 0x00, 0x81, 0x00
vertex    534,      0,    -37,   -861,    951,   0x00, 0x00, 0x81, 0x00
vertex   -534,      0,    -37,   2266,    951,   0x00, 0x00, 0x81, 0x00
vertex   -534,   1022,    -37,   2266,   -433,   0x00, 0x7f, 0x00, 0x00
vertex    534,   1022,      4,   -861,   -557,   0x00, 0x7f, 0x00, 0x00
vertex    534,   1022,    -37,   -861,   -433,   0x00, 0x7f, 0x00, 0x00
vertex   -534,   1022,      4,   2266,   -557,   0x00, 0x7f, 0x00, 0x00
vertex   -534,      0,    -37,   1975,   -433,   0x81, 0x00, 0x00, 0x00
vertex   -534,   1022,      4,  -1015,   -557,   0x81, 0x00, 0x00, 0x00
vertex   -534,   1022,    -37,  -1015,   -433,   0x81, 0x00, 0x00, 0x00

fogDoor_vertex_1: /* 11 vertices out of 15 */
vertex   -534,   1022,      4,  -1015,   -557,   0x81, 0x00, 0x00, 0x00
vertex   -534,      0,    -37,   1975,   -433,   0x81, 0x00, 0x00, 0x00
vertex   -534,      0,      4,   1975,   -557,   0x81, 0x00, 0x00, 0x00
vertex   -534,      0,    -37,  -1306,   -433,   0x00, 0x81, 0x00, 0x00
vertex    534,      0,    -37,   1821,   -433,   0x00, 0x81, 0x00, 0x00
vertex   -534,      0,      4,  -1306,   -557,   0x00, 0x81, 0x00, 0x00
vertex    534,      0,      4,   1821,   -557,   0x00, 0x81, 0x00, 0x00
vertex    534,   1022,      4,   1975,   -557,   0x7f, 0x00, 0x00, 0x00
vertex    534,      0,      4,  -1015,   -557,   0x7f, 0x00, 0x00, 0x00
vertex    534,   1022,    -37,   1975,   -433,   0x7f, 0x00, 0x00, 0x00
vertex    534,      0,    -37,  -1015,   -433,   0x7f, 0x00, 0x00, 0x00

fogDoor_vertex_2: /* 4 vertices out of 6 */
vertex    534,   1022,      4,   1821,  -2039,   0x00, 0x00, 0x7f, 0x00
vertex   -534,   1022,      4,  -1306,  -2039,   0x00, 0x00, 0x7f, 0x00
vertex    534,      0,      4,   1821,    951,   0x00, 0x00, 0x7f, 0x00
vertex   -534,      0,      4,  -1306,    951,   0x00, 0x00, 0x7f, 0x00

/* Render order: 1 */

glabel fogDoor_dl_opaque
gsSPClearGeometryMode G_LIGHTING
/* #LIGHTING 07 - Default */
gsDPPipeSync
gsSPSetGeometryMode G_LIGHTING
gsSPNumLights NUMLIGHTS_1
gsSPLight fogDoor_diffuse_light, 1
gsSPLight fogDoor_ambient_light, 2
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
glabel fogDoor_texLoad
gsDPLoadTextureBlock fogDoor_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSPVertex fogDoor_vertex_0, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex fogDoor_vertex_1, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 5, 4, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 8, 10, 0x00
gsSPVertex fogDoor_vertex_2, 4, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPEndDisplayList
