/* Generated by modconv 2 */

arrowTrapArrow_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
arrowTrapArrow_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

arrowTrapArrow_texture_0:
.incbin "actors/arrowTrapArrow/arrowMetal.rgba16"

arrowTrapArrow_vertex_0: /* 9 vertices out of 15 */
vertex    124,   -101,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex    124,   -101,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex    124,   -101,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff
vertex    110,   -101,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex    110,   -101,     87,   -139,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,   -101,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex    110,    -87,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex    110,    -87,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,    -87,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff

arrowTrapArrow_vertex_1: /* 11 vertices out of 15 */
vertex    110,    -87,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex    110,    -87,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff
vertex    124,    -87,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex    124,    -87,    -87,  -8116,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    110,    -87,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex    110,   -101,    -87,  -8116,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex    110,   -101,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,    -87,     87,   2123,  -1465,   0x81, 0x00, 0x00, 0xff
vertex    110,   -101,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    124,   -101,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    124,    -87,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff

arrowTrapArrow_vertex_2: /* 11 vertices out of 15 */
vertex    124,    -87,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    110,    -87,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex    110,   -101,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    124,    -87,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    124,    -87,     87,   -139,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex    124,    -87,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex    124,   -101,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff
vertex    124,   -101,    -87,  10100,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex    110,    -87,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex    124,    -87,    -87,    582,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    124,   -101,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff

arrowTrapArrow_vertex_3: /* 10 vertices out of 15 */
vertex    124,   -101,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex    110,   -101,    -87,   1401,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex    110,    -87,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex    110,   -101,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     98,    -95,     68,   -141,   -979,   0x00, 0x00, 0x7f, 0xff
vertex    110,   -101,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,   -101,     87,    582,   -646,   0x00, 0x81, 0x00, 0xff
vertex    110,    -87,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    110,    -87,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex     98,    -92,     68,   -141,  -1132,   0x96, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_4: /* 9 vertices out of 15 */
vertex     98,    -95,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex    110,   -101,     87,   2123,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    110,   -101,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    110,    -87,     87,   2123,  -1465,   0x00, 0x37, 0x72, 0xff
vertex    110,    -87,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     98,    -92,     68,    991,  -1132,   0x96, 0x00, 0x44, 0xff
vertex    119,    -74,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex    116,    -74,     68,    992,   -979,   0x00, 0x6a, 0x44, 0xff
vertex    110,    -87,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff

arrowTrapArrow_vertex_5: /* 10 vertices out of 15 */
vertex    110,    -87,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex    124,    -87,     87,   2123,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    124,    -87,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex    119,    -74,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex    124,    -87,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    119,    -74,     68,   1068,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex    124,    -87,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex    110,    -87,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    116,    -74,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex    110,    -87,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_6: /* 11 vertices out of 15 */
vertex    110,    -87,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex    116,    -74,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex    110,    -87,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    124,   -101,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    124,   -101,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    137,    -95,     68,   2125,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    137,    -95,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    137,    -92,     68,    991,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex    124,    -87,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    124,   -101,     87,   -139,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    124,   -101,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_7: /* 11 vertices out of 15 */
vertex    137,    -95,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    124,    -87,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    124,   -101,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    124,    -87,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    137,    -92,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex    124,    -87,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex    124,    -87,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    110,   -101,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    116,   -113,     68,    992,   -979,   0x00, 0x96, 0x44, 0xff
vertex    119,   -113,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff
vertex    124,   -101,     87,   -139,  -1465,   0x00, 0xc9, 0x72, 0xff

arrowTrapArrow_vertex_8: /* 10 vertices out of 15 */
vertex    110,   -101,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    116,   -113,     68,    915,     77,   0x00, 0x96, 0x44, 0xff
vertex    110,   -101,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    124,   -101,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    119,   -113,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex    124,   -101,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    124,   -101,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex     98,    -95,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex     98,    -92,     68,    991,  -1132,   0x6a, 0x00, 0xbc, 0xff
vertex    110,    -87,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff

arrowTrapArrow_vertex_9: /* 9 vertices out of 15 */
vertex    110,    -87,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex    110,    -87,     87,   2123,  -1465,   0x00, 0xdb, 0x87, 0xff
vertex    110,   -101,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff
vertex     98,    -95,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex    110,   -101,     87,   2123,   -646,   0x00, 0x87, 0xdd, 0xff
vertex    124,    -87,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex    124,    -87,     87,   2123,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    110,    -87,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex    119,    -74,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff

arrowTrapArrow_vertex_10: /* 11 vertices out of 15 */
vertex    119,    -74,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff
vertex    110,    -87,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex    116,    -74,     68,    992,   -979,   0x00, 0x96, 0xbc, 0xff
vertex    124,   -101,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex    124,   -101,     87,   -139,   -646,   0x00, 0x6a, 0xbc, 0xff
vertex    124,    -87,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    137,    -95,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff
vertex    137,    -92,     68,    991,  -1132,   0x96, 0x00, 0xbc, 0xff
vertex    110,   -101,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex    124,   -101,     87,   -139,  -1465,   0x00, 0x6a, 0xbc, 0xff
vertex    119,   -113,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff

arrowTrapArrow_vertex_11: /* 9 vertices out of 15 */
vertex    119,   -113,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff
vertex    116,   -113,     68,    992,   -979,   0x00, 0x6a, 0xbc, 0xff
vertex    110,   -101,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex    124,      6,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex    124,      6,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex    124,      6,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff
vertex    110,      6,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex    110,      6,     87,   -139,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,      6,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff

arrowTrapArrow_vertex_12: /* 9 vertices out of 15 */
vertex    110,     20,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex    110,     20,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,     20,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff
vertex    124,     20,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex    124,     20,    -87,  -8116,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    110,     20,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex    110,      6,    -87,  -8116,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex    110,      6,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,     20,     87,   2123,  -1465,   0x81, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_13: /* 9 vertices out of 15 */
vertex    110,      6,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    124,      6,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    124,     20,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    110,     20,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex    124,     20,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    124,     20,     87,   -139,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex    124,     20,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex    124,      6,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff
vertex    124,      6,    -87,  10100,   -646,   0x49, 0xb7, 0xb7, 0xff

arrowTrapArrow_vertex_14: /* 10 vertices out of 15 */
vertex    110,     20,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex    124,     20,    -87,    582,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    124,      6,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex    110,      6,    -87,   1401,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex    110,      6,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     98,     11,     68,   -141,   -979,   0x00, 0x00, 0x7f, 0xff
vertex    110,      6,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,      6,     87,    582,   -646,   0x00, 0x81, 0x00, 0xff
vertex    110,     20,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    110,     20,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_15: /* 9 vertices out of 15 */
vertex    110,     20,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex     98,     14,     68,   -141,  -1132,   0x96, 0x00, 0x44, 0xff
vertex    110,     20,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     98,     11,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex    110,      6,     87,   2123,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    110,      6,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    110,     20,     87,   2123,  -1465,   0x00, 0x37, 0x72, 0xff
vertex    110,     20,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     98,     14,     68,    991,  -1132,   0x96, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_16: /* 8 vertices out of 15 */
vertex    119,     32,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex    116,     32,     68,    992,   -979,   0x00, 0x6a, 0x44, 0xff
vertex    110,     20,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex    124,     20,     87,   2123,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    124,     20,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex    124,     20,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    119,     32,     68,   1068,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex    124,     20,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff

arrowTrapArrow_vertex_17: /* 10 vertices out of 15 */
vertex    110,     20,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    116,     32,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex    110,     20,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    110,     20,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex    124,      6,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    124,      6,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    137,     11,     68,   2125,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    137,     11,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    137,     14,     68,    991,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex    124,     20,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff

arrowTrapArrow_vertex_18: /* 11 vertices out of 15 */
vertex    124,     20,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    124,      6,     87,   -139,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    124,      6,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    137,     11,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    124,     20,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    137,     14,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex    124,     20,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex    124,     20,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    110,      6,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    116,     -6,     68,    992,   -979,   0x00, 0x96, 0x44, 0xff
vertex    119,     -6,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff

arrowTrapArrow_vertex_19: /* 10 vertices out of 15 */
vertex    119,     -6,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff
vertex    124,      6,     87,   -139,  -1465,   0x00, 0xc9, 0x72, 0xff
vertex    110,      6,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    110,      6,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    116,     -6,     68,    915,     77,   0x00, 0x96, 0x44, 0xff
vertex    110,      6,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    124,      6,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    119,     -6,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex    124,      6,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    124,      6,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff

arrowTrapArrow_vertex_20: /* 9 vertices out of 15 */
vertex     98,     11,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex     98,     14,     68,    991,  -1132,   0x6a, 0x00, 0xbc, 0xff
vertex    110,     20,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex    110,     20,     87,   2123,  -1465,   0x00, 0xdb, 0x87, 0xff
vertex    110,      6,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff
vertex    110,      6,     87,   2123,   -646,   0x00, 0x87, 0xdd, 0xff
vertex    124,     20,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex    124,     20,     87,   2123,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    110,     20,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff

arrowTrapArrow_vertex_21: /* 9 vertices out of 15 */
vertex    119,     32,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff
vertex    124,     20,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex    110,     20,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex    116,     32,     68,    992,   -979,   0x00, 0x96, 0xbc, 0xff
vertex    124,      6,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex    124,      6,     87,   -139,   -646,   0x00, 0x6a, 0xbc, 0xff
vertex    124,     20,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    137,     11,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff
vertex    137,     14,     68,    991,  -1132,   0x96, 0x00, 0xbc, 0xff

arrowTrapArrow_vertex_22: /* 10 vertices out of 15 */
vertex    110,      6,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex    124,      6,     87,   -139,  -1465,   0x00, 0x6a, 0xbc, 0xff
vertex    119,     -6,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff
vertex    116,     -6,     68,    992,   -979,   0x00, 0x6a, 0xbc, 0xff
vertex    124,   -208,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex    124,   -208,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex    124,   -208,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff
vertex    110,   -208,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex    110,   -208,     87,   -139,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,   -208,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff

arrowTrapArrow_vertex_23: /* 11 vertices out of 15 */
vertex    124,   -208,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex    110,   -208,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex    110,   -208,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex    110,   -194,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex    110,   -194,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,   -194,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff
vertex    124,   -194,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex    124,   -194,    -87,  -8116,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    110,   -194,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex    110,   -208,    -87,  -8116,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex    110,   -208,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_24: /* 11 vertices out of 15 */
vertex    110,   -208,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,   -194,     87,   2123,  -1465,   0x81, 0x00, 0x00, 0xff
vertex    110,   -194,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex    110,   -208,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    124,   -208,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    124,   -194,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    110,   -194,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex    124,   -194,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    124,   -194,     87,   -139,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex    124,   -194,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex    124,   -208,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_25: /* 11 vertices out of 15 */
vertex    124,   -194,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    124,   -208,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff
vertex    124,   -208,    -87,  10100,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex    110,   -194,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex    124,   -194,    -87,    582,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex    124,   -208,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex    110,   -208,    -87,   1401,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex    110,   -208,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     98,   -202,     68,   -141,   -979,   0x00, 0x00, 0x7f, 0xff
vertex    110,   -208,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff
vertex    110,   -208,     87,    582,   -646,   0x00, 0x81, 0x00, 0xff

arrowTrapArrow_vertex_26: /* 8 vertices out of 15 */
vertex    110,   -194,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    110,   -194,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex     98,   -200,     68,   -141,  -1132,   0x96, 0x00, 0x44, 0xff
vertex     98,   -202,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex    110,   -208,     87,   2123,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    110,   -208,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    110,   -194,     87,   2123,  -1465,   0x00, 0x37, 0x72, 0xff
vertex    110,   -194,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_27: /* 11 vertices out of 15 */
vertex     98,   -202,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex    110,   -194,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     98,   -200,     68,    991,  -1132,   0x96, 0x00, 0x44, 0xff
vertex    119,   -182,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex    116,   -182,     68,    992,   -979,   0x00, 0x6a, 0x44, 0xff
vertex    110,   -194,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex    124,   -194,     87,   2123,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    124,   -194,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex    124,   -194,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    119,   -182,     68,   1068,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex    124,   -194,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff

arrowTrapArrow_vertex_28: /* 9 vertices out of 15 */
vertex    124,   -194,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex    124,   -194,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    110,   -194,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    116,   -182,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex    110,   -194,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    110,   -194,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex    124,   -208,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    124,   -208,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    137,   -202,     68,   2125,   -979,   0x6a, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_29: /* 9 vertices out of 15 */
vertex    137,   -202,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    137,   -200,     68,    991,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex    124,   -194,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    124,   -208,     87,   -139,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    124,   -208,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    124,   -194,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    137,   -200,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex    124,   -194,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex    124,   -194,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_30: /* 10 vertices out of 15 */
vertex    110,   -208,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    116,   -221,     68,    992,   -979,   0x00, 0x96, 0x44, 0xff
vertex    119,   -221,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff
vertex    124,   -208,     87,   -139,  -1465,   0x00, 0xc9, 0x72, 0xff
vertex    110,   -208,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    116,   -221,     68,    915,     77,   0x00, 0x96, 0x44, 0xff
vertex    110,   -208,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex    124,   -208,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    119,   -221,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex    124,   -208,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_31: /* 9 vertices out of 15 */
vertex    124,   -208,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    119,   -221,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex    124,   -208,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex     98,   -202,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex     98,   -200,     68,    991,  -1132,   0x6a, 0x00, 0xbc, 0xff
vertex    110,   -194,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex    110,   -194,     87,   2123,  -1465,   0x00, 0xdb, 0x87, 0xff
vertex    110,   -208,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff
vertex    110,   -208,     87,   2123,   -646,   0x00, 0x87, 0xdd, 0xff

arrowTrapArrow_vertex_32: /* 9 vertices out of 15 */
vertex    124,   -194,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex    124,   -194,     87,   2123,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    110,   -194,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex    119,   -182,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff
vertex    116,   -182,     68,    992,   -979,   0x00, 0x96, 0xbc, 0xff
vertex    124,   -208,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex    124,   -208,     87,   -139,   -646,   0x00, 0x6a, 0xbc, 0xff
vertex    124,   -194,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    137,   -202,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff

arrowTrapArrow_vertex_33: /* 11 vertices out of 15 */
vertex    137,   -202,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff
vertex    124,   -194,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    137,   -200,     68,    991,  -1132,   0x96, 0x00, 0xbc, 0xff
vertex    110,   -208,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex    124,   -208,     87,   -139,  -1465,   0x00, 0x6a, 0xbc, 0xff
vertex    119,   -221,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff
vertex    116,   -221,     68,    992,   -979,   0x00, 0x6a, 0xbc, 0xff
vertex      7,   -208,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex      7,   -208,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex      7,   -208,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff
vertex     -6,   -208,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff

arrowTrapArrow_vertex_34: /* 9 vertices out of 15 */
vertex     -6,   -208,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex     -6,   -208,     87,   -139,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,   -208,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex      7,   -208,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex     -6,   -194,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex     -6,   -194,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,   -194,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff
vertex      7,   -194,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex      7,   -194,    -87,  -8116,  -1465,   0x49, 0x49, 0xb7, 0xff

arrowTrapArrow_vertex_35: /* 11 vertices out of 15 */
vertex     -6,   -194,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex     -6,   -208,    -87,  -8116,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex     -6,   -208,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,   -194,     87,   2123,  -1465,   0x81, 0x00, 0x00, 0xff
vertex     -6,   -208,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex      7,   -208,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex      7,   -194,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex     -6,   -194,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex      7,   -194,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex      7,   -194,     87,   -139,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex      7,   -194,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_36: /* 11 vertices out of 15 */
vertex      7,   -194,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex      7,   -194,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex      7,   -208,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff
vertex      7,   -208,    -87,  10100,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex     -6,   -194,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex      7,   -194,    -87,    582,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex      7,   -208,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex     -6,   -208,    -87,   1401,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex     -6,   -208,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    -19,   -202,     68,   -141,   -979,   0x00, 0x00, 0x7f, 0xff
vertex     -6,   -208,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_37: /* 11 vertices out of 15 */
vertex     -6,   -208,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,   -208,     87,    582,   -646,   0x00, 0x81, 0x00, 0xff
vertex     -6,   -208,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     -6,   -194,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     -6,   -194,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    -19,   -200,     68,   -141,  -1132,   0x96, 0x00, 0x44, 0xff
vertex    -19,   -202,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex     -6,   -208,     87,   2123,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     -6,   -208,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex     -6,   -194,     87,   2123,  -1465,   0x00, 0x37, 0x72, 0xff
vertex     -6,   -194,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_38: /* 9 vertices out of 15 */
vertex    -19,   -202,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex     -6,   -208,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex     -6,   -194,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    -19,   -200,     68,    991,  -1132,   0x96, 0x00, 0x44, 0xff
vertex      1,   -182,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex     -1,   -182,     68,    992,   -979,   0x00, 0x6a, 0x44, 0xff
vertex     -6,   -194,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex      7,   -194,     87,   2123,  -1465,   0x37, 0x00, 0x72, 0xff
vertex      7,   -194,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff

arrowTrapArrow_vertex_39: /* 9 vertices out of 15 */
vertex      7,   -194,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex      1,   -182,     68,   1068,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex      7,   -194,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex     -6,   -194,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     -1,   -182,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex     -6,   -194,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex     -6,   -194,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex      7,   -208,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex      7,   -208,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_40: /* 11 vertices out of 15 */
vertex      7,   -208,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     19,   -202,     68,   2125,   -979,   0x6a, 0x00, 0x44, 0xff
vertex      7,   -208,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex     19,   -202,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex     19,   -200,     68,    991,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex      7,   -194,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex      7,   -208,     87,   -139,   -646,   0x00, 0xc9, 0x72, 0xff
vertex      7,   -208,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff
vertex      7,   -194,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex     19,   -200,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex      7,   -194,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff

arrowTrapArrow_vertex_41: /* 10 vertices out of 15 */
vertex      7,   -194,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex     19,   -200,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex      7,   -194,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex     -6,   -208,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex     -1,   -221,     68,    992,   -979,   0x00, 0x96, 0x44, 0xff
vertex      1,   -221,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff
vertex      7,   -208,     87,   -139,  -1465,   0x00, 0xc9, 0x72, 0xff
vertex     -6,   -208,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     -1,   -221,     68,    915,     77,   0x00, 0x96, 0x44, 0xff
vertex     -6,   -208,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff

arrowTrapArrow_vertex_42: /* 9 vertices out of 15 */
vertex      7,   -208,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex      1,   -221,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex      7,   -208,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex      7,   -208,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    -19,   -202,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex    -19,   -200,     68,    991,  -1132,   0x6a, 0x00, 0xbc, 0xff
vertex     -6,   -194,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex     -6,   -194,     87,   2123,  -1465,   0x00, 0xdb, 0x87, 0xff
vertex     -6,   -208,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff

arrowTrapArrow_vertex_43: /* 11 vertices out of 15 */
vertex    -19,   -202,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex     -6,   -208,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff
vertex     -6,   -208,     87,   2123,   -646,   0x00, 0x87, 0xdd, 0xff
vertex      7,   -194,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex      7,   -194,     87,   2123,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex     -6,   -194,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex      1,   -182,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff
vertex     -1,   -182,     68,    992,   -979,   0x00, 0x96, 0xbc, 0xff
vertex      7,   -208,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex      7,   -208,     87,   -139,   -646,   0x00, 0x6a, 0xbc, 0xff
vertex      7,   -194,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff

arrowTrapArrow_vertex_44: /* 11 vertices out of 15 */
vertex     19,   -202,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff
vertex      7,   -208,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex      7,   -194,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex     19,   -200,     68,    991,  -1132,   0x96, 0x00, 0xbc, 0xff
vertex     -6,   -208,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex      7,   -208,     87,   -139,  -1465,   0x00, 0x6a, 0xbc, 0xff
vertex      1,   -221,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff
vertex     -1,   -221,     68,    992,   -979,   0x00, 0x6a, 0xbc, 0xff
vertex      7,   -101,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex      7,   -101,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex      7,   -101,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff

arrowTrapArrow_vertex_45: /* 9 vertices out of 15 */
vertex      7,   -101,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex      7,   -101,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff
vertex     -6,   -101,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex     -6,   -101,     87,   -139,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,   -101,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex     -6,    -87,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex     -6,    -87,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,    -87,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff
vertex      7,    -87,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff

arrowTrapArrow_vertex_46: /* 11 vertices out of 15 */
vertex     -6,    -87,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex      7,    -87,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex      7,    -87,    -87,  -8116,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex     -6,    -87,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex     -6,   -101,    -87,  -8116,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex     -6,   -101,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,    -87,     87,   2123,  -1465,   0x81, 0x00, 0x00, 0xff
vertex     -6,   -101,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex      7,   -101,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex      7,    -87,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex     -6,    -87,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff

arrowTrapArrow_vertex_47: /* 9 vertices out of 15 */
vertex      7,    -87,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex      7,    -87,     87,   -139,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex      7,    -87,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex      7,   -101,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff
vertex      7,   -101,    -87,  10100,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex     -6,    -87,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex      7,    -87,    -87,    582,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex      7,   -101,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex     -6,   -101,    -87,   1401,   -646,   0xb7, 0xb7, 0xb7, 0xff

arrowTrapArrow_vertex_48: /* 10 vertices out of 15 */
vertex     -6,   -101,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    -19,    -95,     68,   -141,   -979,   0x00, 0x00, 0x7f, 0xff
vertex     -6,   -101,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,   -101,     87,    582,   -646,   0x00, 0x81, 0x00, 0xff
vertex     -6,    -87,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     -6,    -87,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    -19,    -92,     68,   -141,  -1132,   0x96, 0x00, 0x44, 0xff
vertex    -19,    -95,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex     -6,   -101,     87,   2123,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     -6,   -101,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff

arrowTrapArrow_vertex_49: /* 10 vertices out of 15 */
vertex     -6,   -101,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex     -6,    -87,     87,   2123,  -1465,   0x00, 0x37, 0x72, 0xff
vertex     -6,    -87,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    -19,    -95,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex    -19,    -92,     68,    991,  -1132,   0x96, 0x00, 0x44, 0xff
vertex      1,    -74,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex     -1,    -74,     68,    992,   -979,   0x00, 0x6a, 0x44, 0xff
vertex     -6,    -87,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex      7,    -87,     87,   2123,  -1465,   0x37, 0x00, 0x72, 0xff
vertex      7,    -87,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff

arrowTrapArrow_vertex_50: /* 10 vertices out of 15 */
vertex      1,    -74,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex     -6,    -87,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex      7,    -87,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex      7,    -87,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex      1,    -74,     68,   1068,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex      7,    -87,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex     -6,    -87,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     -1,    -74,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex     -6,    -87,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex     -6,    -87,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff

arrowTrapArrow_vertex_51: /* 8 vertices out of 15 */
vertex      7,   -101,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex      7,   -101,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     19,    -95,     68,   2125,   -979,   0x6a, 0x00, 0x44, 0xff
vertex     19,    -95,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex     19,    -92,     68,    991,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex      7,    -87,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex      7,   -101,     87,   -139,   -646,   0x00, 0xc9, 0x72, 0xff
vertex      7,   -101,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_52: /* 10 vertices out of 15 */
vertex      7,    -87,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex     19,    -92,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex      7,    -87,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex      7,    -87,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex     -6,   -101,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex     -1,   -113,     68,    992,   -979,   0x00, 0x96, 0x44, 0xff
vertex      1,   -113,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff
vertex      7,   -101,     87,   -139,  -1465,   0x00, 0xc9, 0x72, 0xff
vertex     -6,   -101,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     -1,   -113,     68,    915,     77,   0x00, 0x96, 0x44, 0xff

arrowTrapArrow_vertex_53: /* 12 vertices out of 15 */
vertex     -6,   -101,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     -1,   -113,     68,    915,     77,   0x00, 0x96, 0x44, 0xff
vertex     -6,   -101,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex      7,   -101,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex      1,   -113,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex      7,   -101,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex      7,   -101,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    -19,    -95,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex    -19,    -92,     68,    991,  -1132,   0x6a, 0x00, 0xbc, 0xff
vertex     -6,    -87,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex     -6,    -87,     87,   2123,  -1465,   0x00, 0xdb, 0x87, 0xff
vertex     -6,   -101,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff

arrowTrapArrow_vertex_54: /* 9 vertices out of 15 */
vertex    -19,    -95,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex     -6,    -87,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex     -6,   -101,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff
vertex     -6,   -101,     87,   2123,   -646,   0x00, 0x87, 0xdd, 0xff
vertex      7,    -87,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex      7,    -87,     87,   2123,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex     -6,    -87,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex      1,    -74,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff
vertex     -1,    -74,     68,    992,   -979,   0x00, 0x96, 0xbc, 0xff

arrowTrapArrow_vertex_55: /* 9 vertices out of 15 */
vertex      7,   -101,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex      7,   -101,     87,   -139,   -646,   0x00, 0x6a, 0xbc, 0xff
vertex      7,    -87,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex     19,    -95,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff
vertex     19,    -92,     68,    991,  -1132,   0x96, 0x00, 0xbc, 0xff
vertex     -6,   -101,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex      7,   -101,     87,   -139,  -1465,   0x00, 0x6a, 0xbc, 0xff
vertex      1,   -113,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff
vertex     -1,   -113,     68,    992,   -979,   0x00, 0x6a, 0xbc, 0xff

arrowTrapArrow_vertex_56: /* 9 vertices out of 15 */
vertex      7,      6,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex      7,      6,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex      7,      6,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff
vertex     -6,      6,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex     -6,      6,     87,   -139,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,      6,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex     -6,     20,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex     -6,     20,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,     20,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff

arrowTrapArrow_vertex_57: /* 11 vertices out of 15 */
vertex     -6,     20,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex     -6,     20,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff
vertex      7,     20,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex      7,     20,    -87,  -8116,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex     -6,     20,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex     -6,      6,    -87,  -8116,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex     -6,      6,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,     20,     87,   2123,  -1465,   0x81, 0x00, 0x00, 0xff
vertex     -6,      6,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex      7,      6,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex      7,     20,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff

arrowTrapArrow_vertex_58: /* 11 vertices out of 15 */
vertex      7,     20,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex     -6,     20,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex     -6,      6,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex      7,     20,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex      7,     20,     87,   -139,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex      7,     20,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex      7,      6,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff
vertex      7,      6,    -87,  10100,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex     -6,     20,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex      7,     20,    -87,    582,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex      7,      6,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff

arrowTrapArrow_vertex_59: /* 10 vertices out of 15 */
vertex      7,      6,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex     -6,      6,    -87,   1401,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex     -6,     20,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex     -6,      6,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    -19,     11,     68,   -141,   -979,   0x00, 0x00, 0x7f, 0xff
vertex     -6,      6,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff
vertex     -6,      6,     87,    582,   -646,   0x00, 0x81, 0x00, 0xff
vertex     -6,     20,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     -6,     20,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex    -19,     14,     68,   -141,  -1132,   0x96, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_60: /* 9 vertices out of 15 */
vertex    -19,     11,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex     -6,      6,     87,   2123,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     -6,      6,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex     -6,     20,     87,   2123,  -1465,   0x00, 0x37, 0x72, 0xff
vertex     -6,     20,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff
vertex    -19,     14,     68,    991,  -1132,   0x96, 0x00, 0x44, 0xff
vertex      1,     32,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex     -1,     32,     68,    992,   -979,   0x00, 0x6a, 0x44, 0xff
vertex     -6,     20,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff

arrowTrapArrow_vertex_61: /* 10 vertices out of 15 */
vertex     -6,     20,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex      7,     20,     87,   2123,  -1465,   0x37, 0x00, 0x72, 0xff
vertex      7,     20,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex      1,     32,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex      7,     20,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex      1,     32,     68,   1068,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex      7,     20,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex     -6,     20,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex     -1,     32,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex     -6,     20,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_62: /* 11 vertices out of 15 */
vertex     -6,     20,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex     -1,     32,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex     -6,     20,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex      7,      6,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex      7,      6,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     19,     11,     68,   2125,   -979,   0x6a, 0x00, 0x44, 0xff
vertex     19,     11,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex     19,     14,     68,    991,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex      7,     20,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex      7,      6,     87,   -139,   -646,   0x00, 0xc9, 0x72, 0xff
vertex      7,      6,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_63: /* 11 vertices out of 15 */
vertex     19,     11,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex      7,     20,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex      7,      6,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff
vertex      7,     20,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex     19,     14,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex      7,     20,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex      7,     20,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex     -6,      6,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex     -1,     -6,     68,    992,   -979,   0x00, 0x96, 0x44, 0xff
vertex      1,     -6,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff
vertex      7,      6,     87,   -139,  -1465,   0x00, 0xc9, 0x72, 0xff

arrowTrapArrow_vertex_64: /* 10 vertices out of 15 */
vertex     -6,      6,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex     -1,     -6,     68,    915,     77,   0x00, 0x96, 0x44, 0xff
vertex     -6,      6,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex      7,      6,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex      1,     -6,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex      7,      6,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex      7,      6,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex    -19,     11,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex    -19,     14,     68,    991,  -1132,   0x6a, 0x00, 0xbc, 0xff
vertex     -6,     20,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff

arrowTrapArrow_vertex_65: /* 9 vertices out of 15 */
vertex     -6,     20,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex     -6,     20,     87,   2123,  -1465,   0x00, 0xdb, 0x87, 0xff
vertex     -6,      6,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff
vertex    -19,     11,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex     -6,      6,     87,   2123,   -646,   0x00, 0x87, 0xdd, 0xff
vertex      7,     20,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex      7,     20,     87,   2123,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex     -6,     20,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex      1,     32,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff

arrowTrapArrow_vertex_66: /* 11 vertices out of 15 */
vertex      1,     32,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff
vertex     -6,     20,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex     -1,     32,     68,    992,   -979,   0x00, 0x96, 0xbc, 0xff
vertex      7,      6,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex      7,      6,     87,   -139,   -646,   0x00, 0x6a, 0xbc, 0xff
vertex      7,     20,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex     19,     11,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff
vertex     19,     14,     68,    991,  -1132,   0x96, 0x00, 0xbc, 0xff
vertex     -6,      6,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex      7,      6,     87,   -139,  -1465,   0x00, 0x6a, 0xbc, 0xff
vertex      1,     -6,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff

arrowTrapArrow_vertex_67: /* 9 vertices out of 15 */
vertex      1,     -6,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff
vertex     -1,     -6,     68,    992,   -979,   0x00, 0x6a, 0xbc, 0xff
vertex     -6,      6,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex   -110,   -208,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex   -110,   -208,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex   -110,   -208,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff
vertex   -124,   -208,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex   -124,   -208,     87,   -139,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,   -208,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff

arrowTrapArrow_vertex_68: /* 9 vertices out of 15 */
vertex   -124,   -194,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex   -124,   -194,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,   -194,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff
vertex   -110,   -194,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex   -110,   -194,    -87,  -8116,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -124,   -194,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex   -124,   -208,    -87,  -8116,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex   -124,   -208,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,   -194,     87,   2123,  -1465,   0x81, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_69: /* 9 vertices out of 15 */
vertex   -124,   -208,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -110,   -208,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex   -110,   -194,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex   -124,   -194,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex   -110,   -194,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -110,   -194,     87,   -139,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex   -110,   -194,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex   -110,   -208,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff
vertex   -110,   -208,    -87,  10100,   -646,   0x49, 0xb7, 0xb7, 0xff

arrowTrapArrow_vertex_70: /* 10 vertices out of 15 */
vertex   -124,   -194,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex   -110,   -194,    -87,    582,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -110,   -208,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex   -124,   -208,    -87,   1401,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex   -124,   -208,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -137,   -202,     68,   -141,   -979,   0x00, 0x00, 0x7f, 0xff
vertex   -124,   -208,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,   -208,     87,    582,   -646,   0x00, 0x81, 0x00, 0xff
vertex   -124,   -194,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -124,   -194,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_71: /* 9 vertices out of 15 */
vertex   -124,   -194,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -137,   -200,     68,   -141,  -1132,   0x96, 0x00, 0x44, 0xff
vertex   -124,   -194,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -137,   -202,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex   -124,   -208,     87,   2123,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -124,   -208,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -124,   -194,     87,   2123,  -1465,   0x00, 0x37, 0x72, 0xff
vertex   -124,   -194,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -137,   -200,     68,    991,  -1132,   0x96, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_72: /* 8 vertices out of 15 */
vertex   -116,   -182,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex   -119,   -182,     68,    992,   -979,   0x00, 0x6a, 0x44, 0xff
vertex   -124,   -194,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex   -110,   -194,     87,   2123,  -1465,   0x37, 0x00, 0x72, 0xff
vertex   -110,   -194,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex   -110,   -194,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -116,   -182,     68,   1068,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex   -110,   -194,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff

arrowTrapArrow_vertex_73: /* 10 vertices out of 15 */
vertex   -124,   -194,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -119,   -182,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex   -124,   -194,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -124,   -194,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex   -110,   -208,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex   -110,   -208,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    -98,   -202,     68,   2125,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    -98,   -202,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    -98,   -200,     68,    991,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex   -110,   -194,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff

arrowTrapArrow_vertex_74: /* 11 vertices out of 15 */
vertex   -110,   -194,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex   -110,   -208,     87,   -139,   -646,   0x00, 0xc9, 0x72, 0xff
vertex   -110,   -208,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    -98,   -202,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex   -110,   -194,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    -98,   -200,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex   -110,   -194,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex   -110,   -194,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -124,   -208,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -119,   -221,     68,    992,   -979,   0x00, 0x96, 0x44, 0xff
vertex   -116,   -221,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff

arrowTrapArrow_vertex_75: /* 10 vertices out of 15 */
vertex   -116,   -221,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff
vertex   -110,   -208,     87,   -139,  -1465,   0x00, 0xc9, 0x72, 0xff
vertex   -124,   -208,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -124,   -208,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -119,   -221,     68,    915,     77,   0x00, 0x96, 0x44, 0xff
vertex   -124,   -208,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -110,   -208,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex   -116,   -221,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex   -110,   -208,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -110,   -208,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff

arrowTrapArrow_vertex_76: /* 9 vertices out of 15 */
vertex   -137,   -202,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex   -137,   -200,     68,    991,  -1132,   0x6a, 0x00, 0xbc, 0xff
vertex   -124,   -194,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex   -124,   -194,     87,   2123,  -1465,   0x00, 0xdb, 0x87, 0xff
vertex   -124,   -208,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff
vertex   -124,   -208,     87,   2123,   -646,   0x00, 0x87, 0xdd, 0xff
vertex   -110,   -194,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex   -110,   -194,     87,   2123,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex   -124,   -194,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff

arrowTrapArrow_vertex_77: /* 9 vertices out of 15 */
vertex   -116,   -182,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff
vertex   -110,   -194,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex   -124,   -194,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex   -119,   -182,     68,    992,   -979,   0x00, 0x96, 0xbc, 0xff
vertex   -110,   -208,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex   -110,   -208,     87,   -139,   -646,   0x00, 0x6a, 0xbc, 0xff
vertex   -110,   -194,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    -98,   -202,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff
vertex    -98,   -200,     68,    991,  -1132,   0x96, 0x00, 0xbc, 0xff

arrowTrapArrow_vertex_78: /* 10 vertices out of 15 */
vertex   -124,   -208,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex   -110,   -208,     87,   -139,  -1465,   0x00, 0x6a, 0xbc, 0xff
vertex   -116,   -221,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff
vertex   -119,   -221,     68,    992,   -979,   0x00, 0x6a, 0xbc, 0xff
vertex   -110,   -101,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex   -110,   -101,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex   -110,   -101,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff
vertex   -124,   -101,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex   -124,   -101,     87,   -139,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,   -101,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff

arrowTrapArrow_vertex_79: /* 11 vertices out of 15 */
vertex   -110,   -101,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex   -124,   -101,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex   -124,   -101,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex   -124,    -87,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex   -124,    -87,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,    -87,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff
vertex   -110,    -87,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex   -110,    -87,    -87,  -8116,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -124,    -87,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex   -124,   -101,    -87,  -8116,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex   -124,   -101,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_80: /* 11 vertices out of 15 */
vertex   -124,   -101,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,    -87,     87,   2123,  -1465,   0x81, 0x00, 0x00, 0xff
vertex   -124,    -87,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex   -124,   -101,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -110,   -101,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex   -110,    -87,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex   -124,    -87,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex   -110,    -87,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -110,    -87,     87,   -139,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex   -110,    -87,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex   -110,   -101,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_81: /* 11 vertices out of 15 */
vertex   -110,    -87,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -110,   -101,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff
vertex   -110,   -101,    -87,  10100,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex   -124,    -87,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex   -110,    -87,    -87,    582,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -110,   -101,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex   -124,   -101,    -87,   1401,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex   -124,   -101,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -137,    -95,     68,   -141,   -979,   0x00, 0x00, 0x7f, 0xff
vertex   -124,   -101,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,   -101,     87,    582,   -646,   0x00, 0x81, 0x00, 0xff

arrowTrapArrow_vertex_82: /* 8 vertices out of 15 */
vertex   -124,    -87,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -124,    -87,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -137,    -92,     68,   -141,  -1132,   0x96, 0x00, 0x44, 0xff
vertex   -137,    -95,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex   -124,   -101,     87,   2123,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -124,   -101,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -124,    -87,     87,   2123,  -1465,   0x00, 0x37, 0x72, 0xff
vertex   -124,    -87,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_83: /* 11 vertices out of 15 */
vertex   -137,    -95,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex   -124,    -87,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -137,    -92,     68,    991,  -1132,   0x96, 0x00, 0x44, 0xff
vertex   -116,    -74,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex   -119,    -74,     68,    992,   -979,   0x00, 0x6a, 0x44, 0xff
vertex   -124,    -87,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex   -110,    -87,     87,   2123,  -1465,   0x37, 0x00, 0x72, 0xff
vertex   -110,    -87,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex   -110,    -87,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -116,    -74,     68,   1068,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex   -110,    -87,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff

arrowTrapArrow_vertex_84: /* 9 vertices out of 15 */
vertex   -110,    -87,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex   -110,    -87,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -124,    -87,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -119,    -74,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex   -124,    -87,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -124,    -87,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex   -110,   -101,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex   -110,   -101,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    -98,    -95,     68,   2125,   -979,   0x6a, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_85: /* 9 vertices out of 15 */
vertex    -98,    -95,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    -98,    -92,     68,    991,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex   -110,    -87,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex   -110,   -101,     87,   -139,   -646,   0x00, 0xc9, 0x72, 0xff
vertex   -110,   -101,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff
vertex   -110,    -87,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    -98,    -92,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex   -110,    -87,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex   -110,    -87,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_86: /* 10 vertices out of 15 */
vertex   -124,   -101,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -119,   -113,     68,    992,   -979,   0x00, 0x96, 0x44, 0xff
vertex   -116,   -113,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff
vertex   -110,   -101,     87,   -139,  -1465,   0x00, 0xc9, 0x72, 0xff
vertex   -124,   -101,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -119,   -113,     68,    915,     77,   0x00, 0x96, 0x44, 0xff
vertex   -124,   -101,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -110,   -101,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex   -116,   -113,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex   -110,   -101,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_87: /* 9 vertices out of 15 */
vertex   -110,   -101,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex   -116,   -113,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex   -110,   -101,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex   -137,    -95,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex   -137,    -92,     68,    991,  -1132,   0x6a, 0x00, 0xbc, 0xff
vertex   -124,    -87,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex   -124,    -87,     87,   2123,  -1465,   0x00, 0xdb, 0x87, 0xff
vertex   -124,   -101,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff
vertex   -124,   -101,     87,   2123,   -646,   0x00, 0x87, 0xdd, 0xff

arrowTrapArrow_vertex_88: /* 9 vertices out of 15 */
vertex   -110,    -87,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex   -110,    -87,     87,   2123,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex   -124,    -87,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex   -116,    -74,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff
vertex   -119,    -74,     68,    992,   -979,   0x00, 0x96, 0xbc, 0xff
vertex   -110,   -101,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex   -110,   -101,     87,   -139,   -646,   0x00, 0x6a, 0xbc, 0xff
vertex   -110,    -87,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    -98,    -95,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff

arrowTrapArrow_vertex_89: /* 11 vertices out of 15 */
vertex    -98,    -95,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff
vertex   -110,    -87,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    -98,    -92,     68,    991,  -1132,   0x96, 0x00, 0xbc, 0xff
vertex   -124,   -101,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex   -110,   -101,     87,   -139,  -1465,   0x00, 0x6a, 0xbc, 0xff
vertex   -116,   -113,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff
vertex   -119,   -113,     68,    992,   -979,   0x00, 0x6a, 0xbc, 0xff
vertex   -110,      6,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex   -110,      6,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex   -110,      6,     87,   -139,  -1465,   0x00, 0x81, 0x00, 0xff
vertex   -124,      6,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff

arrowTrapArrow_vertex_90: /* 9 vertices out of 15 */
vertex   -124,      6,     87,   -139,   -646,   0x00, 0x81, 0x00, 0xff
vertex   -124,      6,     87,   -139,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,      6,    -87,  10100,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex   -110,      6,    -87,  10100,  -1465,   0x49, 0xb7, 0xb7, 0xff
vertex   -124,     20,    -87,  -8116,   -646,   0xb7, 0x49, 0xb7, 0xff
vertex   -124,     20,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,     20,     87,   2123,   -646,   0x00, 0x7f, 0x00, 0xff
vertex   -110,     20,     87,   2123,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex   -110,     20,    -87,  -8116,  -1465,   0x49, 0x49, 0xb7, 0xff

arrowTrapArrow_vertex_91: /* 11 vertices out of 15 */
vertex   -124,     20,    -87,  -8116,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex   -124,      6,    -87,  -8116,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex   -124,      6,     87,   2123,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,     20,     87,   2123,  -1465,   0x81, 0x00, 0x00, 0xff
vertex   -124,      6,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -110,      6,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex   -110,     20,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex   -124,     20,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex   -110,     20,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -110,     20,     87,   -139,  -1465,   0x00, 0x7f, 0x00, 0xff
vertex   -110,     20,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_92: /* 11 vertices out of 15 */
vertex   -110,     20,    -87,  10100,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -110,     20,     87,   -139,  -1465,   0x7f, 0x00, 0x00, 0xff
vertex   -110,      6,     87,   -139,   -646,   0x7f, 0x00, 0x00, 0xff
vertex   -110,      6,    -87,  10100,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex   -124,     20,    -87,   1401,  -1465,   0xb7, 0x49, 0xb7, 0xff
vertex   -110,     20,    -87,    582,  -1465,   0x49, 0x49, 0xb7, 0xff
vertex   -110,      6,    -87,    582,   -646,   0x49, 0xb7, 0xb7, 0xff
vertex   -124,      6,    -87,   1401,   -646,   0xb7, 0xb7, 0xb7, 0xff
vertex   -124,      6,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -137,     11,     68,   -141,   -979,   0x00, 0x00, 0x7f, 0xff
vertex   -124,      6,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff

arrowTrapArrow_vertex_93: /* 11 vertices out of 15 */
vertex   -124,      6,     87,    582,   -646,   0x81, 0x00, 0x00, 0xff
vertex   -124,      6,     87,    582,   -646,   0x00, 0x81, 0x00, 0xff
vertex   -124,      6,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -124,     20,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -124,     20,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -137,     14,     68,   -141,  -1132,   0x96, 0x00, 0x44, 0xff
vertex   -137,     11,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex   -124,      6,     87,   2123,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -124,      6,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -124,     20,     87,   2123,  -1465,   0x00, 0x37, 0x72, 0xff
vertex   -124,     20,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff

arrowTrapArrow_vertex_94: /* 9 vertices out of 15 */
vertex   -137,     11,     68,    991,   -979,   0x96, 0x00, 0x44, 0xff
vertex   -124,      6,     87,   2123,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -124,     20,     87,   2123,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -137,     14,     68,    991,  -1132,   0x96, 0x00, 0x44, 0xff
vertex   -116,     32,     68,    992,  -1132,   0x00, 0x6a, 0x44, 0xff
vertex   -119,     32,     68,    992,   -979,   0x00, 0x6a, 0x44, 0xff
vertex   -124,     20,     87,   2123,   -646,   0x00, 0x37, 0x72, 0xff
vertex   -110,     20,     87,   2123,  -1465,   0x37, 0x00, 0x72, 0xff
vertex   -110,     20,     87,   2123,  -1465,   0x00, 0x6a, 0x44, 0xff

arrowTrapArrow_vertex_95: /* 9 vertices out of 15 */
vertex   -110,     20,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -116,     32,     68,   1068,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex   -110,     20,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex   -124,     20,     87,    582,  -1465,   0x96, 0x00, 0x44, 0xff
vertex   -119,     32,     68,    915,  -2189,   0x00, 0x6a, 0x44, 0xff
vertex   -124,     20,     87,    582,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -124,     20,     87,    582,  -1465,   0x00, 0x37, 0x72, 0xff
vertex   -110,      6,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex   -110,      6,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff

arrowTrapArrow_vertex_96: /* 11 vertices out of 15 */
vertex   -110,      6,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex    -98,     11,     68,   2125,   -979,   0x6a, 0x00, 0x44, 0xff
vertex   -110,      6,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex    -98,     11,     68,    991,   -979,   0x6a, 0x00, 0x44, 0xff
vertex    -98,     14,     68,    991,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex   -110,     20,     87,   -139,  -1465,   0x37, 0x00, 0x72, 0xff
vertex   -110,      6,     87,   -139,   -646,   0x00, 0xc9, 0x72, 0xff
vertex   -110,      6,     87,   -139,   -646,   0x6a, 0x00, 0x44, 0xff
vertex   -110,     20,     87,   1401,  -1465,   0x37, 0x00, 0x72, 0xff
vertex    -98,     14,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex   -110,     20,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff

arrowTrapArrow_vertex_97: /* 10 vertices out of 15 */
vertex   -110,     20,     87,   1401,  -1465,   0x00, 0x6a, 0x44, 0xff
vertex    -98,     14,     68,   2125,  -1132,   0x6a, 0x00, 0x44, 0xff
vertex   -110,     20,     87,   1401,  -1465,   0x00, 0x00, 0x7f, 0xff
vertex   -124,      6,     87,   -139,   -646,   0xd7, 0xd7, 0x70, 0xff
vertex   -119,     -6,     68,    992,   -979,   0x00, 0x96, 0x44, 0xff
vertex   -116,     -6,     68,    992,  -1132,   0x00, 0x96, 0x44, 0xff
vertex   -110,      6,     87,   -139,  -1465,   0x00, 0xc9, 0x72, 0xff
vertex   -124,      6,     87,    582,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -119,     -6,     68,    915,     77,   0x00, 0x96, 0x44, 0xff
vertex   -124,      6,     87,    582,   -646,   0xd7, 0xd7, 0x70, 0xff

arrowTrapArrow_vertex_98: /* 9 vertices out of 15 */
vertex   -110,      6,     87,   1401,   -646,   0x6a, 0x00, 0x44, 0xff
vertex   -116,     -6,     68,   1068,     77,   0x00, 0x96, 0x44, 0xff
vertex   -110,      6,     87,   1401,   -646,   0x00, 0x00, 0x7f, 0xff
vertex   -110,      6,     87,   1401,   -646,   0x00, 0xc9, 0x72, 0xff
vertex   -137,     11,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex   -137,     14,     68,    991,  -1132,   0x6a, 0x00, 0xbc, 0xff
vertex   -124,     20,     87,   2123,  -1465,   0x60, 0x00, 0xae, 0xff
vertex   -124,     20,     87,   2123,  -1465,   0x00, 0xdb, 0x87, 0xff
vertex   -124,      6,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff

arrowTrapArrow_vertex_99: /* 11 vertices out of 15 */
vertex   -137,     11,     68,    991,   -979,   0x6a, 0x00, 0xbc, 0xff
vertex   -124,      6,     87,   2123,   -646,   0x45, 0x08, 0x96, 0xff
vertex   -124,      6,     87,   2123,   -646,   0x00, 0x87, 0xdd, 0xff
vertex   -110,     20,     87,   2123,  -1465,   0x00, 0x9c, 0x4d, 0xff
vertex   -110,     20,     87,   2123,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex   -124,     20,     87,   2123,   -646,   0x00, 0xdb, 0x87, 0xff
vertex   -116,     32,     68,    992,  -1132,   0x00, 0x96, 0xbc, 0xff
vertex   -119,     32,     68,    992,   -979,   0x00, 0x96, 0xbc, 0xff
vertex   -110,      6,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex   -110,      6,     87,   -139,   -646,   0x00, 0x6a, 0xbc, 0xff
vertex   -110,     20,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff

arrowTrapArrow_vertex_100: /* 8 vertices out of 12 */
vertex    -98,     11,     68,    991,   -979,   0x96, 0x00, 0xbc, 0xff
vertex   -110,      6,     87,   -139,   -646,   0x96, 0x00, 0xbc, 0xff
vertex   -110,     20,     87,   -139,  -1465,   0x9c, 0x00, 0x4d, 0xff
vertex    -98,     14,     68,    991,  -1132,   0x96, 0x00, 0xbc, 0xff
vertex   -124,      6,     87,   -139,   -646,   0x45, 0x08, 0x96, 0xff
vertex   -110,      6,     87,   -139,  -1465,   0x00, 0x6a, 0xbc, 0xff
vertex   -116,     -6,     68,    992,  -1132,   0x00, 0x6a, 0xbc, 0xff
vertex   -119,     -6,     68,    992,   -979,   0x00, 0x6a, 0xbc, 0xff

/* Render order: 1 */

glabel arrowTrapArrow_dl_opaque
gsSPClearGeometryMode G_LIGHTING
/* #LIGHTING 07 - Default */
gsDPPipeSync
gsSPSetGeometryMode G_LIGHTING
gsSPNumLights NUMLIGHTS_1
gsSPLight arrowTrapArrow_diffuse_light, 1
gsSPLight arrowTrapArrow_ambient_light, 2
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock arrowTrapArrow_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSPVertex arrowTrapArrow_vertex_0, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 0, 3, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_1, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_2, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 3, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_3, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 8, 0x00
gsSP1Triangle 8, 9, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_4, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 0, 2, 4, 0x00
gsSP1Triangle 0, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_5, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 4, 4, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_6, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 4, 0x00
gsSP1Triangle 4, 5, 3, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_7, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 4, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_8, 10, 0
gsSP1Triangle 0, 1, 0, 0x00
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 4, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_9, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 8, 5, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_10, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 3, 5, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_11, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 3, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_12, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 0, 3, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 8, 5, 0x00
gsSPVertex arrowTrapArrow_vertex_13, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 4, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_14, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_15, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSP1Triangle 3, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_16, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 0, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 5, 5, 0x00
gsSPVertex arrowTrapArrow_vertex_17, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 1, 0, 0x00
gsSP1Triangle 4, 5, 5, 0x00
gsSP1Triangle 5, 6, 4, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_18, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_19, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 3, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 9, 7, 6, 0x00
gsSPVertex arrowTrapArrow_vertex_20, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 0, 2, 4, 0x00
gsSP1Triangle 0, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_21, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 4, 6, 0x00
gsSP1Triangle 7, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_22, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_23, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 3, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_24, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_25, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_26, 8, 0
gsSP1Triangle 0, 1, 1, 0x00
gsSP1Triangle 1, 2, 0, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_27, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_28, 9, 0
gsSP1Triangle 0, 1, 1, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 5, 3, 2, 0x00
gsSP1Triangle 6, 7, 7, 0x00
gsSP1Triangle 7, 8, 6, 0x00
gsSPVertex arrowTrapArrow_vertex_29, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 0, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_30, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 4, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_31, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSP1Triangle 3, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_32, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 8, 5, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_33, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_34, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 4, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_35, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_36, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_37, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 4, 0x00
gsSP1Triangle 4, 5, 3, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_38, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 4, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_39, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 0, 0, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 4, 3, 0x00
gsSP1Triangle 7, 8, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_40, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_41, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 7, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_42, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 1, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 4, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_43, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 3, 5, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_44, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_45, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 0, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 5, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_46, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_47, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 0, 3, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 8, 5, 0x00
gsSPVertex arrowTrapArrow_vertex_48, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 5, 0x00
gsSP1Triangle 5, 6, 4, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_49, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_50, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 3, 3, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 9, 7, 6, 0x00
gsSPVertex arrowTrapArrow_vertex_51, 8, 0
gsSP1Triangle 0, 1, 1, 0x00
gsSP1Triangle 1, 2, 0, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_52, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 1, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_53, 12, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 4, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 11, 0x00
gsSPVertex arrowTrapArrow_vertex_54, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 4, 6, 0x00
gsSP1Triangle 7, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_55, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 8, 5, 0x00
gsSPVertex arrowTrapArrow_vertex_56, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 0, 3, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_57, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_58, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 3, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_59, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 8, 0x00
gsSP1Triangle 8, 9, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_60, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 0, 2, 4, 0x00
gsSP1Triangle 0, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_61, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 4, 4, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_62, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 4, 0x00
gsSP1Triangle 4, 5, 3, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_63, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 4, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_64, 10, 0
gsSP1Triangle 0, 1, 0, 0x00
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 4, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_65, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 8, 5, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_66, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 3, 5, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_67, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 3, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_68, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 0, 3, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 8, 5, 0x00
gsSPVertex arrowTrapArrow_vertex_69, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 4, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_70, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_71, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSP1Triangle 3, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_72, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 0, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 5, 5, 0x00
gsSPVertex arrowTrapArrow_vertex_73, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 1, 0, 0x00
gsSP1Triangle 4, 5, 5, 0x00
gsSP1Triangle 5, 6, 4, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_74, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_75, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 3, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 9, 7, 6, 0x00
gsSPVertex arrowTrapArrow_vertex_76, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 0, 2, 4, 0x00
gsSP1Triangle 0, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_77, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 4, 6, 0x00
gsSP1Triangle 7, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_78, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_79, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 3, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_80, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_81, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_82, 8, 0
gsSP1Triangle 0, 1, 1, 0x00
gsSP1Triangle 1, 2, 0, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_83, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_84, 9, 0
gsSP1Triangle 0, 1, 1, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 5, 3, 2, 0x00
gsSP1Triangle 6, 7, 7, 0x00
gsSP1Triangle 7, 8, 6, 0x00
gsSPVertex arrowTrapArrow_vertex_85, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 0, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_86, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 4, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_87, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSP1Triangle 3, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_88, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 8, 5, 7, 0x00
gsSPVertex arrowTrapArrow_vertex_89, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_90, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 4, 7, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_91, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_92, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_93, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 4, 0x00
gsSP1Triangle 4, 5, 3, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_94, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 4, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_95, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 0, 0, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 4, 3, 0x00
gsSP1Triangle 7, 8, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_96, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 3, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_97, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 7, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex arrowTrapArrow_vertex_98, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 1, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 4, 6, 8, 0x00
gsSPVertex arrowTrapArrow_vertex_99, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 3, 5, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex arrowTrapArrow_vertex_100, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPEndDisplayList
