/* Generated by modconv 2 */

glabel floorArrowTrap_collision
colInit
colVertexInit 8
colVertex 51, 3, -44
colVertex -52, 3, -44
colVertex 51, 3, 42
colVertex -52, 3, 42
colVertex -52, 0, -44
colVertex -52, 0, 42
colVertex 51, 0, 42
colVertex 51, 0, -44

colTriInit SURFACE_DEFAULT, 10
colTri      0,      1,      2
colTri      1,      3,      2
colTri      3,      1,      4
colTri      3,      4,      5
colTri      2,      3,      5
colTri      2,      5,      6
colTri      2,      7,      0
colTri      7,      2,      6
colTri      0,      4,      1
colTri      4,      0,      7
colTriStop
colEnd
