/* Generated by modconv 2 */

glabel floorArrowTrap_geo
                        geo_scale 0x00, 16384
            geo_open_node
                geo_display_list LAYER_OPAQUE floorArrowTrap_dl_opaque
            geo_close_node
            geo_end
