/* Generated by modconv 2 */

floorArrowTrap_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
floorArrowTrap_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

floorArrowTrap_texture_0:
.incbin "actors/floorArrowTrap/mossyTile.rgba16"

floorArrowTrap_vertex_0: /* 11 vertices out of 15 */
vertex    210,     15,   -175,   2016,  -1824,   0x00, 0x7f, 0x00, 0x00
vertex   -210,     15,   -175,  -1056,  -1824,   0x00, 0x7f, 0x00, 0x00
vertex    210,     15,    174,   2016,    736,   0x00, 0x7f, 0x00, 0x00
vertex   -210,     15,    174,  -1056,    735,   0x00, 0x7f, 0x00, 0x00
vertex   -210,     15,    174,   1759,   -230,   0x81, 0x00, 0x00, 0x00
vertex   -210,     15,   -175,   -800,   -230,   0x81, 0x00, 0x00, 0x00
vertex   -210,      0,   -175,   -800,   -114,   0x81, 0x00, 0x00, 0x00
vertex   -210,      0,    174,   1759,   -114,   0x81, 0x00, 0x00, 0x00
vertex    210,     15,    174,   2016,   -230,   0x00, 0x00, 0x7f, 0x00
vertex   -210,     15,    174,  -1056,   -230,   0x00, 0x00, 0x7f, 0x00
vertex   -210,      0,    174,  -1056,   -114,   0x00, 0x00, 0x7f, 0x00

floorArrowTrap_vertex_1: /* 11 vertices out of 15 */
vertex    210,     15,    174,   2016,   -230,   0x00, 0x00, 0x7f, 0x00
vertex   -210,      0,    174,  -1056,   -114,   0x00, 0x00, 0x7f, 0x00
vertex    210,      0,    174,   2016,   -114,   0x00, 0x00, 0x7f, 0x00
vertex    210,     15,    174,   -800,   -230,   0x7f, 0x00, 0x00, 0x00
vertex    210,      0,   -175,   1759,   -114,   0x7f, 0x00, 0x00, 0x00
vertex    210,     15,   -175,   1760,   -230,   0x7f, 0x00, 0x00, 0x00
vertex    210,      0,    174,   -800,   -114,   0x7f, 0x00, 0x00, 0x00
vertex    210,     15,   -175,  -1056,   -230,   0x00, 0x00, 0x81, 0x00
vertex   -210,      0,   -175,   2016,   -114,   0x00, 0x00, 0x81, 0x00
vertex   -210,     15,   -175,   2016,   -230,   0x00, 0x00, 0x81, 0x00
vertex    210,      0,   -175,  -1056,   -114,   0x00, 0x00, 0x81, 0x00

/* Render order: 1 */

glabel floorArrowTrap_dl_opaque
gsSPClearGeometryMode G_LIGHTING
/* #LIGHTING 01 - Default */
gsDPPipeSync
gsSPSetGeometryMode G_LIGHTING
gsSPNumLights NUMLIGHTS_1
gsSPLight floorArrowTrap_diffuse_light, 1
gsSPLight floorArrowTrap_ambient_light, 2
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock floorArrowTrap_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSPVertex floorArrowTrap_vertex_0, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex floorArrowTrap_vertex_1, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 8, 7, 10, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPEndDisplayList
