/* Generated by modconv 2 */

model_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
model_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

model_texture_0:
.incbin "levels/bob/clouds.rgba16"

model_texture_1:
.incbin "levels/bob/mossyBrick.rgba16"

model_texture_2:
.incbin "levels/bob/shingle.rgba16"

model_texture_3:
.incbin "levels/bob/woodDoor.rgba16"

model_texture_4:
.incbin "levels/bob/mossyTile.rgba16"

model_texture_6:
.incbin "levels/bob/stone.rgba16"

model_texture_7:
.incbin "levels/bob/vines.rgba16"
