/* Generated by modconv 2 */

glabel smoughMass_geo
    geo_shadow SHADOW_CIRCLE_4_VERTS, 0xC8, 75
        geo_open_node
            geo_scale 0x00, 16384
            geo_open_node
                geo_display_list LAYER_OPAQUE smoughMass_dl_opaque
            geo_close_node
        geo_close_node
    geo_end
