/* Generated by modconv 2 */

smoughMass_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
smoughMass_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

smoughMass_texture_0:
.incbin "actors/smoughMass/smoughHead.rgba16"

smoughMass_vertex_0: /* 7 vertices out of 15 */
vertex      7,    138,    -18,   4895, -10355,   0xff, 0xff, 0xff, 0xff
vertex     24,    150,      2,   5112, -10676,   0xff, 0xff, 0xff, 0xff
vertex     23,    143,    -15,   4931, -10680,   0xff, 0xff, 0xff, 0xff
vertex      0,    154,      5,   5140, -10196,   0xff, 0xff, 0xff, 0xff
vertex     54,    136,     -6,   5024, -11328,   0xff, 0xff, 0xff, 0xff
vertex     40,    135,    -26,   4808, -11039,   0xff, 0xff, 0xff, 0xff
vertex     24,    121,    -49,   4520, -10740,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_1: /* 9 vertices out of 15 */
vertex     24,    121,    -49,   4520, -10740,   0xff, 0xff, 0xff, 0xff
vertex     23,    143,    -15,   4931, -10680,   0xff, 0xff, 0xff, 0xff
vertex     40,    135,    -26,   4808, -11039,   0xff, 0xff, 0xff, 0xff
vertex     54,    136,     -6,   5024, -11328,   0xff, 0xff, 0xff, 0xff
vertex     83,    107,    -10,   4958, -12150,   0xff, 0xff, 0xff, 0xff
vertex     80,    103,    -27,   4758, -12123,   0xff, 0xff, 0xff, 0xff
vertex     70,    110,    -37,   4651, -11829,   0xff, 0xff, 0xff, 0xff
vertex     80,     81,    -27,   4696, -12446,   0xff, 0xff, 0xff, 0xff
vertex     87,     74,     -3,   5031, -12726,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_2: /* 8 vertices out of 15 */
vertex     80,     81,    -27,   4696, -12446,   0xff, 0xff, 0xff, 0xff
vertex     70,    110,    -37,   4651, -11829,   0xff, 0xff, 0xff, 0xff
vertex     80,    103,    -27,   4758, -12123,   0xff, 0xff, 0xff, 0xff
vertex     74,     78,    -57,   4295, -12227,   0xff, 0xff, 0xff, 0xff
vertex     53,    115,    -39,   4628, -11428,   0xff, 0xff, 0xff, 0xff
vertex     54,    136,     -6,   5024, -11328,   0xff, 0xff, 0xff, 0xff
vertex     40,    135,    -26,   4808, -11039,   0xff, 0xff, 0xff, 0xff
vertex     53,    103,    -55,   4399, -11498,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_3: /* 7 vertices out of 15 */
vertex     53,    115,    -39,   4628, -11428,   0xff, 0xff, 0xff, 0xff
vertex     70,    110,    -37,   4651, -11829,   0xff, 0xff, 0xff, 0xff
vertex     53,    103,    -55,   4399, -11498,   0xff, 0xff, 0xff, 0xff
vertex     24,    121,    -49,   4520, -10740,   0xff, 0xff, 0xff, 0xff
vertex     40,    135,    -26,   4808, -11039,   0xff, 0xff, 0xff, 0xff
vertex     39,     93,    -73,   4133, -11190,   0xff, 0xff, 0xff, 0xff
vertex     52,     92,    -67,   4220, -11538,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_4: /* 9 vertices out of 15 */
vertex     74,     78,    -57,   4295, -12227,   0xff, 0xff, 0xff, 0xff
vertex     52,     92,    -67,   4220, -11538,   0xff, 0xff, 0xff, 0xff
vertex     53,    103,    -55,   4399, -11498,   0xff, 0xff, 0xff, 0xff
vertex     58,     73,    -72,   4052, -11849,   0xff, 0xff, 0xff, 0xff
vertex     39,     93,    -73,   4133, -11190,   0xff, 0xff, 0xff, 0xff
vertex     32,     67,    -79,   3856, -11154,   0xff, 0xff, 0xff, 0xff
vertex     -7,    136,    -24,   4829, -10029,   0xff, 0xff, 0xff, 0xff
vertex      0,    154,      5,   5140, -10196,   0xff, 0xff, 0xff, 0xff
vertex      7,    138,    -18,   4895, -10355,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_5: /* 7 vertices out of 15 */
vertex    -22,    140,    -12,   4959,  -9722,   0xff, 0xff, 0xff, 0xff
vertex      0,    154,      5,   5140, -10196,   0xff, 0xff, 0xff, 0xff
vertex     -7,    136,    -24,   4829, -10029,   0xff, 0xff, 0xff, 0xff
vertex     24,    121,    -49,   4520, -10740,   0xff, 0xff, 0xff, 0xff
vertex     -8,    122,    -40,   4616,  -9974,   0xff, 0xff, 0xff, 0xff
vertex      7,    138,    -18,   4895, -10355,   0xff, 0xff, 0xff, 0xff
vertex    -38,    122,    -37,   4661,  -9323,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_6: /* 7 vertices out of 15 */
vertex     24,    121,    -49,   4520, -10740,   0xff, 0xff, 0xff, 0xff
vertex     39,     93,    -73,   4133, -11190,   0xff, 0xff, 0xff, 0xff
vertex     20,     90,    -77,   4056, -10717,   0xff, 0xff, 0xff, 0xff
vertex      9,    103,    -70,   4213, -10420,   0xff, 0xff, 0xff, 0xff
vertex     32,     67,    -79,   3856, -11154,   0xff, 0xff, 0xff, 0xff
vertex      9,     74,    -80,   3886, -10425,   0xff, 0xff, 0xff, 0xff
vertex    -17,     82,    -82,   3944,  -9676,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_7: /* 8 vertices out of 15 */
vertex      9,     74,    -80,   3886, -10425,   0xff, 0xff, 0xff, 0xff
vertex      9,    103,    -70,   4213, -10420,   0xff, 0xff, 0xff, 0xff
vertex     20,     90,    -77,   4056, -10717,   0xff, 0xff, 0xff, 0xff
vertex     24,    121,    -49,   4520, -10740,   0xff, 0xff, 0xff, 0xff
vertex     -8,    110,    -57,   4385,  -9967,   0xff, 0xff, 0xff, 0xff
vertex     -8,    122,    -40,   4616,  -9974,   0xff, 0xff, 0xff, 0xff
vertex    -17,     82,    -82,   3944,  -9676,   0xff, 0xff, 0xff, 0xff
vertex    -23,    102,    -64,   4276,  -9574,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_8: /* 7 vertices out of 15 */
vertex    -23,    102,    -64,   4276,  -9574,   0xff, 0xff, 0xff, 0xff
vertex     -8,    122,    -40,   4616,  -9974,   0xff, 0xff, 0xff, 0xff
vertex     -8,    110,    -57,   4385,  -9967,   0xff, 0xff, 0xff, 0xff
vertex    -38,    122,    -37,   4661,  -9323,   0xff, 0xff, 0xff, 0xff
vertex    -38,     94,    -65,   4234,  -9177,   0xff, 0xff, 0xff, 0xff
vertex    -53,     99,    -55,   4397,  -8841,   0xff, 0xff, 0xff, 0xff
vertex    -17,     82,    -82,   3944,  -9676,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_9: /* 9 vertices out of 15 */
vertex    -38,     94,    -65,   4234,  -9177,   0xff, 0xff, 0xff, 0xff
vertex    -17,     82,    -82,   3944,  -9676,   0xff, 0xff, 0xff, 0xff
vertex    -41,     79,    -71,   4073,  -8986,   0xff, 0xff, 0xff, 0xff
vertex    -53,     99,    -55,   4397,  -8841,   0xff, 0xff, 0xff, 0xff
vertex    -71,     70,    -61,   4204,  -8125,   0xff, 0xff, 0xff, 0xff
vertex    -31,    142,      1,   5107,  -9541,   0xff, 0xff, 0xff, 0xff
vertex    -19,    148,     18,   5266,  -9806,   0xff, 0xff, 0xff, 0xff
vertex      0,    154,      5,   5140, -10196,   0xff, 0xff, 0xff, 0xff
vertex    -22,    140,    -12,   4959,  -9722,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_10: /* 8 vertices out of 15 */
vertex    -31,    142,      1,   5107,  -9541,   0xff, 0xff, 0xff, 0xff
vertex    -22,    140,    -12,   4959,  -9722,   0xff, 0xff, 0xff, 0xff
vertex    -44,    134,     -6,   5021,  -9239,   0xff, 0xff, 0xff, 0xff
vertex    -38,    122,    -37,   4661,  -9323,   0xff, 0xff, 0xff, 0xff
vertex    -37,    135,     23,   5338,  -9397,   0xff, 0xff, 0xff, 0xff
vertex    -19,    148,     18,   5266,  -9806,   0xff, 0xff, 0xff, 0xff
vertex    -53,     99,    -55,   4397,  -8841,   0xff, 0xff, 0xff, 0xff
vertex    -62,     98,    -44,   4531,  -8592,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_11: /* 7 vertices out of 15 */
vertex    -38,    122,    -37,   4661,  -9323,   0xff, 0xff, 0xff, 0xff
vertex    -62,     98,    -44,   4531,  -8592,   0xff, 0xff, 0xff, 0xff
vertex    -59,    114,    -31,   4723,  -8803,   0xff, 0xff, 0xff, 0xff
vertex    -53,     99,    -55,   4397,  -8841,   0xff, 0xff, 0xff, 0xff
vertex    -71,     70,    -61,   4204,  -8125,   0xff, 0xff, 0xff, 0xff
vertex    -81,     81,    -41,   4535,  -7984,   0xff, 0xff, 0xff, 0xff
vertex    -83,     86,    -14,   4889,  -7954,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_12: /* 7 vertices out of 15 */
vertex    -54,    124,    -13,   4940,  -8980,   0xff, 0xff, 0xff, 0xff
vertex    -38,    122,    -37,   4661,  -9323,   0xff, 0xff, 0xff, 0xff
vertex    -59,    114,    -31,   4723,  -8803,   0xff, 0xff, 0xff, 0xff
vertex    -44,    134,     -6,   5021,  -9239,   0xff, 0xff, 0xff, 0xff
vertex    -83,     86,    -14,   4889,  -7954,   0xff, 0xff, 0xff, 0xff
vertex    -56,    114,      0,   5080,  -8830,   0xff, 0xff, 0xff, 0xff
vertex    -37,    135,     23,   5338,  -9397,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_13: /* 8 vertices out of 15 */
vertex    -56,    114,      0,   5080,  -8830,   0xff, 0xff, 0xff, 0xff
vertex    -44,    134,     -6,   5021,  -9239,   0xff, 0xff, 0xff, 0xff
vertex    -54,    124,    -13,   4940,  -8980,   0xff, 0xff, 0xff, 0xff
vertex    -37,    135,     23,   5338,  -9397,   0xff, 0xff, 0xff, 0xff
vertex    -59,    105,     14,   5265,  -8688,   0xff, 0xff, 0xff, 0xff
vertex    -47,    107,     32,   5485,  -8992,   0xff, 0xff, 0xff, 0xff
vertex    -83,     86,    -14,   4889,  -7954,   0xff, 0xff, 0xff, 0xff
vertex    -76,     86,     15,   5298,  -8087,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_14: /* 9 vertices out of 15 */
vertex    -76,     86,     15,   5298,  -8087,   0xff, 0xff, 0xff, 0xff
vertex    -47,    107,     32,   5485,  -8992,   0xff, 0xff, 0xff, 0xff
vertex    -59,    105,     14,   5265,  -8688,   0xff, 0xff, 0xff, 0xff
vertex    -63,     80,     43,   5702,  -8340,   0xff, 0xff, 0xff, 0xff
vertex     -6,    149,     32,   5406, -10072,   0xff, 0xff, 0xff, 0xff
vertex      0,    154,      5,   5140, -10196,   0xff, 0xff, 0xff, 0xff
vertex    -19,    148,     18,   5266,  -9806,   0xff, 0xff, 0xff, 0xff
vertex     10,    154,     31,   5384, -10388,   0xff, 0xff, 0xff, 0xff
vertex    -37,    135,     23,   5338,  -9397,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_15: /* 8 vertices out of 15 */
vertex     -6,    149,     32,   5406, -10072,   0xff, 0xff, 0xff, 0xff
vertex    -37,    135,     23,   5338,  -9397,   0xff, 0xff, 0xff, 0xff
vertex     -2,    142,     44,   5534, -10134,   0xff, 0xff, 0xff, 0xff
vertex     10,    154,     31,   5384, -10388,   0xff, 0xff, 0xff, 0xff
vertex     31,    139,     50,   5597, -10824,   0xff, 0xff, 0xff, 0xff
vertex    -33,    108,     49,   5695,  -9347,   0xff, 0xff, 0xff, 0xff
vertex    -17,    121,     51,   5675,  -9789,   0xff, 0xff, 0xff, 0xff
vertex    -47,    107,     32,   5485,  -8992,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_16: /* 8 vertices out of 15 */
vertex    -63,     80,     43,   5702,  -8340,   0xff, 0xff, 0xff, 0xff
vertex    -33,    108,     49,   5695,  -9347,   0xff, 0xff, 0xff, 0xff
vertex    -47,    107,     32,   5485,  -8992,   0xff, 0xff, 0xff, 0xff
vertex    -36,     84,     64,   5994,  -9141,   0xff, 0xff, 0xff, 0xff
vertex     -7,     83,     78,   6190,  -9953,   0xff, 0xff, 0xff, 0xff
vertex    -17,    121,     51,   5675,  -9789,   0xff, 0xff, 0xff, 0xff
vertex     -2,    142,     44,   5534, -10134,   0xff, 0xff, 0xff, 0xff
vertex    -37,    135,     23,   5338,  -9397,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_17: /* 6 vertices out of 15 */
vertex     -2,    142,     44,   5534, -10134,   0xff, 0xff, 0xff, 0xff
vertex    -17,    121,     51,   5675,  -9789,   0xff, 0xff, 0xff, 0xff
vertex     -1,    128,     55,   5697, -10163,   0xff, 0xff, 0xff, 0xff
vertex     -7,     83,     78,   6190,  -9953,   0xff, 0xff, 0xff, 0xff
vertex     16,    114,     64,   5845, -10558,   0xff, 0xff, 0xff, 0xff
vertex     31,    139,     50,   5597, -10824,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_18: /* 7 vertices out of 15 */
vertex     42,    106,     67,   5892, -11204,   0xff, 0xff, 0xff, 0xff
vertex     16,    114,     64,   5845, -10558,   0xff, 0xff, 0xff, 0xff
vertex     27,    100,     73,   6003, -10858,   0xff, 0xff, 0xff, 0xff
vertex     31,    139,     50,   5597, -10824,   0xff, 0xff, 0xff, 0xff
vertex     -7,     83,     78,   6190,  -9953,   0xff, 0xff, 0xff, 0xff
vertex     20,     80,     90,   6328, -10735,   0xff, 0xff, 0xff, 0xff
vertex     44,     71,     89,   6361, -11411,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_19: /* 9 vertices out of 15 */
vertex     44,     71,     89,   6361, -11411,   0xff, 0xff, 0xff, 0xff
vertex     27,    100,     73,   6003, -10858,   0xff, 0xff, 0xff, 0xff
vertex     20,     80,     90,   6328, -10735,   0xff, 0xff, 0xff, 0xff
vertex     10,    154,     31,   5384, -10388,   0xff, 0xff, 0xff, 0xff
vertex     25,    154,     19,   5276, -10682,   0xff, 0xff, 0xff, 0xff
vertex      0,    154,      5,   5140, -10196,   0xff, 0xff, 0xff, 0xff
vertex     24,    150,      2,   5112, -10676,   0xff, 0xff, 0xff, 0xff
vertex     31,    139,     50,   5597, -10824,   0xff, 0xff, 0xff, 0xff
vertex     37,    143,     25,   5349, -10957,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_20: /* 10 vertices out of 15 */
vertex     24,    150,      2,   5112, -10676,   0xff, 0xff, 0xff, 0xff
vertex     37,    143,     25,   5349, -10957,   0xff, 0xff, 0xff, 0xff
vertex     54,    136,     -6,   5024, -11328,   0xff, 0xff, 0xff, 0xff
vertex     25,    154,     19,   5276, -10682,   0xff, 0xff, 0xff, 0xff
vertex     60,    116,     46,   5617, -11554,   0xff, 0xff, 0xff, 0xff
vertex     42,    106,     67,   5892, -11204,   0xff, 0xff, 0xff, 0xff
vertex     58,    106,     62,   5827, -11556,   0xff, 0xff, 0xff, 0xff
vertex     31,    139,     50,   5597, -10824,   0xff, 0xff, 0xff, 0xff
vertex     44,     71,     89,   6361, -11411,   0xff, 0xff, 0xff, 0xff
vertex     64,     84,     69,   6003, -11879,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_21: /* 8 vertices out of 15 */
vertex     42,    106,     67,   5892, -11204,   0xff, 0xff, 0xff, 0xff
vertex     64,     84,     69,   6003, -11879,   0xff, 0xff, 0xff, 0xff
vertex     58,    106,     62,   5827, -11556,   0xff, 0xff, 0xff, 0xff
vertex     76,     84,     42,   5673, -12262,   0xff, 0xff, 0xff, 0xff
vertex     60,    116,     46,   5617, -11554,   0xff, 0xff, 0xff, 0xff
vertex     37,    143,     25,   5349, -10957,   0xff, 0xff, 0xff, 0xff
vertex     60,    126,     30,   5422, -11495,   0xff, 0xff, 0xff, 0xff
vertex     31,    139,     50,   5597, -10824,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_22: /* 8 vertices out of 15 */
vertex     76,     84,     42,   5673, -12262,   0xff, 0xff, 0xff, 0xff
vertex     73,    117,     15,   5260, -11854,   0xff, 0xff, 0xff, 0xff
vertex     60,    116,     46,   5617, -11554,   0xff, 0xff, 0xff, 0xff
vertex     60,    126,     30,   5422, -11495,   0xff, 0xff, 0xff, 0xff
vertex     54,    136,     -6,   5024, -11328,   0xff, 0xff, 0xff, 0xff
vertex     37,    143,     25,   5349, -10957,   0xff, 0xff, 0xff, 0xff
vertex     83,    107,    -10,   4958, -12150,   0xff, 0xff, 0xff, 0xff
vertex     82,    102,      7,   5183, -12202,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_23: /* 7 vertices out of 15 */
vertex     73,    117,     15,   5260, -11854,   0xff, 0xff, 0xff, 0xff
vertex     83,    107,    -10,   4958, -12150,   0xff, 0xff, 0xff, 0xff
vertex     54,    136,     -6,   5024, -11328,   0xff, 0xff, 0xff, 0xff
vertex     76,     84,     42,   5673, -12262,   0xff, 0xff, 0xff, 0xff
vertex     82,    102,      7,   5183, -12202,   0xff, 0xff, 0xff, 0xff
vertex     86,     78,     21,   5391, -12614,   0xff, 0xff, 0xff, 0xff
vertex     87,     74,     -3,   5031, -12726,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_24: /* 7 vertices out of 15 */
vertex     88,     44,    -19,   4730, -13361,   0xff, 0xff, 0xff, 0xff
vertex     86,     41,     10,   5295, -13444,   0xff, 0xff, 0xff, 0xff
vertex     91,     31,     -4,   4990, -13802,   0xff, 0xff, 0xff, 0xff
vertex     87,     74,     -3,   5031, -12726,   0xff, 0xff, 0xff, 0xff
vertex    101,      6,     26,   5675, -14583,   0xff, 0xff, 0xff, 0xff
vertex    105,      9,     -5,   4960, -14646,   0xff, 0xff, 0xff, 0xff
vertex    105,      9,    -38,   4296, -14396,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_25: /* 9 vertices out of 15 */
vertex    105,      9,    -38,   4296, -14396,   0xff, 0xff, 0xff, 0xff
vertex     91,     31,     -4,   4990, -13802,   0xff, 0xff, 0xff, 0xff
vertex    105,      9,     -5,   4960, -14646,   0xff, 0xff, 0xff, 0xff
vertex    101,      6,     26,   5675, -14583,   0xff, 0xff, 0xff, 0xff
vertex    139,    -34,     35,   5792, -15672,   0xff, 0xff, 0xff, 0xff
vertex    135,    -27,     10,   5304, -15711,   0xff, 0xff, 0xff, 0xff
vertex    122,    -23,     55,   6214, -15122,   0xff, 0xff, 0xff, 0xff
vertex    146,    -57,     44,   5992, -16042,   0xff, 0xff, 0xff, 0xff
vertex    127,    -56,     79,   6715, -15343,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_26: /* 8 vertices out of 15 */
vertex    146,    -66,      1,   5123, -16543,   0xff, 0xff, 0xff, 0xff
vertex    139,    -34,     35,   5792, -15672,   0xff, 0xff, 0xff, 0xff
vertex    146,    -57,     44,   5992, -16042,   0xff, 0xff, 0xff, 0xff
vertex    135,    -27,     10,   5304, -15711,   0xff, 0xff, 0xff, 0xff
vertex    105,      9,     -5,   4960, -14646,   0xff, 0xff, 0xff, 0xff
vertex    101,      6,     26,   5675, -14583,   0xff, 0xff, 0xff, 0xff
vertex    126,    -18,     -4,   4992, -15501,   0xff, 0xff, 0xff, 0xff
vertex    134,    -31,    -26,   4531, -15698,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_27: /* 7 vertices out of 15 */
vertex    135,    -27,     10,   5304, -15711,   0xff, 0xff, 0xff, 0xff
vertex    134,    -31,    -26,   4531, -15698,   0xff, 0xff, 0xff, 0xff
vertex    126,    -18,     -4,   4992, -15501,   0xff, 0xff, 0xff, 0xff
vertex    105,      9,    -38,   4296, -14396,   0xff, 0xff, 0xff, 0xff
vertex    105,      9,     -5,   4960, -14646,   0xff, 0xff, 0xff, 0xff
vertex    138,    -35,    -49,   4130, -15537,   0xff, 0xff, 0xff, 0xff
vertex    125,    -18,    -64,   3862, -14885,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_28: /* 9 vertices out of 15 */
vertex    138,    -35,    -49,   4130, -15537,   0xff, 0xff, 0xff, 0xff
vertex    134,    -31,    -26,   4531, -15698,   0xff, 0xff, 0xff, 0xff
vertex    146,    -58,    -48,   4112, -16006,   0xff, 0xff, 0xff, 0xff
vertex    146,    -66,      1,   5123, -16543,   0xff, 0xff, 0xff, 0xff
vertex    121,    -51,    -88,   3300, -15004,   0xff, 0xff, 0xff, 0xff
vertex    125,    -18,    -64,   3862, -14885,   0xff, 0xff, 0xff, 0xff
vertex     22,     40,    -86,   3477, -10974,   0xff, 0xff, 0xff, 0xff
vertex     48,     40,    -81,   3597, -11901,   0xff, 0xff, 0xff, 0xff
vertex     38,     27,    -92,   3306, -11624,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_29: /* 7 vertices out of 15 */
vertex     48,     40,    -81,   3597, -11901,   0xff, 0xff, 0xff, 0xff
vertex     22,     40,    -86,   3477, -10974,   0xff, 0xff, 0xff, 0xff
vertex     32,     67,    -79,   3856, -11154,   0xff, 0xff, 0xff, 0xff
vertex     72,     13,    -90,   3358, -12902,   0xff, 0xff, 0xff, 0xff
vertex     38,     27,    -92,   3306, -11624,   0xff, 0xff, 0xff, 0xff
vertex     42,      7,   -102,   2986, -11854,   0xff, 0xff, 0xff, 0xff
vertex     10,      7,   -103,   2874, -10533,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_30: /* 6 vertices out of 15 */
vertex     72,     13,    -90,   3358, -12902,   0xff, 0xff, 0xff, 0xff
vertex     83,    -29,   -109,   2872, -13498,   0xff, 0xff, 0xff, 0xff
vertex     64,    -23,   -120,   2693, -12665,   0xff, 0xff, 0xff, 0xff
vertex     98,    -22,    -91,   3234, -14095,   0xff, 0xff, 0xff, 0xff
vertex     91,    -54,   -114,   2710, -13931,   0xff, 0xff, 0xff, 0xff
vertex    121,    -51,    -88,   3300, -15004,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_31: /* 7 vertices out of 15 */
vertex     64,    -23,   -120,   2693, -12665,   0xff, 0xff, 0xff, 0xff
vertex     91,    -54,   -114,   2710, -13931,   0xff, 0xff, 0xff, 0xff
vertex     46,    -65,   -139,   2107, -12071,   0xff, 0xff, 0xff, 0xff
vertex     42,      7,   -102,   2986, -11854,   0xff, 0xff, 0xff, 0xff
vertex     43,    -16,   -120,   2630, -11891,   0xff, 0xff, 0xff, 0xff
vertex     72,     13,    -90,   3358, -12902,   0xff, 0xff, 0xff, 0xff
vertex     32,    -31,   -133,   2382, -11415,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_32: /* 7 vertices out of 15 */
vertex     43,    -16,   -120,   2630, -11891,   0xff, 0xff, 0xff, 0xff
vertex     10,      7,   -103,   2874, -10533,   0xff, 0xff, 0xff, 0xff
vertex     42,      7,   -102,   2986, -11854,   0xff, 0xff, 0xff, 0xff
vertex     32,    -31,   -133,   2382, -11415,   0xff, 0xff, 0xff, 0xff
vertex    -11,    -28,   -131,   2374,  -9643,   0xff, 0xff, 0xff, 0xff
vertex      9,    -46,   -141,   2169, -10509,   0xff, 0xff, 0xff, 0xff
vertex     46,    -65,   -139,   2107, -12071,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_33: /* 9 vertices out of 15 */
vertex      9,    -46,   -141,   2169, -10509,   0xff, 0xff, 0xff, 0xff
vertex     46,    -65,   -139,   2107, -12071,   0xff, 0xff, 0xff, 0xff
vertex      2,    -69,   -144,   1932, -10190,   0xff, 0xff, 0xff, 0xff
vertex    -35,    -48,   -148,   2266,  -8761,   0xff, 0xff, 0xff, 0xff
vertex    -11,    -28,   -131,   2374,  -9643,   0xff, 0xff, 0xff, 0xff
vertex    -86,     44,    -49,   4258,  -7265,   0xff, 0xff, 0xff, 0xff
vertex    -66,     46,    -68,   3940,  -7902,   0xff, 0xff, 0xff, 0xff
vertex    -78,     32,    -62,   3953,  -7309,   0xff, 0xff, 0xff, 0xff
vertex    -71,     70,    -61,   4204,  -8125,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_34: /* 8 vertices out of 15 */
vertex    -51,     12,    -89,   3244,  -8018,   0xff, 0xff, 0xff, 0xff
vertex    -78,     32,    -62,   3953,  -7309,   0xff, 0xff, 0xff, 0xff
vertex    -66,     46,    -68,   3940,  -7902,   0xff, 0xff, 0xff, 0xff
vertex    -74,     12,    -67,   3681,  -7044,   0xff, 0xff, 0xff, 0xff
vertex    -95,     12,    -37,   4327,  -6236,   0xff, 0xff, 0xff, 0xff
vertex    -86,     44,    -49,   4258,  -7265,   0xff, 0xff, 0xff, 0xff
vertex    -73,    -21,   -119,   2867,  -7386,   0xff, 0xff, 0xff, 0xff
vertex    -48,    -13,   -117,   2753,  -8210,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_35: /* 7 vertices out of 15 */
vertex    -51,     12,    -89,   3244,  -8018,   0xff, 0xff, 0xff, 0xff
vertex    -73,    -21,   -119,   2867,  -7386,   0xff, 0xff, 0xff, 0xff
vertex    -84,    -14,    -98,   3169,  -6862,   0xff, 0xff, 0xff, 0xff
vertex    -48,    -13,   -117,   2753,  -8210,   0xff, 0xff, 0xff, 0xff
vertex    -72,    -43,   -124,   2631,  -7236,   0xff, 0xff, 0xff, 0xff
vertex    -35,    -48,   -148,   2266,  -8761,   0xff, 0xff, 0xff, 0xff
vertex   -103,    -44,    -76,   3380,  -5517,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_36: /* 7 vertices out of 15 */
vertex    -74,     12,    -67,   3681,  -7044,   0xff, 0xff, 0xff, 0xff
vertex    -51,     12,    -89,   3244,  -8018,   0xff, 0xff, 0xff, 0xff
vertex    -83,     -6,    -77,   3466,  -6593,   0xff, 0xff, 0xff, 0xff
vertex    -84,    -14,    -98,   3169,  -6862,   0xff, 0xff, 0xff, 0xff
vertex   -103,    -44,    -76,   3380,  -5517,   0xff, 0xff, 0xff, 0xff
vertex    -99,    -13,    -62,   3774,  -5893,   0xff, 0xff, 0xff, 0xff
vertex    -95,     12,    -37,   4327,  -6236,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_37: /* 8 vertices out of 15 */
vertex    -99,    -13,    -62,   3774,  -5893,   0xff, 0xff, 0xff, 0xff
vertex    -74,     12,    -67,   3681,  -7044,   0xff, 0xff, 0xff, 0xff
vertex    -83,     -6,    -77,   3466,  -6593,   0xff, 0xff, 0xff, 0xff
vertex    -95,     12,    -37,   4327,  -6236,   0xff, 0xff, 0xff, 0xff
vertex   -116,    -23,    -43,   4179,  -5245,   0xff, 0xff, 0xff, 0xff
vertex   -115,    -15,    -21,   4629,  -5200,   0xff, 0xff, 0xff, 0xff
vertex   -103,    -44,    -76,   3380,  -5517,   0xff, 0xff, 0xff, 0xff
vertex   -121,    -44,    -36,   4275,  -4652,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_38: /* 9 vertices out of 15 */
vertex   -121,    -44,    -36,   4275,  -4652,   0xff, 0xff, 0xff, 0xff
vertex   -115,    -15,    -21,   4629,  -5200,   0xff, 0xff, 0xff, 0xff
vertex   -116,    -23,    -43,   4179,  -5245,   0xff, 0xff, 0xff, 0xff
vertex   -132,    -52,      2,   5143,  -4250,   0xff, 0xff, 0xff, 0xff
vertex    -63,     48,     68,   6236,  -8012,   0xff, 0xff, 0xff, 0xff
vertex    -88,     49,     37,   5703,  -7241,   0xff, 0xff, 0xff, 0xff
vertex    -75,     37,     52,   6049,  -7351,   0xff, 0xff, 0xff, 0xff
vertex    -63,     80,     43,   5702,  -8340,   0xff, 0xff, 0xff, 0xff
vertex    -99,     12,     27,   5644,  -6093,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_39: /* 8 vertices out of 15 */
vertex    -75,     37,     52,   6049,  -7351,   0xff, 0xff, 0xff, 0xff
vertex    -99,     12,     27,   5644,  -6093,   0xff, 0xff, 0xff, 0xff
vertex    -75,     10,     53,   6302,  -6708,   0xff, 0xff, 0xff, 0xff
vertex    -52,      4,     80,   6938,  -7688,   0xff, 0xff, 0xff, 0xff
vertex    -63,     48,     68,   6236,  -8012,   0xff, 0xff, 0xff, 0xff
vertex   -101,    -29,     53,   6350,  -5328,   0xff, 0xff, 0xff, 0xff
vertex   -117,    -21,     14,   5411,  -4994,   0xff, 0xff, 0xff, 0xff
vertex   -115,    -38,     37,   5958,  -4806,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_40: /* 9 vertices out of 15 */
vertex   -132,    -52,      2,   5143,  -4250,   0xff, 0xff, 0xff, 0xff
vertex   -115,    -38,     37,   5958,  -4806,   0xff, 0xff, 0xff, 0xff
vertex   -117,    -21,     14,   5411,  -4994,   0xff, 0xff, 0xff, 0xff
vertex   -119,    -63,     43,   6136,  -4343,   0xff, 0xff, 0xff, 0xff
vertex   -101,    -29,     53,   6350,  -5328,   0xff, 0xff, 0xff, 0xff
vertex   -107,    -79,     85,   7084,  -5086,   0xff, 0xff, 0xff, 0xff
vertex    -82,    -23,     60,   6648,  -5852,   0xff, 0xff, 0xff, 0xff
vertex    -75,     10,     53,   6302,  -6708,   0xff, 0xff, 0xff, 0xff
vertex    -99,     12,     27,   5644,  -6093,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_41: /* 7 vertices out of 15 */
vertex    -99,     12,     27,   5644,  -6093,   0xff, 0xff, 0xff, 0xff
vertex   -101,    -29,     53,   6350,  -5328,   0xff, 0xff, 0xff, 0xff
vertex    -82,    -23,     60,   6648,  -5852,   0xff, 0xff, 0xff, 0xff
vertex   -107,    -79,     85,   7084,  -5086,   0xff, 0xff, 0xff, 0xff
vertex    -74,    -42,     77,   7165,  -6031,   0xff, 0xff, 0xff, 0xff
vertex    -75,     10,     53,   6302,  -6708,   0xff, 0xff, 0xff, 0xff
vertex    -52,      4,     80,   6938,  -7688,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_42: /* 7 vertices out of 15 */
vertex    -50,    -32,    112,   7611,  -7843,   0xff, 0xff, 0xff, 0xff
vertex    -74,    -42,     77,   7165,  -6031,   0xff, 0xff, 0xff, 0xff
vertex    -70,    -53,     98,   7529,  -6570,   0xff, 0xff, 0xff, 0xff
vertex    -52,      4,     80,   6938,  -7688,   0xff, 0xff, 0xff, 0xff
vertex   -107,    -79,     85,   7084,  -5086,   0xff, 0xff, 0xff, 0xff
vertex    -77,    -78,    106,   7698,  -6274,   0xff, 0xff, 0xff, 0xff
vertex    -42,    -59,    123,   7990,  -8107,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_43: /* 9 vertices out of 15 */
vertex    -42,    -59,    123,   7990,  -8107,   0xff, 0xff, 0xff, 0xff
vertex    -50,    -32,    112,   7611,  -7843,   0xff, 0xff, 0xff, 0xff
vertex    -70,    -53,     98,   7529,  -6570,   0xff, 0xff, 0xff, 0xff
vertex     54,     41,     89,   6607, -11988,   0xff, 0xff, 0xff, 0xff
vertex     27,     40,    104,   6829, -11070,   0xff, 0xff, 0xff, 0xff
vertex     41,     29,     94,   6854, -11671,   0xff, 0xff, 0xff, 0xff
vertex     44,     71,     89,   6361, -11411,   0xff, 0xff, 0xff, 0xff
vertex      9,      7,    107,   7316, -10515,   0xff, 0xff, 0xff, 0xff
vertex     41,      7,     95,   7152, -11911,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_44: /* 10 vertices out of 15 */
vertex     71,      5,     79,   6804, -13178,   0xff, 0xff, 0xff, 0xff
vertex     54,     41,     89,   6607, -11988,   0xff, 0xff, 0xff, 0xff
vertex     41,     29,     94,   6854, -11671,   0xff, 0xff, 0xff, 0xff
vertex     41,      7,     95,   7152, -11911,   0xff, 0xff, 0xff, 0xff
vertex     26,    -28,    114,   7792, -11351,   0xff, 0xff, 0xff, 0xff
vertex    -15,    -21,    121,   7712,  -9435,   0xff, 0xff, 0xff, 0xff
vertex      1,    -38,    126,   7960, -10155,   0xff, 0xff, 0xff, 0xff
vertex      9,      7,    107,   7316, -10515,   0xff, 0xff, 0xff, 0xff
vertex    -42,    -59,    123,   7990,  -8107,   0xff, 0xff, 0xff, 0xff
vertex     -4,    -60,    135,   8178,  -9907,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_45: /* 8 vertices out of 15 */
vertex    -15,    -21,    121,   7712,  -9435,   0xff, 0xff, 0xff, 0xff
vertex     -4,    -60,    135,   8178,  -9907,   0xff, 0xff, 0xff, 0xff
vertex      1,    -38,    126,   7960, -10155,   0xff, 0xff, 0xff, 0xff
vertex     41,    -60,    123,   8077, -12105,   0xff, 0xff, 0xff, 0xff
vertex     26,    -28,    114,   7792, -11351,   0xff, 0xff, 0xff, 0xff
vertex     41,      7,     95,   7152, -11911,   0xff, 0xff, 0xff, 0xff
vertex      9,      7,    107,   7316, -10515,   0xff, 0xff, 0xff, 0xff
vertex     43,    -16,    103,   7511, -12149,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_46: /* 7 vertices out of 15 */
vertex     41,    -60,    123,   8077, -12105,   0xff, 0xff, 0xff, 0xff
vertex     62,    -33,    104,   7550, -13024,   0xff, 0xff, 0xff, 0xff
vertex     26,    -28,    114,   7792, -11351,   0xff, 0xff, 0xff, 0xff
vertex     43,    -16,    103,   7511, -12149,   0xff, 0xff, 0xff, 0xff
vertex     41,      7,     95,   7152, -11911,   0xff, 0xff, 0xff, 0xff
vertex     71,      5,     79,   6804, -13178,   0xff, 0xff, 0xff, 0xff
vertex     87,    -38,    106,   7333, -13793,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_47: /* 7 vertices out of 15 */
vertex     71,      5,     79,   6804, -13178,   0xff, 0xff, 0xff, 0xff
vertex     87,    -38,    106,   7333, -13793,   0xff, 0xff, 0xff, 0xff
vertex    105,    -28,     87,   6866, -14405,   0xff, 0xff, 0xff, 0xff
vertex     62,    -33,    104,   7550, -13024,   0xff, 0xff, 0xff, 0xff
vertex     88,    -60,    108,   7530, -14065,   0xff, 0xff, 0xff, 0xff
vertex     41,    -60,    123,   8077, -12105,   0xff, 0xff, 0xff, 0xff
vertex    127,    -56,     79,   6715, -15343,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_48: /* 7 vertices out of 15 */
vertex    125,    -18,    -64,   3862, -14885,   0xff, 0xff, 0xff, 0xff
vertex     98,    -22,    -91,   3234, -14095,   0xff, 0xff, 0xff, 0xff
vertex    107,     -9,    -74,   3639, -14334,   0xff, 0xff, 0xff, 0xff
vertex    121,    -51,    -88,   3300, -15004,   0xff, 0xff, 0xff, 0xff
vertex     72,     13,    -90,   3358, -12902,   0xff, 0xff, 0xff, 0xff
vertex     93,      7,    -67,   3741, -13862,   0xff, 0xff, 0xff, 0xff
vertex    105,      9,    -38,   4296, -14396,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_49: /* 9 vertices out of 15 */
vertex    105,      9,    -38,   4296, -14396,   0xff, 0xff, 0xff, 0xff
vertex    125,    -18,    -64,   3862, -14885,   0xff, 0xff, 0xff, 0xff
vertex    107,     -9,    -74,   3639, -14334,   0xff, 0xff, 0xff, 0xff
vertex     48,     40,    -81,   3597, -11901,   0xff, 0xff, 0xff, 0xff
vertex     67,     45,    -65,   3926, -12512,   0xff, 0xff, 0xff, 0xff
vertex     72,     13,    -90,   3358, -12902,   0xff, 0xff, 0xff, 0xff
vertex     58,     55,    -70,   3923, -12076,   0xff, 0xff, 0xff, 0xff
vertex     32,     67,    -79,   3856, -11154,   0xff, 0xff, 0xff, 0xff
vertex     58,     73,    -72,   4052, -11849,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_50: /* 8 vertices out of 15 */
vertex     58,     73,    -72,   4052, -11849,   0xff, 0xff, 0xff, 0xff
vertex     74,     78,    -57,   4295, -12227,   0xff, 0xff, 0xff, 0xff
vertex     58,     55,    -70,   3923, -12076,   0xff, 0xff, 0xff, 0xff
vertex     67,     45,    -65,   3926, -12512,   0xff, 0xff, 0xff, 0xff
vertex     72,     13,    -90,   3358, -12902,   0xff, 0xff, 0xff, 0xff
vertex     77,     30,    -61,   3910, -13100,   0xff, 0xff, 0xff, 0xff
vertex     93,      7,    -67,   3741, -13862,   0xff, 0xff, 0xff, 0xff
vertex     82,     44,    -44,   4292, -13096,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_51: /* 8 vertices out of 15 */
vertex     67,     45,    -65,   3926, -12512,   0xff, 0xff, 0xff, 0xff
vertex     74,     78,    -57,   4295, -12227,   0xff, 0xff, 0xff, 0xff
vertex     82,     44,    -44,   4292, -13096,   0xff, 0xff, 0xff, 0xff
vertex    105,      9,    -38,   4296, -14396,   0xff, 0xff, 0xff, 0xff
vertex     93,      7,    -67,   3741, -13862,   0xff, 0xff, 0xff, 0xff
vertex     77,     30,    -61,   3910, -13100,   0xff, 0xff, 0xff, 0xff
vertex     88,     44,    -19,   4730, -13361,   0xff, 0xff, 0xff, 0xff
vertex     85,     57,    -31,   4567, -12963,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_52: /* 9 vertices out of 15 */
vertex     74,     78,    -57,   4295, -12227,   0xff, 0xff, 0xff, 0xff
vertex     85,     57,    -31,   4567, -12963,   0xff, 0xff, 0xff, 0xff
vertex     82,     44,    -44,   4292, -13096,   0xff, 0xff, 0xff, 0xff
vertex     80,     81,    -27,   4696, -12446,   0xff, 0xff, 0xff, 0xff
vertex     87,     74,     -3,   5031, -12726,   0xff, 0xff, 0xff, 0xff
vertex     88,     44,    -19,   4730, -13361,   0xff, 0xff, 0xff, 0xff
vertex    -30,     -8,   -113,   2711,  -8818,   0xff, 0xff, 0xff, 0xff
vertex    -35,    -48,   -148,   2266,  -8761,   0xff, 0xff, 0xff, 0xff
vertex    -48,    -13,   -117,   2753,  -8210,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_53: /* 7 vertices out of 15 */
vertex    -35,    -48,   -148,   2266,  -8761,   0xff, 0xff, 0xff, 0xff
vertex    -30,     -8,   -113,   2711,  -8818,   0xff, 0xff, 0xff, 0xff
vertex    -11,    -28,   -131,   2374,  -9643,   0xff, 0xff, 0xff, 0xff
vertex    -51,     12,    -89,   3244,  -8018,   0xff, 0xff, 0xff, 0xff
vertex    -48,    -13,   -117,   2753,  -8210,   0xff, 0xff, 0xff, 0xff
vertex    -21,     12,    -95,   3034,  -9175,   0xff, 0xff, 0xff, 0xff
vertex     10,      7,   -103,   2874, -10533,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_54: /* 7 vertices out of 15 */
vertex    -66,     46,    -68,   3940,  -7902,   0xff, 0xff, 0xff, 0xff
vertex    -39,     43,    -75,   3699,  -8673,   0xff, 0xff, 0xff, 0xff
vertex    -51,     12,    -89,   3244,  -8018,   0xff, 0xff, 0xff, 0xff
vertex    -51,     57,    -72,   3914,  -8501,   0xff, 0xff, 0xff, 0xff
vertex    -71,     70,    -61,   4204,  -8125,   0xff, 0xff, 0xff, 0xff
vertex    -41,     79,    -71,   4073,  -8986,   0xff, 0xff, 0xff, 0xff
vertex    -17,     82,    -82,   3944,  -9676,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_55: /* 8 vertices out of 15 */
vertex    -41,     79,    -71,   4073,  -8986,   0xff, 0xff, 0xff, 0xff
vertex    -39,     43,    -75,   3699,  -8673,   0xff, 0xff, 0xff, 0xff
vertex    -51,     57,    -72,   3914,  -8501,   0xff, 0xff, 0xff, 0xff
vertex    -51,     12,    -89,   3244,  -8018,   0xff, 0xff, 0xff, 0xff
vertex    -21,     36,    -82,   3469,  -9254,   0xff, 0xff, 0xff, 0xff
vertex    -21,     12,    -95,   3034,  -9175,   0xff, 0xff, 0xff, 0xff
vertex     -6,     47,    -80,   3594,  -9872,   0xff, 0xff, 0xff, 0xff
vertex    -17,     82,    -82,   3944,  -9676,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_56: /* 8 vertices out of 15 */
vertex     10,      7,   -103,   2874, -10533,   0xff, 0xff, 0xff, 0xff
vertex    -21,     36,    -82,   3469,  -9254,   0xff, 0xff, 0xff, 0xff
vertex     -6,     47,    -80,   3594,  -9872,   0xff, 0xff, 0xff, 0xff
vertex    -21,     12,    -95,   3034,  -9175,   0xff, 0xff, 0xff, 0xff
vertex     22,     40,    -86,   3477, -10974,   0xff, 0xff, 0xff, 0xff
vertex      7,     53,    -79,   3681, -10411,   0xff, 0xff, 0xff, 0xff
vertex      9,     74,    -80,   3886, -10425,   0xff, 0xff, 0xff, 0xff
vertex    -17,     82,    -82,   3944,  -9676,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_57: /* 9 vertices out of 15 */
vertex     -6,     47,    -80,   3594,  -9872,   0xff, 0xff, 0xff, 0xff
vertex      9,     74,    -80,   3886, -10425,   0xff, 0xff, 0xff, 0xff
vertex      7,     53,    -79,   3681, -10411,   0xff, 0xff, 0xff, 0xff
vertex     22,     40,    -86,   3477, -10974,   0xff, 0xff, 0xff, 0xff
vertex     32,     67,    -79,   3856, -11154,   0xff, 0xff, 0xff, 0xff
vertex   -117,    -21,     14,   5411,  -4994,   0xff, 0xff, 0xff, 0xff
vertex   -115,    -15,    -21,   4629,  -5200,   0xff, 0xff, 0xff, 0xff
vertex   -132,    -52,      2,   5143,  -4250,   0xff, 0xff, 0xff, 0xff
vertex   -111,     -8,     -5,   4970,  -5311,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_58: /* 8 vertices out of 15 */
vertex    -99,     12,     27,   5644,  -6093,   0xff, 0xff, 0xff, 0xff
vertex   -111,     -8,     -5,   4970,  -5311,   0xff, 0xff, 0xff, 0xff
vertex   -117,    -21,     14,   5411,  -4994,   0xff, 0xff, 0xff, 0xff
vertex   -103,     11,     -5,   4973,  -5938,   0xff, 0xff, 0xff, 0xff
vertex   -115,    -15,    -21,   4629,  -5200,   0xff, 0xff, 0xff, 0xff
vertex    -95,     12,    -37,   4327,  -6236,   0xff, 0xff, 0xff, 0xff
vertex    -88,     49,     37,   5703,  -7241,   0xff, 0xff, 0xff, 0xff
vertex   -102,     49,      7,   5200,  -6916,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_59: /* 6 vertices out of 15 */
vertex   -102,     49,      7,   5200,  -6916,   0xff, 0xff, 0xff, 0xff
vertex    -88,     49,     37,   5703,  -7241,   0xff, 0xff, 0xff, 0xff
vertex    -95,     63,     19,   5380,  -7339,   0xff, 0xff, 0xff, 0xff
vertex    -63,     80,     43,   5702,  -8340,   0xff, 0xff, 0xff, 0xff
vertex    -76,     86,     15,   5298,  -8087,   0xff, 0xff, 0xff, 0xff
vertex    -83,     86,    -14,   4889,  -7954,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_60: /* 7 vertices out of 15 */
vertex    -99,     12,     27,   5644,  -6093,   0xff, 0xff, 0xff, 0xff
vertex   -102,     49,      7,   5200,  -6916,   0xff, 0xff, 0xff, 0xff
vertex   -103,     34,     -7,   4960,  -6543,   0xff, 0xff, 0xff, 0xff
vertex   -103,     11,     -5,   4973,  -5938,   0xff, 0xff, 0xff, 0xff
vertex   -101,     48,    -23,   4714,  -6960,   0xff, 0xff, 0xff, 0xff
vertex    -83,     86,    -14,   4889,  -7954,   0xff, 0xff, 0xff, 0xff
vertex    -95,     12,    -37,   4327,  -6236,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_61: /* 8 vertices out of 15 */
vertex   -103,     34,     -7,   4960,  -6543,   0xff, 0xff, 0xff, 0xff
vertex    -95,     12,    -37,   4327,  -6236,   0xff, 0xff, 0xff, 0xff
vertex   -103,     11,     -5,   4973,  -5938,   0xff, 0xff, 0xff, 0xff
vertex   -101,     48,    -23,   4714,  -6960,   0xff, 0xff, 0xff, 0xff
vertex    -86,     44,    -49,   4258,  -7265,   0xff, 0xff, 0xff, 0xff
vertex    -91,     60,    -38,   4511,  -7411,   0xff, 0xff, 0xff, 0xff
vertex    -83,     86,    -14,   4889,  -7954,   0xff, 0xff, 0xff, 0xff
vertex    -81,     81,    -41,   4535,  -7984,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_62: /* 10 vertices out of 15 */
vertex    -86,     44,    -49,   4258,  -7265,   0xff, 0xff, 0xff, 0xff
vertex    -91,     60,    -38,   4511,  -7411,   0xff, 0xff, 0xff, 0xff
vertex    -71,     70,    -61,   4204,  -8125,   0xff, 0xff, 0xff, 0xff
vertex    -81,     81,    -41,   4535,  -7984,   0xff, 0xff, 0xff, 0xff
vertex    -50,    -32,    112,   7611,  -7843,   0xff, 0xff, 0xff, 0xff
vertex    -15,    -21,    121,   7712,  -9435,   0xff, 0xff, 0xff, 0xff
vertex    -28,    -16,    114,   7586,  -8879,   0xff, 0xff, 0xff, 0xff
vertex    -42,    -59,    123,   7990,  -8107,   0xff, 0xff, 0xff, 0xff
vertex      9,      7,    107,   7316, -10515,   0xff, 0xff, 0xff, 0xff
vertex    -22,      4,    102,   7287,  -9121,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_63: /* 9 vertices out of 15 */
vertex    -15,    -21,    121,   7712,  -9435,   0xff, 0xff, 0xff, 0xff
vertex    -22,      4,    102,   7287,  -9121,   0xff, 0xff, 0xff, 0xff
vertex    -28,    -16,    114,   7586,  -8879,   0xff, 0xff, 0xff, 0xff
vertex    -52,      4,     80,   6938,  -7688,   0xff, 0xff, 0xff, 0xff
vertex    -50,    -32,    112,   7611,  -7843,   0xff, 0xff, 0xff, 0xff
vertex     27,     40,    104,   6829, -11070,   0xff, 0xff, 0xff, 0xff
vertex      0,     49,    106,   6764, -10135,   0xff, 0xff, 0xff, 0xff
vertex      9,      7,    107,   7316, -10515,   0xff, 0xff, 0xff, 0xff
vertex     17,     56,    106,   6687, -10689,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_64: /* 8 vertices out of 15 */
vertex     44,     71,     89,   6361, -11411,   0xff, 0xff, 0xff, 0xff
vertex     17,     56,    106,   6687, -10689,   0xff, 0xff, 0xff, 0xff
vertex     27,     40,    104,   6829, -11070,   0xff, 0xff, 0xff, 0xff
vertex     20,     80,     90,   6328, -10735,   0xff, 0xff, 0xff, 0xff
vertex     -7,     83,     78,   6190,  -9953,   0xff, 0xff, 0xff, 0xff
vertex      0,     49,    106,   6764, -10135,   0xff, 0xff, 0xff, 0xff
vertex      9,      7,    107,   7316, -10515,   0xff, 0xff, 0xff, 0xff
vertex    -18,     31,    101,   6931,  -9455,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_65: /* 7 vertices out of 15 */
vertex      9,      7,    107,   7316, -10515,   0xff, 0xff, 0xff, 0xff
vertex    -18,     31,    101,   6931,  -9455,   0xff, 0xff, 0xff, 0xff
vertex    -22,      4,    102,   7287,  -9121,   0xff, 0xff, 0xff, 0xff
vertex      0,     49,    106,   6764, -10135,   0xff, 0xff, 0xff, 0xff
vertex    -33,     43,     92,   6668,  -9005,   0xff, 0xff, 0xff, 0xff
vertex     -7,     83,     78,   6190,  -9953,   0xff, 0xff, 0xff, 0xff
vertex    -52,      4,     80,   6938,  -7688,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_66: /* 7 vertices out of 15 */
vertex    -33,     43,     92,   6668,  -9005,   0xff, 0xff, 0xff, 0xff
vertex    -63,     48,     68,   6236,  -8012,   0xff, 0xff, 0xff, 0xff
vertex    -52,      4,     80,   6938,  -7688,   0xff, 0xff, 0xff, 0xff
vertex    -46,     58,     77,   6317,  -8665,   0xff, 0xff, 0xff, 0xff
vertex     -7,     83,     78,   6190,  -9953,   0xff, 0xff, 0xff, 0xff
vertex    -36,     84,     64,   5994,  -9141,   0xff, 0xff, 0xff, 0xff
vertex    -63,     80,     43,   5702,  -8340,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_67: /* 9 vertices out of 15 */
vertex    -63,     80,     43,   5702,  -8340,   0xff, 0xff, 0xff, 0xff
vertex    -63,     48,     68,   6236,  -8012,   0xff, 0xff, 0xff, 0xff
vertex    -46,     58,     77,   6317,  -8665,   0xff, 0xff, 0xff, 0xff
vertex    122,    -23,     55,   6214, -15122,   0xff, 0xff, 0xff, 0xff
vertex    105,    -28,     87,   6866, -14405,   0xff, 0xff, 0xff, 0xff
vertex    127,    -56,     79,   6715, -15343,   0xff, 0xff, 0xff, 0xff
vertex    108,    -10,     66,   6443, -14513,   0xff, 0xff, 0xff, 0xff
vertex    101,      6,     26,   5675, -14583,   0xff, 0xff, 0xff, 0xff
vertex     93,      8,     54,   6244, -14052,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_68: /* 9 vertices out of 15 */
vertex     71,      5,     79,   6804, -13178,   0xff, 0xff, 0xff, 0xff
vertex    108,    -10,     66,   6443, -14513,   0xff, 0xff, 0xff, 0xff
vertex     93,      8,     54,   6244, -14052,   0xff, 0xff, 0xff, 0xff
vertex    105,    -28,     87,   6866, -14405,   0xff, 0xff, 0xff, 0xff
vertex     86,     41,     10,   5295, -13444,   0xff, 0xff, 0xff, 0xff
vertex     82,     42,     40,   5837, -13164,   0xff, 0xff, 0xff, 0xff
vertex    101,      6,     26,   5675, -14583,   0xff, 0xff, 0xff, 0xff
vertex     81,     54,     25,   5526, -12968,   0xff, 0xff, 0xff, 0xff
vertex     87,     74,     -3,   5031, -12726,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_69: /* 8 vertices out of 15 */
vertex     81,     54,     25,   5526, -12968,   0xff, 0xff, 0xff, 0xff
vertex     87,     74,     -3,   5031, -12726,   0xff, 0xff, 0xff, 0xff
vertex     86,     78,     21,   5391, -12614,   0xff, 0xff, 0xff, 0xff
vertex     76,     84,     42,   5673, -12262,   0xff, 0xff, 0xff, 0xff
vertex     82,     42,     40,   5837, -13164,   0xff, 0xff, 0xff, 0xff
vertex    101,      6,     26,   5675, -14583,   0xff, 0xff, 0xff, 0xff
vertex     79,     33,     52,   6099, -13213,   0xff, 0xff, 0xff, 0xff
vertex     93,      8,     54,   6244, -14052,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_70: /* 7 vertices out of 15 */
vertex     70,     49,     69,   6245, -12512,   0xff, 0xff, 0xff, 0xff
vertex     79,     33,     52,   6099, -13213,   0xff, 0xff, 0xff, 0xff
vertex     82,     42,     40,   5837, -13164,   0xff, 0xff, 0xff, 0xff
vertex     76,     84,     42,   5673, -12262,   0xff, 0xff, 0xff, 0xff
vertex     71,      5,     79,   6804, -13178,   0xff, 0xff, 0xff, 0xff
vertex     93,      8,     54,   6244, -14052,   0xff, 0xff, 0xff, 0xff
vertex     54,     41,     89,   6607, -11988,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_71: /* 6 vertices out of 15 */
vertex     54,     41,     89,   6607, -11988,   0xff, 0xff, 0xff, 0xff
vertex     70,     49,     69,   6245, -12512,   0xff, 0xff, 0xff, 0xff
vertex     63,     59,     80,   6319, -12078,   0xff, 0xff, 0xff, 0xff
vertex     76,     84,     42,   5673, -12262,   0xff, 0xff, 0xff, 0xff
vertex     64,     84,     69,   6003, -11879,   0xff, 0xff, 0xff, 0xff
vertex     44,     71,     89,   6361, -11411,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_72: /* 7 vertices out of 15 */
vertex      6,   -155,      0,   3516, -19957,   0xff, 0xff, 0xff, 0xff
vertex     -3,   -160,    -47,    543,  -8842,   0xff, 0xff, 0xff, 0xff
vertex     27,   -155,    -50,   1015, -14131,   0xff, 0xff, 0xff, 0xff
vertex     41,   -146,    -30,   2178, -17265,   0xff, 0xff, 0xff, 0xff
vertex     31,   -139,    -77,   1155, -13063,   0xff, 0xff, 0xff, 0xff
vertex    -23,   -123,    -89,   1304,  -7911,   0xff, 0xff, 0xff, 0xff
vertex     81,   -127,    -55,   2764, -16729,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_73: /* 9 vertices out of 15 */
vertex     81,   -127,    -55,   2764, -16729,   0xff, 0xff, 0xff, 0xff
vertex     27,   -155,    -50,   1015, -14131,   0xff, 0xff, 0xff, 0xff
vertex     31,   -139,    -77,   1155, -13063,   0xff, 0xff, 0xff, 0xff
vertex    -23,   -123,    -89,   1304,  -7911,   0xff, 0xff, 0xff, 0xff
vertex    -11,    -87,   -132,   1736,  -9507,   0xff, 0xff, 0xff, 0xff
vertex     12,    -99,   -120,   1538, -10797,   0xff, 0xff, 0xff, 0xff
vertex    -39,    -83,   -119,   1916,  -7979,   0xff, 0xff, 0xff, 0xff
vertex    -35,    -48,   -148,   2266,  -8761,   0xff, 0xff, 0xff, 0xff
vertex      2,    -69,   -144,   1932, -10190,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_74: /* 8 vertices out of 15 */
vertex     12,    -99,   -120,   1538, -10797,   0xff, 0xff, 0xff, 0xff
vertex      2,    -69,   -144,   1932, -10190,   0xff, 0xff, 0xff, 0xff
vertex     46,    -65,   -139,   2107, -12071,   0xff, 0xff, 0xff, 0xff
vertex    -11,    -87,   -132,   1736,  -9507,   0xff, 0xff, 0xff, 0xff
vertex     31,   -139,    -77,   1155, -13063,   0xff, 0xff, 0xff, 0xff
vertex    -23,   -123,    -89,   1304,  -7911,   0xff, 0xff, 0xff, 0xff
vertex     39,   -111,   -101,   1542, -12774,   0xff, 0xff, 0xff, 0xff
vertex     67,    -93,    -98,   2121, -14083,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_75: /* 8 vertices out of 15 */
vertex     46,    -65,   -139,   2107, -12071,   0xff, 0xff, 0xff, 0xff
vertex     39,   -111,   -101,   1542, -12774,   0xff, 0xff, 0xff, 0xff
vertex     12,    -99,   -120,   1538, -10797,   0xff, 0xff, 0xff, 0xff
vertex     31,   -139,    -77,   1155, -13063,   0xff, 0xff, 0xff, 0xff
vertex     67,    -93,    -98,   2121, -14083,   0xff, 0xff, 0xff, 0xff
vertex     81,   -127,    -55,   2764, -16729,   0xff, 0xff, 0xff, 0xff
vertex     87,    -81,    -97,   2545, -14623,   0xff, 0xff, 0xff, 0xff
vertex    105,    -84,    -73,   3099, -15762,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_76: /* 9 vertices out of 15 */
vertex     46,    -65,   -139,   2107, -12071,   0xff, 0xff, 0xff, 0xff
vertex     87,    -81,    -97,   2545, -14623,   0xff, 0xff, 0xff, 0xff
vertex     67,    -93,    -98,   2121, -14083,   0xff, 0xff, 0xff, 0xff
vertex     91,    -54,   -114,   2710, -13931,   0xff, 0xff, 0xff, 0xff
vertex    121,    -51,    -88,   3300, -15004,   0xff, 0xff, 0xff, 0xff
vertex    105,    -84,    -73,   3099, -15762,   0xff, 0xff, 0xff, 0xff
vertex    -38,   -148,      2,   5336,  -1039,   0xff, 0xff, 0xff, 0xff
vertex    -34,   -153,    -29,   2300,  -3009,   0xff, 0xff, 0xff, 0xff
vertex      6,   -155,      0,   3516, -19957,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_77: /* 7 vertices out of 15 */
vertex     -3,   -160,    -47,    543,  -8842,   0xff, 0xff, 0xff, 0xff
vertex      6,   -155,      0,   3516, -19957,   0xff, 0xff, 0xff, 0xff
vertex    -34,   -153,    -29,   2300,  -3009,   0xff, 0xff, 0xff, 0xff
vertex    -82,   -122,     14,   5764,  -2366,   0xff, 0xff, 0xff, 0xff
vertex    -49,   -134,    -33,   2796,  -2922,   0xff, 0xff, 0xff, 0xff
vertex    -38,   -148,      2,   5336,  -1039,   0xff, 0xff, 0xff, 0xff
vertex    -23,   -123,    -89,   1304,  -7911,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_78: /* 7 vertices out of 15 */
vertex   -118,    -86,     13,   5455,  -3467,   0xff, 0xff, 0xff, 0xff
vertex   -101,    -89,    -24,   4291,  -3337,   0xff, 0xff, 0xff, 0xff
vertex    -82,   -122,     14,   5764,  -2366,   0xff, 0xff, 0xff, 0xff
vertex   -119,    -71,    -18,   4605,  -3816,   0xff, 0xff, 0xff, 0xff
vertex   -132,    -52,      2,   5143,  -4250,   0xff, 0xff, 0xff, 0xff
vertex   -121,    -44,    -36,   4275,  -4652,   0xff, 0xff, 0xff, 0xff
vertex   -103,    -44,    -76,   3380,  -5517,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_79: /* 8 vertices out of 15 */
vertex   -121,    -44,    -36,   4275,  -4652,   0xff, 0xff, 0xff, 0xff
vertex   -101,    -89,    -24,   4291,  -3337,   0xff, 0xff, 0xff, 0xff
vertex   -119,    -71,    -18,   4605,  -3816,   0xff, 0xff, 0xff, 0xff
vertex    -49,   -134,    -33,   2796,  -2922,   0xff, 0xff, 0xff, 0xff
vertex    -78,   -106,    -44,   3282,  -3528,   0xff, 0xff, 0xff, 0xff
vertex    -82,   -122,     14,   5764,  -2366,   0xff, 0xff, 0xff, 0xff
vertex    -68,    -88,    -77,   2489,  -5423,   0xff, 0xff, 0xff, 0xff
vertex   -103,    -44,    -76,   3380,  -5517,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_80: /* 7 vertices out of 15 */
vertex    -68,    -88,    -77,   2489,  -5423,   0xff, 0xff, 0xff, 0xff
vertex    -49,   -134,    -33,   2796,  -2922,   0xff, 0xff, 0xff, 0xff
vertex    -78,   -106,    -44,   3282,  -3528,   0xff, 0xff, 0xff, 0xff
vertex    -23,   -123,    -89,   1304,  -7911,   0xff, 0xff, 0xff, 0xff
vertex    -65,    -70,   -109,   2359,  -6815,   0xff, 0xff, 0xff, 0xff
vertex    -39,    -83,   -119,   1916,  -7979,   0xff, 0xff, 0xff, 0xff
vertex   -103,    -44,    -76,   3380,  -5517,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_81: /* 9 vertices out of 15 */
vertex    -65,    -70,   -109,   2359,  -6815,   0xff, 0xff, 0xff, 0xff
vertex   -103,    -44,    -76,   3380,  -5517,   0xff, 0xff, 0xff, 0xff
vertex    -72,    -43,   -124,   2631,  -7236,   0xff, 0xff, 0xff, 0xff
vertex    -35,    -48,   -148,   2266,  -8761,   0xff, 0xff, 0xff, 0xff
vertex    -39,    -83,   -119,   1916,  -7979,   0xff, 0xff, 0xff, 0xff
vertex    -38,   -148,      2,  -4903,  -1039,   0xff, 0xff, 0xff, 0xff
vertex    -12,   -140,     36,   -958,  -6392,   0xff, 0xff, 0xff, 0xff
vertex    -33,   -140,     30,  -2277,  -3274,   0xff, 0xff, 0xff, 0xff
vertex      6,   -155,      0,  -6723, -19957,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_82: /* 8 vertices out of 15 */
vertex    -38,   -125,     81,   8632,  -6586,   0xff, 0xff, 0xff, 0xff
vertex    -33,   -140,     30,   7962,  -3274,   0xff, 0xff, 0xff, 0xff
vertex    -12,   -140,     36,   9281,  -6392,   0xff, 0xff, 0xff, 0xff
vertex    -64,   -125,     56,   7651,  -4067,   0xff, 0xff, 0xff, 0xff
vertex    -82,   -122,     14,   5764,  -2366,   0xff, 0xff, 0xff, 0xff
vertex    -38,   -148,      2,   5336,  -1039,   0xff, 0xff, 0xff, 0xff
vertex    -76,    -95,    111,   7870,  -6263,   0xff, 0xff, 0xff, 0xff
vertex    -91,   -105,     96,   7603,  -5339,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_83: /* 7 vertices out of 15 */
vertex    -76,    -95,    111,   7870,  -6263,   0xff, 0xff, 0xff, 0xff
vertex    -38,   -125,     81,   8632,  -6586,   0xff, 0xff, 0xff, 0xff
vertex    -48,    -93,    120,   8241,  -7529,   0xff, 0xff, 0xff, 0xff
vertex    -77,    -78,    106,   7698,  -6274,   0xff, 0xff, 0xff, 0xff
vertex    -42,    -59,    123,   7990,  -8107,   0xff, 0xff, 0xff, 0xff
vertex    -91,   -105,     96,   7603,  -5339,   0xff, 0xff, 0xff, 0xff
vertex   -107,    -79,     85,   7084,  -5086,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_84: /* 7 vertices out of 15 */
vertex    -64,   -125,     56,   7651,  -4067,   0xff, 0xff, 0xff, 0xff
vertex    -38,   -125,     81,   8632,  -6586,   0xff, 0xff, 0xff, 0xff
vertex    -85,   -106,     75,   7442,  -4697,   0xff, 0xff, 0xff, 0xff
vertex    -91,   -105,     96,   7603,  -5339,   0xff, 0xff, 0xff, 0xff
vertex   -107,    -79,     85,   7084,  -5086,   0xff, 0xff, 0xff, 0xff
vertex   -105,    -94,     65,   6878,  -4309,   0xff, 0xff, 0xff, 0xff
vertex    -82,   -122,     14,   5764,  -2366,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_85: /* 8 vertices out of 15 */
vertex   -105,    -94,     65,   6878,  -4309,   0xff, 0xff, 0xff, 0xff
vertex    -64,   -125,     56,   7651,  -4067,   0xff, 0xff, 0xff, 0xff
vertex    -85,   -106,     75,   7442,  -4697,   0xff, 0xff, 0xff, 0xff
vertex    -82,   -122,     14,   5764,  -2366,   0xff, 0xff, 0xff, 0xff
vertex   -122,    -84,     41,   6130,  -3895,   0xff, 0xff, 0xff, 0xff
vertex   -118,    -86,     13,   5455,  -3467,   0xff, 0xff, 0xff, 0xff
vertex   -107,    -79,     85,   7084,  -5086,   0xff, 0xff, 0xff, 0xff
vertex   -119,    -63,     43,   6136,  -4343,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_86: /* 9 vertices out of 15 */
vertex   -119,    -63,     43,   6136,  -4343,   0xff, 0xff, 0xff, 0xff
vertex   -118,    -86,     13,   5455,  -3467,   0xff, 0xff, 0xff, 0xff
vertex   -122,    -84,     41,   6130,  -3895,   0xff, 0xff, 0xff, 0xff
vertex   -132,    -52,      2,   5143,  -4250,   0xff, 0xff, 0xff, 0xff
vertex    -12,   -140,     36,   9281,  -6392,   0xff, 0xff, 0xff, 0xff
vertex      6,   -155,      0,  13756, -19957,   0xff, 0xff, 0xff, 0xff
vertex     12,   -136,     46,   9540, -11857,   0xff, 0xff, 0xff, 0xff
vertex     45,   -139,     20,   7118, -18388,   0xff, 0xff, 0xff, 0xff
vertex     65,   -124,     49,   7647, -16677,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_87: /* 8 vertices out of 15 */
vertex     12,   -136,     46,   9540, -11857,   0xff, 0xff, 0xff, 0xff
vertex     65,   -124,     49,   7647, -16677,   0xff, 0xff, 0xff, 0xff
vertex     13,   -127,     67,   9279, -11520,   0xff, 0xff, 0xff, 0xff
vertex    -12,   -140,     36,   9281,  -6392,   0xff, 0xff, 0xff, 0xff
vertex    -38,   -125,     81,   8632,  -6586,   0xff, 0xff, 0xff, 0xff
vertex     42,   -101,     98,   8520, -12942,   0xff, 0xff, 0xff, 0xff
vertex     77,    -85,     99,   7836, -14330,   0xff, 0xff, 0xff, 0xff
vertex     99,    -88,     75,   7220, -15702,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_88: /* 8 vertices out of 15 */
vertex    127,    -56,     79,   6715, -15343,   0xff, 0xff, 0xff, 0xff
vertex     88,    -60,    108,   7530, -14065,   0xff, 0xff, 0xff, 0xff
vertex     99,    -88,     75,   7220, -15702,   0xff, 0xff, 0xff, 0xff
vertex     77,    -85,     99,   7836, -14330,   0xff, 0xff, 0xff, 0xff
vertex     41,    -60,    123,   8077, -12105,   0xff, 0xff, 0xff, 0xff
vertex     42,   -101,     98,   8520, -12942,   0xff, 0xff, 0xff, 0xff
vertex     13,   -127,     67,   9279, -11520,   0xff, 0xff, 0xff, 0xff
vertex     12,   -111,     92,   8947, -11016,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_89: /* 7 vertices out of 15 */
vertex     42,   -101,     98,   8520, -12942,   0xff, 0xff, 0xff, 0xff
vertex     13,   -127,     67,   9279, -11520,   0xff, 0xff, 0xff, 0xff
vertex     65,   -124,     49,   7647, -16677,   0xff, 0xff, 0xff, 0xff
vertex     41,    -60,    123,   8077, -12105,   0xff, 0xff, 0xff, 0xff
vertex     -1,    -98,    109,   8709,  -9891,   0xff, 0xff, 0xff, 0xff
vertex     12,   -111,     92,   8947, -11016,   0xff, 0xff, 0xff, 0xff
vertex    -38,   -125,     81,   8632,  -6586,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_90: /* 7 vertices out of 15 */
vertex    -48,    -93,    120,   8241,  -7529,   0xff, 0xff, 0xff, 0xff
vertex    -38,   -125,     81,   8632,  -6586,   0xff, 0xff, 0xff, 0xff
vertex    -19,    -82,    124,   8393,  -9058,   0xff, 0xff, 0xff, 0xff
vertex     -1,    -98,    109,   8709,  -9891,   0xff, 0xff, 0xff, 0xff
vertex     41,    -60,    123,   8077, -12105,   0xff, 0xff, 0xff, 0xff
vertex     -4,    -60,    135,   8178,  -9907,   0xff, 0xff, 0xff, 0xff
vertex    -42,    -59,    123,   7990,  -8107,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_91: /* 9 vertices out of 15 */
vertex    -42,    -59,    123,   7990,  -8107,   0xff, 0xff, 0xff, 0xff
vertex    -48,    -93,    120,   8241,  -7529,   0xff, 0xff, 0xff, 0xff
vertex    -19,    -82,    124,   8393,  -9058,   0xff, 0xff, 0xff, 0xff
vertex     56,   -138,     -8,   4387, -19081,   0xff, 0xff, 0xff, 0xff
vertex      6,   -155,      0,   3516, -19957,   0xff, 0xff, 0xff, 0xff
vertex     41,   -146,    -30,   2178, -17265,   0xff, 0xff, 0xff, 0xff
vertex     45,   -139,     20,   7118, -18388,   0xff, 0xff, 0xff, 0xff
vertex     81,   -127,    -55,   2764, -16729,   0xff, 0xff, 0xff, 0xff
vertex     83,   -125,      0,   5083, -18485,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_92: /* 10 vertices out of 15 */
vertex     83,   -125,      0,   5083, -18485,   0xff, 0xff, 0xff, 0xff
vertex     45,   -139,     20,   7118, -18388,   0xff, 0xff, 0xff, 0xff
vertex     56,   -138,     -8,   4387, -19081,   0xff, 0xff, 0xff, 0xff
vertex     65,   -124,     49,   7647, -16677,   0xff, 0xff, 0xff, 0xff
vertex    126,    -80,    -45,   3923, -16509,   0xff, 0xff, 0xff, 0xff
vertex     81,   -127,    -55,   2764, -16729,   0xff, 0xff, 0xff, 0xff
vertex    105,    -84,    -73,   3099, -15762,   0xff, 0xff, 0xff, 0xff
vertex    121,    -98,    -25,   4342, -17222,   0xff, 0xff, 0xff, 0xff
vertex    146,    -58,    -48,   4112, -16006,   0xff, 0xff, 0xff, 0xff
vertex    121,    -51,    -88,   3300, -15004,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_93: /* 8 vertices out of 15 */
vertex    105,    -84,    -73,   3099, -15762,   0xff, 0xff, 0xff, 0xff
vertex    146,    -58,    -48,   4112, -16006,   0xff, 0xff, 0xff, 0xff
vertex    126,    -80,    -45,   3923, -16509,   0xff, 0xff, 0xff, 0xff
vertex    146,    -66,      1,   5123, -16543,   0xff, 0xff, 0xff, 0xff
vertex    121,    -98,    -25,   4342, -17222,   0xff, 0xff, 0xff, 0xff
vertex     83,   -125,      0,   5083, -18485,   0xff, 0xff, 0xff, 0xff
vertex    109,   -108,     -2,   5011, -17774,   0xff, 0xff, 0xff, 0xff
vertex     81,   -127,    -55,   2764, -16729,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_94: /* 8 vertices out of 15 */
vertex    109,   -108,     -2,   5011, -17774,   0xff, 0xff, 0xff, 0xff
vertex    146,    -66,      1,   5123, -16543,   0xff, 0xff, 0xff, 0xff
vertex    116,    -98,     27,   5933, -17232,   0xff, 0xff, 0xff, 0xff
vertex    121,    -98,    -25,   4342, -17222,   0xff, 0xff, 0xff, 0xff
vertex     83,   -125,      0,   5083, -18485,   0xff, 0xff, 0xff, 0xff
vertex     65,   -124,     49,   7647, -16677,   0xff, 0xff, 0xff, 0xff
vertex     99,    -88,     75,   7220, -15702,   0xff, 0xff, 0xff, 0xff
vertex    123,    -82,     54,   6459, -16356,   0xff, 0xff, 0xff, 0xff

smoughMass_vertex_95: /* 7 vertices out of 15 */
vertex    116,    -98,     27,   5933, -17232,   0xff, 0xff, 0xff, 0xff
vertex     99,    -88,     75,   7220, -15702,   0xff, 0xff, 0xff, 0xff
vertex     65,   -124,     49,   7647, -16677,   0xff, 0xff, 0xff, 0xff
vertex    146,    -66,      1,   5123, -16543,   0xff, 0xff, 0xff, 0xff
vertex    146,    -57,     44,   5992, -16042,   0xff, 0xff, 0xff, 0xff
vertex    123,    -82,     54,   6459, -16356,   0xff, 0xff, 0xff, 0xff
vertex    127,    -56,     79,   6715, -15343,   0xff, 0xff, 0xff, 0xff

/* Render order: 1 */

glabel smoughMass_dl_opaque
gsSPClearGeometryMode G_LIGHTING
/* 08 - Default */
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
glabel smoughMass_texLoad
gsDPLoadTextureBlock smoughMass_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 64, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 6, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSPVertex smoughMass_vertex_0, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 2, 4, 5, 0x00
gsSP1Triangle 4, 2, 1, 0x00
gsSP1Triangle 6, 0, 2, 0x00
gsSPVertex smoughMass_vertex_1, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 4, 8, 7, 0x00
gsSPVertex smoughMass_vertex_2, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 1, 0x00
gsSP1Triangle 5, 4, 6, 0x00
gsSP1Triangle 3, 7, 1, 0x00
gsSPVertex smoughMass_vertex_3, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 3, 4, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 5, 2, 6, 0x00
gsSP1Triangle 2, 5, 3, 0x00
gsSPVertex smoughMass_vertex_4, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 3, 4, 1, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex smoughMass_vertex_5, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 4, 2, 0x00
gsSP1Triangle 2, 6, 0, 0x00
gsSP1Triangle 4, 6, 2, 0x00
gsSPVertex smoughMass_vertex_6, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 2, 1, 0x00
gsSP1Triangle 2, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSPVertex smoughMass_vertex_7, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 1, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 6, 4, 1, 0x00
gsSPVertex smoughMass_vertex_8, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 0, 0x00
gsSP1Triangle 6, 4, 0, 0x00
gsSPVertex smoughMass_vertex_9, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 7, 8, 5, 0x00
gsSPVertex smoughMass_vertex_10, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 2, 4, 0, 0x00
gsSP1Triangle 4, 5, 0, 0x00
gsSP1Triangle 3, 6, 7, 0x00
gsSPVertex smoughMass_vertex_11, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 1, 0x00
gsSP1Triangle 6, 2, 1, 0x00
gsSP1Triangle 6, 1, 5, 0x00
gsSPVertex smoughMass_vertex_12, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 1, 0, 0x00
gsSP1Triangle 4, 5, 2, 0x00
gsSP1Triangle 2, 5, 0, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSPVertex smoughMass_vertex_13, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 0, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 6, 4, 0, 0x00
gsSPVertex smoughMass_vertex_14, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 8, 4, 6, 0x00
gsSPVertex smoughMass_vertex_15, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 1, 0x00
gsSP1Triangle 1, 7, 5, 0x00
gsSPVertex smoughMass_vertex_16, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 1, 3, 0x00
gsSP1Triangle 1, 4, 5, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSPVertex smoughMass_vertex_17, 6, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 1, 0x00
gsSP1Triangle 1, 4, 2, 0x00
gsSP1Triangle 4, 5, 2, 0x00
gsSP1Triangle 5, 0, 2, 0x00
gsSPVertex smoughMass_vertex_18, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 2, 1, 0x00
gsSP1Triangle 2, 4, 5, 0x00
gsSP1Triangle 2, 6, 0, 0x00
gsSPVertex smoughMass_vertex_19, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 5, 4, 0x00
gsSP1Triangle 7, 4, 3, 0x00
gsSP1Triangle 4, 7, 8, 0x00
gsSPVertex smoughMass_vertex_20, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 5, 8, 9, 0x00
gsSPVertex smoughMass_vertex_21, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 3, 2, 1, 0x00
gsSP1Triangle 5, 4, 6, 0x00
gsSP1Triangle 4, 5, 7, 0x00
gsSPVertex smoughMass_vertex_22, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 1, 3, 0x00
gsSP1Triangle 4, 5, 3, 0x00
gsSP1Triangle 4, 3, 1, 0x00
gsSP1Triangle 6, 1, 7, 0x00
gsSPVertex smoughMass_vertex_23, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 0, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 4, 6, 1, 0x00
gsSP1Triangle 6, 4, 5, 0x00
gsSPVertex smoughMass_vertex_24, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 2, 4, 5, 0x00
gsSP1Triangle 4, 2, 1, 0x00
gsSP1Triangle 6, 0, 2, 0x00
gsSPVertex smoughMass_vertex_25, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 4, 6, 0x00
gsSP1Triangle 6, 8, 7, 0x00
gsSPVertex smoughMass_vertex_26, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 3, 6, 0x00
gsSP1Triangle 0, 7, 3, 0x00
gsSPVertex smoughMass_vertex_27, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 3, 1, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSPVertex smoughMass_vertex_28, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 4, 5, 0, 0x00
gsSP1Triangle 4, 0, 2, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex smoughMass_vertex_29, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 0, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 6, 1, 4, 0x00
gsSP1Triangle 6, 4, 5, 0x00
gsSPVertex smoughMass_vertex_30, 6, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 1, 3, 0x00
gsSP1Triangle 3, 5, 4, 0x00
gsSP1Triangle 4, 2, 1, 0x00
gsSPVertex smoughMass_vertex_31, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 4, 0x00
gsSP1Triangle 0, 3, 5, 0x00
gsSP1Triangle 2, 6, 0, 0x00
gsSP1Triangle 0, 6, 4, 0x00
gsSPVertex smoughMass_vertex_32, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 1, 0, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 3, 4, 1, 0x00
gsSP1Triangle 6, 5, 3, 0x00
gsSPVertex smoughMass_vertex_33, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 3, 4, 0, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 6, 5, 8, 0x00
gsSPVertex smoughMass_vertex_34, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 1, 0x00
gsSP1Triangle 4, 1, 3, 0x00
gsSP1Triangle 6, 0, 7, 0x00
gsSPVertex smoughMass_vertex_35, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 4, 0x00
gsSP1Triangle 3, 5, 4, 0x00
gsSP1Triangle 4, 2, 1, 0x00
gsSP1Triangle 2, 4, 6, 0x00
gsSPVertex smoughMass_vertex_36, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 4, 2, 3, 0x00
gsSP1Triangle 2, 4, 5, 0x00
gsSP1Triangle 0, 5, 6, 0x00
gsSPVertex smoughMass_vertex_37, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 0, 0x00
gsSP1Triangle 6, 4, 0, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSPVertex smoughMass_vertex_38, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 8, 6, 5, 0x00
gsSPVertex smoughMass_vertex_39, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 0, 3, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 6, 5, 1, 0x00
gsSPVertex smoughMass_vertex_40, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 3, 4, 1, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex smoughMass_vertex_41, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 1, 0x00
gsSP1Triangle 1, 4, 2, 0x00
gsSP1Triangle 5, 2, 6, 0x00
gsSP1Triangle 4, 6, 2, 0x00
gsSPVertex smoughMass_vertex_42, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 2, 1, 0x00
gsSP1Triangle 2, 4, 5, 0x00
gsSP1Triangle 2, 5, 6, 0x00
gsSPVertex smoughMass_vertex_43, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 5, 4, 0x00
gsSP1Triangle 5, 7, 8, 0x00
gsSPVertex smoughMass_vertex_44, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 5, 8, 9, 0x00
gsSPVertex smoughMass_vertex_45, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 2, 1, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 6, 4, 7, 0x00
gsSPVertex smoughMass_vertex_46, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 1, 3, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 1, 5, 3, 0x00
gsSP1Triangle 5, 1, 6, 0x00
gsSPVertex smoughMass_vertex_47, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 4, 0x00
gsSP1Triangle 3, 5, 4, 0x00
gsSP1Triangle 4, 2, 1, 0x00
gsSP1Triangle 2, 4, 6, 0x00
gsSPVertex smoughMass_vertex_48, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 2, 1, 0x00
gsSP1Triangle 2, 4, 5, 0x00
gsSP1Triangle 5, 6, 2, 0x00
gsSPVertex smoughMass_vertex_49, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 6, 3, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex smoughMass_vertex_50, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 3, 7, 0x00
gsSPVertex smoughMass_vertex_51, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 2, 0x00
gsSP1Triangle 2, 6, 3, 0x00
gsSP1Triangle 6, 2, 7, 0x00
gsSPVertex smoughMass_vertex_52, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 1, 0x00
gsSP1Triangle 4, 1, 3, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex smoughMass_vertex_53, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 1, 4, 0x00
gsSP1Triangle 1, 3, 5, 0x00
gsSP1Triangle 1, 6, 2, 0x00
gsSP1Triangle 6, 1, 5, 0x00
gsSPVertex smoughMass_vertex_54, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 3, 0, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 1, 5, 6, 0x00
gsSPVertex smoughMass_vertex_55, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 1, 0x00
gsSP1Triangle 6, 4, 1, 0x00
gsSP1Triangle 1, 7, 6, 0x00
gsSPVertex smoughMass_vertex_56, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 2, 4, 0, 0x00
gsSP1Triangle 4, 2, 5, 0x00
gsSP1Triangle 6, 2, 7, 0x00
gsSPVertex smoughMass_vertex_57, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 1, 4, 2, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 6, 5, 8, 0x00
gsSPVertex smoughMass_vertex_58, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 3, 4, 1, 0x00
gsSP1Triangle 6, 7, 0, 0x00
gsSPVertex smoughMass_vertex_59, 6, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 2, 1, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 2, 5, 0, 0x00
gsSP1Triangle 5, 2, 4, 0x00
gsSPVertex smoughMass_vertex_60, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 2, 1, 4, 0x00
gsSP1Triangle 1, 5, 4, 0x00
gsSP1Triangle 6, 2, 4, 0x00
gsSPVertex smoughMass_vertex_61, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 1, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 6, 5, 3, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSPVertex smoughMass_vertex_62, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 1, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 8, 9, 5, 0x00
gsSPVertex smoughMass_vertex_63, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 3, 4, 2, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 6, 5, 8, 0x00
gsSPVertex smoughMass_vertex_64, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 3, 4, 1, 0x00
gsSP1Triangle 4, 5, 1, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSPVertex smoughMass_vertex_65, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 4, 0x00
gsSP1Triangle 3, 5, 4, 0x00
gsSP1Triangle 6, 1, 4, 0x00
gsSP1Triangle 1, 6, 2, 0x00
gsSPVertex smoughMass_vertex_66, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 0, 0x00
gsSP1Triangle 0, 5, 3, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSPVertex smoughMass_vertex_67, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 8, 3, 0x00
gsSP1Triangle 3, 8, 6, 0x00
gsSPVertex smoughMass_vertex_68, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 8, 7, 4, 0x00
gsSPVertex smoughMass_vertex_69, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 3, 4, 0, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 6, 5, 4, 0x00
gsSPVertex smoughMass_vertex_70, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 1, 0, 0x00
gsSP1Triangle 1, 4, 5, 0x00
gsSP1Triangle 0, 6, 4, 0x00
gsSPVertex smoughMass_vertex_71, 6, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 1, 0x00
gsSP1Triangle 1, 4, 2, 0x00
gsSP1Triangle 4, 5, 2, 0x00
gsSP1Triangle 5, 0, 2, 0x00
gsSPVertex smoughMass_vertex_72, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 2, 1, 4, 0x00
gsSP1Triangle 1, 5, 4, 0x00
gsSP1Triangle 6, 3, 2, 0x00
gsSPVertex smoughMass_vertex_73, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 4, 6, 0x00
gsSP1Triangle 4, 7, 8, 0x00
gsSPVertex smoughMass_vertex_74, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 0, 4, 5, 0x00
gsSP1Triangle 4, 0, 6, 0x00
gsSP1Triangle 6, 2, 7, 0x00
gsSPVertex smoughMass_vertex_75, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 1, 0x00
gsSP1Triangle 6, 7, 5, 0x00
gsSP1Triangle 5, 4, 6, 0x00
gsSPVertex smoughMass_vertex_76, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 1, 3, 4, 0x00
gsSP1Triangle 4, 5, 1, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex smoughMass_vertex_77, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 4, 2, 0x00
gsSP1Triangle 2, 6, 0, 0x00
gsSP1Triangle 4, 6, 2, 0x00
gsSPVertex smoughMass_vertex_78, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 0, 0x00
gsSP1Triangle 1, 5, 6, 0x00
gsSPVertex smoughMass_vertex_79, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 1, 4, 0x00
gsSP1Triangle 1, 3, 5, 0x00
gsSP1Triangle 6, 4, 1, 0x00
gsSP1Triangle 1, 7, 6, 0x00
gsSPVertex smoughMass_vertex_80, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 3, 0, 4, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 4, 0, 0x00
gsSPVertex smoughMass_vertex_81, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 3, 4, 0, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 6, 5, 8, 0x00
gsSPVertex smoughMass_vertex_82, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 1, 3, 0x00
gsSP1Triangle 1, 4, 5, 0x00
gsSP1Triangle 0, 6, 7, 0x00
gsSPVertex smoughMass_vertex_83, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 5, 3, 6, 0x00
gsSP1Triangle 3, 5, 0, 0x00
gsSPVertex smoughMass_vertex_84, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 4, 2, 3, 0x00
gsSP1Triangle 2, 4, 5, 0x00
gsSP1Triangle 0, 5, 6, 0x00
gsSPVertex smoughMass_vertex_85, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 4, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 7, 0, 0x00
gsSP1Triangle 0, 7, 4, 0x00
gsSPVertex smoughMass_vertex_86, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 7, 6, 0x00
gsSP1Triangle 8, 6, 7, 0x00
gsSPVertex smoughMass_vertex_87, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 5, 1, 6, 0x00
gsSP1Triangle 1, 7, 6, 0x00
gsSPVertex smoughMass_vertex_88, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 1, 3, 0x00
gsSP1Triangle 1, 4, 3, 0x00
gsSP1Triangle 4, 5, 3, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSPVertex smoughMass_vertex_89, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 3, 4, 0x00
gsSP1Triangle 0, 4, 5, 0x00
gsSP1Triangle 6, 5, 4, 0x00
gsSP1Triangle 5, 6, 1, 0x00
gsSPVertex smoughMass_vertex_90, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 4, 5, 3, 0x00
gsSP1Triangle 3, 5, 2, 0x00
gsSP1Triangle 5, 6, 2, 0x00
gsSPVertex smoughMass_vertex_91, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 3, 5, 0x00
gsSP1Triangle 3, 7, 8, 0x00
gsSPVertex smoughMass_vertex_92, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 8, 6, 9, 0x00
gsSPVertex smoughMass_vertex_93, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSP1Triangle 5, 4, 6, 0x00
gsSP1Triangle 4, 5, 7, 0x00
gsSPVertex smoughMass_vertex_94, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 2, 4, 0, 0x00
gsSP1Triangle 4, 2, 5, 0x00
gsSP1Triangle 6, 2, 7, 0x00
gsSPVertex smoughMass_vertex_95, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 0, 0x00
gsSP1Triangle 0, 4, 5, 0x00
gsSP1Triangle 4, 6, 5, 0x00
gsSP1Triangle 6, 1, 5, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPEndDisplayList
