/* Generated by modconv 2 */

bonfire_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
bonfire_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bonfire_texture_0:
.incbin "actors/bonfire/bonfireBone.rgba16"

bonfire_texture_1:
.incbin "actors/bonfire/copper.rgba16"

bonfire_texture_2:
.incbin "actors/bonfire/bonfireAsh.rgba16"

bonfire_vertex_0: /* 11 vertices out of 15 */
vertex   -236,   -172,   -150,   4659,      0,   0xac, 0x15, 0x5b, 0xff
vertex   -220,   -213,   -126,   5580,      0,   0xac, 0x15, 0x5b, 0xff
vertex     19,    -10,     48,   5580,  -7613,   0xac, 0x15, 0x5b, 0xff
vertex      3,     30,     23,   4659,  -7613,   0xac, 0x15, 0x5b, 0xff
vertex   -220,   -213,   -126,   4587,      0,   0x4e, 0x9d, 0x07, 0xff
vertex   -199,   -200,   -170,   5652,      0,   0x4e, 0x9d, 0x07, 0xff
vertex     40,      2,      4,   5652,  -7613,   0x4e, 0x9d, 0x07, 0xff
vertex     19,    -10,     48,   4587,  -7613,   0x4e, 0x9d, 0x07, 0xff
vertex   -199,   -200,   -170,   4659,      0,   0x06, 0x4e, 0x9d, 0xff
vertex   -236,   -172,   -150,   5580,      0,   0x06, 0x4e, 0x9d, 0xff
vertex      3,     30,     23,   5580,  -7613,   0x06, 0x4e, 0x9d, 0xff

bonfire_vertex_1: /* 13 vertices out of 15 */
vertex   -199,   -200,   -170,   4659,      0,   0x06, 0x4e, 0x9d, 0xff
vertex      3,     30,     23,   5580,  -7613,   0x06, 0x4e, 0x9d, 0xff
vertex     40,      2,      4,   4659,  -7613,   0x06, 0x4e, 0x9d, 0xff
vertex     40,      2,      4,   4659,  -4587,   0x54, 0x47, 0x3d, 0xff
vertex      3,     30,     23,   5580,  -5119,   0x54, 0x47, 0x3d, 0xff
vertex     19,    -10,     48,   4659,  -5652,   0x54, 0x47, 0x3d, 0xff
vertex     -2,   -174,    122,   5068,      0,   0xd1, 0x1c, 0x72, 0xff
vertex     12,   -173,    128,   5376,      0,   0xd1, 0x1c, 0x72, 0xff
vertex     30,    100,     68,   5376,  -5961,   0xd1, 0x1c, 0x72, 0xff
vertex     14,    100,     62,   5068,  -5961,   0xd1, 0x1c, 0x72, 0xff
vertex     12,   -173,    128,   4942,      0,   0x7d, 0xf5, 0xf1, 0xff
vertex     10,   -177,    112,   5297,      0,   0x7d, 0xf5, 0xf1, 0xff
vertex     28,     97,     52,   5297,  -5961,   0x7d, 0xf5, 0xf1, 0xff

bonfire_vertex_2: /* 13 vertices out of 15 */
vertex     12,   -173,    128,   4942,      0,   0x7d, 0xf5, 0xf1, 0xff
vertex     28,     97,     52,   5297,  -5961,   0x7d, 0xf5, 0xf1, 0xff
vertex     30,    100,     68,   4942,  -5961,   0x7d, 0xf5, 0xf1, 0xff
vertex     10,   -177,    112,   4864,      0,   0xb3, 0xf0, 0x9e, 0xff
vertex     -2,   -174,    122,   5171,      0,   0xb3, 0xf0, 0x9e, 0xff
vertex     14,    100,     62,   5171,  -5961,   0xb3, 0xf0, 0x9e, 0xff
vertex     28,     97,     52,   4864,  -5961,   0xb3, 0xf0, 0x9e, 0xff
vertex     28,     97,     52,   4864,  -4942,   0x07, 0x7b, 0xe5, 0xff
vertex     14,    100,     62,   5171,  -5120,   0x07, 0x7b, 0xe5, 0xff
vertex     30,    100,     68,   4864,  -5297,   0x07, 0x7b, 0xe5, 0xff
vertex     30,   -174,    122,   5068,      0,   0xcf, 0x19, 0x72, 0xff
vertex     45,   -173,    128,   5376,      0,   0xcf, 0x19, 0x72, 0xff
vertex     46,    101,     68,   5376,  -5961,   0xcf, 0x19, 0x72, 0xff

bonfire_vertex_3: /* 11 vertices out of 15 */
vertex     30,   -174,    122,   5068,      0,   0xcf, 0x19, 0x72, 0xff
vertex     46,    101,     68,   5376,  -5961,   0xcf, 0x19, 0x72, 0xff
vertex     30,    100,     62,   5068,  -5961,   0xcf, 0x19, 0x72, 0xff
vertex     45,   -173,    128,   4942,      0,   0x7e, 0xfd, 0xf1, 0xff
vertex     43,   -177,    112,   5297,      0,   0x7e, 0xfd, 0xf1, 0xff
vertex     44,     98,     52,   5297,  -5961,   0x7e, 0xfd, 0xf1, 0xff
vertex     46,    101,     68,   4942,  -5961,   0x7e, 0xfd, 0xf1, 0xff
vertex     43,   -177,    112,   4864,      0,   0xb4, 0xeb, 0x9e, 0xff
vertex     30,   -174,    122,   5171,      0,   0xb4, 0xeb, 0x9e, 0xff
vertex     30,    100,     62,   5171,  -5961,   0xb4, 0xeb, 0x9e, 0xff
vertex     44,     98,     52,   4864,  -5961,   0xb4, 0xeb, 0x9e, 0xff

bonfire_vertex_4: /* 11 vertices out of 15 */
vertex     44,     98,     52,   4864,  -4942,   0x00, 0x7c, 0xe5, 0xff
vertex     30,    100,     62,   5171,  -5120,   0x00, 0x7c, 0xe5, 0xff
vertex     46,    101,     68,   4864,  -5297,   0x00, 0x7c, 0xe5, 0xff
vertex    233,   -129,     79,   4917,      0,   0x43, 0x2d, 0x9f, 0xff
vertex    219,   -147,     61,   5451,      0,   0x43, 0x2d, 0x9f, 0xff
vertex     61,     11,     27,   5451,  -4798,   0x43, 0x2d, 0x9f, 0xff
vertex     75,     29,     45,   4917,  -4798,   0x43, 0x2d, 0x9f, 0xff
vertex    219,   -147,     61,   4811,      0,   0xa9, 0xa6, 0xed, 0xff
vertex    212,   -147,     90,   5428,      0,   0xa9, 0xa6, 0xed, 0xff
vertex     55,     11,     55,   5428,  -4798,   0xa9, 0xa6, 0xed, 0xff
vertex     61,     11,     27,   4811,  -4798,   0xa9, 0xa6, 0xed, 0xff

bonfire_vertex_5: /* 11 vertices out of 15 */
vertex    212,   -147,     90,   4788,      0,   0x13, 0x2c, 0x75, 0xff
vertex    233,   -129,     79,   5322,      0,   0x13, 0x2c, 0x75, 0xff
vertex     75,     29,     45,   5322,  -4798,   0x13, 0x2c, 0x75, 0xff
vertex     55,     11,     55,   4788,  -4798,   0x13, 0x2c, 0x75, 0xff
vertex     55,     11,     55,   4788,  -4811,   0xa8, 0x59, 0xed, 0xff
vertex     75,     29,     45,   5322,  -5120,   0xa8, 0x59, 0xed, 0xff
vertex     61,     11,     27,   4788,  -5428,   0xa8, 0x59, 0xed, 0xff
vertex    136,   -116,    -56,   4917,      0,   0x1c, 0x36, 0x91, 0xff
vertex    109,   -120,    -65,   5451,      0,   0x1c, 0x36, 0x91, 0xff
vertex     49,     81,     17,   5451,  -4798,   0x1c, 0x36, 0x91, 0xff
vertex     76,     85,     26,   4917,  -4798,   0x1c, 0x36, 0x91, 0xff

bonfire_vertex_6: /* 11 vertices out of 15 */
vertex    109,   -120,    -65,   4811,      0,   0x8b, 0xd5, 0x15, 0xff
vertex    117,   -129,    -38,   5428,      0,   0x8b, 0xd5, 0x15, 0xff
vertex     57,     72,     44,   5428,  -4798,   0x8b, 0xd5, 0x15, 0xff
vertex     49,     81,     17,   4811,  -4798,   0x8b, 0xd5, 0x15, 0xff
vertex    117,   -129,    -38,   4788,      0,   0x58, 0xf6, 0x5a, 0xff
vertex    136,   -116,    -56,   5322,      0,   0x58, 0xf6, 0x5a, 0xff
vertex     76,     85,     26,   5322,  -4798,   0x58, 0xf6, 0x5a, 0xff
vertex     57,     72,     44,   4788,  -4798,   0x58, 0xf6, 0x5a, 0xff
vertex     57,     72,     44,   4788,  -4811,   0xdf, 0x71, 0x2e, 0xff
vertex     76,     85,     26,   5322,  -5120,   0xdf, 0x71, 0x2e, 0xff
vertex     49,     81,     17,   4788,  -5428,   0xdf, 0x71, 0x2e, 0xff

bonfire_vertex_7: /* 11 vertices out of 15 */
vertex   -125,   -117,    107,   5376,  -4942,   0x8b, 0xff, 0xd0, 0xff
vertex   -131,   -113,    122,   5376,  -5297,   0x8b, 0xff, 0xd0, 0xff
vertex   -127,   -101,    110,   5068,  -5120,   0x8b, 0xff, 0xd0, 0xff
vertex   -127,   -101,    110,   5068,      0,   0xde, 0x5b, 0x51, 0xff
vertex   -131,   -113,    122,   5376,      0,   0xde, 0x5b, 0x51, 0xff
vertex    128,   -110,    230,   5376,  -5961,   0xde, 0x5b, 0x51, 0xff
vertex    132,    -98,    219,   5068,  -5961,   0xde, 0x5b, 0x51, 0xff
vertex   -131,   -113,    122,   4942,      0,   0xf4, 0x86, 0x20, 0xff
vertex   -125,   -117,    107,   5297,      0,   0xf4, 0x86, 0x20, 0xff
vertex    134,   -115,    215,   5297,  -5961,   0xf4, 0x86, 0x20, 0xff
vertex    128,   -110,    230,   4942,  -5961,   0xf4, 0x86, 0x20, 0xff

bonfire_vertex_8: /* 13 vertices out of 15 */
vertex   -125,   -117,    107,   4864,      0,   0x2f, 0x1f, 0x8f, 0xff
vertex   -127,   -101,    110,   5171,      0,   0x2f, 0x1f, 0x8f, 0xff
vertex    132,    -98,    219,   5171,  -5961,   0x2f, 0x1f, 0x8f, 0xff
vertex    134,   -115,    215,   4864,  -5961,   0x2f, 0x1f, 0x8f, 0xff
vertex    134,   -115,    215,   4864,  -4942,   0x75, 0x01, 0x30, 0xff
vertex    132,    -98,    219,   5171,  -5120,   0x75, 0x01, 0x30, 0xff
vertex    128,   -110,    230,   4864,  -5297,   0x75, 0x01, 0x30, 0xff
vertex    -15,   -114,    -98,   5376,  -4942,   0x8b, 0x16, 0x29, 0xff
vertex     -8,   -109,    -83,   5376,  -5297,   0x8b, 0x16, 0x29, 0xff
vertex    -11,    -98,    -96,   5068,  -5120,   0x8b, 0x16, 0x29, 0xff
vertex    -11,    -98,    -96,   5068,      0,   0x2b, 0x5d, 0x49, 0xff
vertex     -8,   -109,    -83,   5376,      0,   0x2b, 0x5d, 0x49, 0xff
vertex    158,   -141,   -142,   5376,  -3815,   0x2b, 0x5d, 0x49, 0xff

bonfire_vertex_9: /* 11 vertices out of 15 */
vertex    -11,    -98,    -96,   5068,      0,   0x2b, 0x5d, 0x49, 0xff
vertex    158,   -141,   -142,   5376,  -3815,   0x2b, 0x5d, 0x49, 0xff
vertex    155,   -130,   -155,   5068,  -3815,   0x2b, 0x5d, 0x49, 0xff
vertex     -8,   -109,    -83,   4942,      0,   0xfa, 0x8a, 0x2d, 0xff
vertex    -15,   -114,    -98,   5297,      0,   0xfa, 0x8a, 0x2d, 0xff
vertex    152,   -146,   -157,   5297,  -3815,   0xfa, 0x8a, 0x2d, 0xff
vertex    158,   -141,   -142,   4942,  -3815,   0xfa, 0x8a, 0x2d, 0xff
vertex    -15,   -114,    -98,   4864,      0,   0xdb, 0x18, 0x8a, 0xff
vertex    -11,    -98,    -96,   5171,      0,   0xdb, 0x18, 0x8a, 0xff
vertex    155,   -130,   -155,   5171,  -3815,   0xdb, 0x18, 0x8a, 0xff
vertex    152,   -146,   -157,   4864,  -3815,   0xdb, 0x18, 0x8a, 0xff

bonfire_vertex_10: /* 13 vertices out of 15 */
vertex    152,   -146,   -157,   4864,  -4942,   0x75, 0xea, 0xd7, 0xff
vertex    155,   -130,   -155,   5171,  -5120,   0x75, 0xea, 0xd7, 0xff
vertex    158,   -141,   -142,   4864,  -5297,   0x75, 0xea, 0xd7, 0xff
vertex     29,    -44,     60,   1514,   -250,   0x00, 0x81, 0x00, 0xff
vertex     29,    -44,     26,   1514,  -1797,   0x00, 0x81, 0x00, 0xff
vertex     58,    -44,     43,    175,  -1023,   0x00, 0x81, 0x00, 0xff
vertex     58,    -44,     43,    175,   -717,   0x3f, 0x00, 0x93, 0xff
vertex     29,    -44,     26,   1514,   -717,   0x3f, 0x00, 0x93, 0xff
vertex     29,    201,     26,   1514, -11763,   0x3f, 0x03, 0x93, 0xff
vertex     58,    201,     43,    175, -11763,   0x3f, 0x03, 0x93, 0xff
vertex     29,    -44,     26,    250,   -717,   0x81, 0x00, 0x00, 0xff
vertex     29,    -44,     60,   1797,   -717,   0x81, 0x00, 0x00, 0xff
vertex     29,    201,     60,   1797, -11763,   0x82, 0x03, 0x00, 0xff

bonfire_vertex_11: /* 11 vertices out of 15 */
vertex     29,    -44,     26,    250,   -717,   0x81, 0x00, 0x00, 0xff
vertex     29,    201,     60,   1797, -11763,   0x82, 0x03, 0x00, 0xff
vertex     29,    201,     26,    250, -11763,   0x82, 0x03, 0x00, 0xff
vertex     29,    -44,     60,    533,   -717,   0x3f, 0x00, 0x6d, 0xff
vertex     58,    -44,     43,   1872,   -717,   0x3f, 0x00, 0x6d, 0xff
vertex     58,    201,     43,   1872, -11763,   0x3f, 0x03, 0x6d, 0xff
vertex     29,    201,     60,    533, -11763,   0x3f, 0x03, 0x6d, 0xff
vertex     77,    195,     11,   -640, -11519,   0x3f, 0x00, 0x93, 0xff
vertex     47,    195,     -5,    698, -11519,   0x3f, 0x00, 0x93, 0xff
vertex     47,    212,     -5,    698, -12294,   0x3f, 0x00, 0x93, 0xff
vertex     77,    212,     11,   -640, -12294,   0x3f, 0x00, 0x93, 0xff

bonfire_vertex_12: /* 11 vertices out of 15 */
vertex     -7,    195,     26,    250, -11519,   0x81, 0x00, 0x00, 0xff
vertex     -7,    195,     60,   1797, -11519,   0x81, 0x00, 0x00, 0xff
vertex     -7,    212,     60,   1797, -12294,   0x81, 0x00, 0x00, 0xff
vertex     -7,    212,     26,    250, -12294,   0x81, 0x00, 0x00, 0xff
vertex     47,    195,     91,   1349, -11519,   0x3f, 0x00, 0x6d, 0xff
vertex     77,    195,     74,   2688, -11519,   0x3f, 0x00, 0x6d, 0xff
vertex     77,    212,     74,   2688, -12294,   0x3f, 0x00, 0x6d, 0xff
vertex     47,    212,     91,   1349, -12294,   0x3f, 0x00, 0x6d, 0xff
vertex     58,    182,     43,    175,  -1023,   0x15, 0x89, 0xdb, 0xff
vertex     29,    182,     26,   1514,  -1797,   0x15, 0x89, 0xdb, 0xff
vertex     47,    195,     -5,    698,  -3210,   0x15, 0x89, 0xdb, 0xff

bonfire_vertex_13: /* 11 vertices out of 15 */
vertex     58,    182,     43,    175,  -1023,   0x15, 0x89, 0xdb, 0xff
vertex     47,    195,     -5,    698,  -3210,   0x15, 0x89, 0xdb, 0xff
vertex     77,    195,     11,   -640,  -2437,   0x15, 0x89, 0xdb, 0xff
vertex     29,    182,     26,    250, -10927,   0x93, 0x00, 0xc1, 0xff
vertex     29,    199,     26,    250, -11702,   0x93, 0x00, 0xc1, 0xff
vertex     47,    212,     -5,  -1162, -12294,   0x93, 0x00, 0xc1, 0xff
vertex     47,    195,     -5,  -1162, -11519,   0x93, 0x00, 0xc1, 0xff
vertex     29,    199,     26,    533,  -1797,   0xeb, 0x77, 0x25, 0xff
vertex     58,    199,     43,   1872,  -1023,   0xeb, 0x77, 0x25, 0xff
vertex     77,    212,     11,   2688,  -2437,   0xeb, 0x77, 0x25, 0xff
vertex     47,    212,     -5,   1349,  -3210,   0xeb, 0x77, 0x25, 0xff

bonfire_vertex_14: /* 11 vertices out of 15 */
vertex     58,    199,     43,   1023, -11702,   0x6d, 0x00, 0x3f, 0xff
vertex     58,    182,     43,   1023, -10927,   0x6d, 0x00, 0x3f, 0xff
vertex     77,    195,     11,   2437, -11519,   0x6d, 0x00, 0x3f, 0xff
vertex     77,    212,     11,   2437, -12294,   0x6d, 0x00, 0x3f, 0xff
vertex     29,    182,     60,   1514,   -250,   0x15, 0x89, 0x25, 0xff
vertex     58,    182,     43,    175,  -1023,   0x15, 0x89, 0x25, 0xff
vertex     77,    195,     74,   -640,    389,   0x15, 0x89, 0x25, 0xff
vertex     47,    195,     91,    698,   1162,   0x15, 0x89, 0x25, 0xff
vertex     58,    182,     43,   1023, -10927,   0x6d, 0x00, 0xc1, 0xff
vertex     58,    199,     43,   1023, -11702,   0x6d, 0x00, 0xc1, 0xff
vertex     77,    212,     74,   -389, -12294,   0x6d, 0x00, 0xc1, 0xff

bonfire_vertex_15: /* 11 vertices out of 15 */
vertex     58,    182,     43,   1023, -10927,   0x6d, 0x00, 0xc1, 0xff
vertex     77,    212,     74,   -389, -12294,   0x6d, 0x00, 0xc1, 0xff
vertex     77,    195,     74,   -389, -11519,   0x6d, 0x00, 0xc1, 0xff
vertex     58,    199,     43,   1872,  -1023,   0xeb, 0x77, 0xdb, 0xff
vertex     29,    199,     60,    533,   -250,   0xeb, 0x77, 0xdb, 0xff
vertex     47,    212,     91,   1349,   1162,   0xeb, 0x77, 0xdb, 0xff
vertex     77,    212,     74,   2688,    389,   0xeb, 0x77, 0xdb, 0xff
vertex     29,    199,     60,   1797, -11702,   0x93, 0x00, 0x3f, 0xff
vertex     29,    182,     60,   1797, -10927,   0x93, 0x00, 0x3f, 0xff
vertex     47,    195,     91,   3210, -11519,   0x93, 0x00, 0x3f, 0xff
vertex     47,    212,     91,   3210, -12294,   0x93, 0x00, 0x3f, 0xff

bonfire_vertex_16: /* 11 vertices out of 15 */
vertex     29,    182,     26,   1514,  -1797,   0xd5, 0x89, 0x00, 0xff
vertex     29,    182,     60,   1514,   -250,   0xd5, 0x89, 0x00, 0xff
vertex     -7,    195,     60,   3147,   -250,   0xd5, 0x89, 0x00, 0xff
vertex     -7,    195,     26,   3147,  -1797,   0xd5, 0x89, 0x00, 0xff
vertex     29,    182,     60,    533, -10927,   0x00, 0x00, 0x7f, 0xff
vertex     29,    199,     60,    533, -11702,   0x00, 0x00, 0x7f, 0xff
vertex     -7,    212,     60,  -1099, -12294,   0x00, 0x00, 0x7f, 0xff
vertex     -7,    195,     60,  -1099, -11519,   0x00, 0x00, 0x7f, 0xff
vertex     29,    199,     60,    533,   -250,   0x2b, 0x77, 0x00, 0xff
vertex     29,    199,     26,    533,  -1797,   0x2b, 0x77, 0x00, 0xff
vertex     -7,    212,     26,  -1099,  -1797,   0x2b, 0x77, 0x00, 0xff

bonfire_vertex_17: /* 13 vertices out of 15 */
vertex     29,    199,     60,    533,   -250,   0x2b, 0x77, 0x00, 0xff
vertex     -7,    212,     26,  -1099,  -1797,   0x2b, 0x77, 0x00, 0xff
vertex     -7,    212,     60,  -1099,   -250,   0x2b, 0x77, 0x00, 0xff
vertex     29,    199,     26,   1514, -11702,   0x00, 0x00, 0x81, 0xff
vertex     29,    182,     26,   1514, -10927,   0x00, 0x00, 0x81, 0xff
vertex     -7,    195,     26,   3147, -11519,   0x00, 0x00, 0x81, 0xff
vertex     -7,    212,     26,   3147, -12294,   0x00, 0x00, 0x81, 0xff
vertex     35,    314,     37,    820,  -1299,   0x00, 0x7f, 0x00, 0xff
vertex     35,    314,     49,    820,   -748,   0x00, 0x7f, 0x00, 0xff
vertex     46,    314,     43,   1298,  -1023,   0x00, 0x7f, 0x00, 0xff
vertex     58,    201,     43,    175, -11763,   0x3f, 0x03, 0x93, 0xff
vertex     29,    201,     26,   1514, -11763,   0x3f, 0x03, 0x93, 0xff
vertex     35,    314,     37,   1227, -16861,   0x3f, 0x07, 0x93, 0xff

bonfire_vertex_18: /* 11 vertices out of 15 */
vertex     58,    201,     43,    175, -11763,   0x3f, 0x03, 0x93, 0xff
vertex     35,    314,     37,   1227, -16861,   0x3f, 0x07, 0x93, 0xff
vertex     46,    314,     43,    749, -16861,   0x3f, 0x07, 0x93, 0xff
vertex     29,    201,     26,    250, -11763,   0x82, 0x03, 0x00, 0xff
vertex     29,    201,     60,   1797, -11763,   0x82, 0x03, 0x00, 0xff
vertex     35,    314,     49,   1299, -16861,   0x82, 0x07, 0x00, 0xff
vertex     35,    314,     37,    748, -16861,   0x82, 0x07, 0x00, 0xff
vertex     29,    201,     60,    533, -11763,   0x3f, 0x03, 0x6d, 0xff
vertex     58,    201,     43,   1872, -11763,   0x3f, 0x03, 0x6d, 0xff
vertex     46,    314,     43,   1298, -16861,   0x3f, 0x07, 0x6d, 0xff
vertex     35,    314,     49,    820, -16861,   0x3f, 0x07, 0x6d, 0xff

bonfire_vertex_19: /* 11 vertices out of 15 */
vertex     41,    314,     43,  -1515,  -7539,   0x59, 0x36, 0xb8, 0xff
vertex     38,    314,     39,  -1314,  -7539,   0x59, 0x36, 0xb8, 0xff
vertex     38,    321,     45,  -1613,  -7938,   0x59, 0x36, 0xb8, 0xff
vertex     41,    321,     48,  -1814,  -7938,   0x59, 0x36, 0xb8, 0xff
vertex     38,    314,     39,   3362,  -7539,   0x81, 0x00, 0x00, 0xff
vertex     38,    314,     46,   3763,  -7539,   0x81, 0x00, 0x00, 0xff
vertex     38,    321,     51,   4062,  -7938,   0x81, 0x00, 0x00, 0xff
vertex     38,    321,     45,   3661,  -7938,   0x81, 0x00, 0x00, 0xff
vertex     38,    314,     46,  -1715,  -7539,   0x59, 0xca, 0x48, 0xff
vertex     41,    314,     43,  -1515,  -7539,   0x59, 0xca, 0x48, 0xff
vertex     41,    321,     48,  -1814,  -7938,   0x59, 0xca, 0x48, 0xff

bonfire_vertex_20: /* 11 vertices out of 15 */
vertex     38,    314,     46,  -1715,  -7539,   0x59, 0xca, 0x48, 0xff
vertex     41,    321,     48,  -1814,  -7938,   0x59, 0xca, 0x48, 0xff
vertex     38,    321,     51,  -2014,  -7938,   0x59, 0xca, 0x48, 0xff
vertex     41,    321,     48,  -1814,  -7938,   0x59, 0xca, 0xb9, 0xff
vertex     38,    321,     45,  -1613,  -7938,   0x59, 0xca, 0xb9, 0xff
vertex     38,    323,     43,  -1515,  -8068,   0x59, 0xca, 0xb9, 0xff
vertex     41,    327,     43,  -1515,  -8336,   0x59, 0xca, 0xb9, 0xff
vertex     38,    321,     45,   3661,  -7938,   0x81, 0x00, 0x00, 0xff
vertex     38,    321,     51,   4062,  -7938,   0x81, 0x00, 0x00, 0xff
vertex     38,    327,     46,   3763,  -8336,   0x81, 0x00, 0x00, 0xff
vertex     38,    323,     43,   3563,  -8068,   0x81, 0x00, 0x00, 0xff

bonfire_vertex_21: /* 11 vertices out of 15 */
vertex     38,    321,     51,  -2014,  -7938,   0x59, 0x36, 0x48, 0xff
vertex     41,    321,     48,  -1814,  -7938,   0x59, 0x36, 0x48, 0xff
vertex     41,    327,     43,  -1515,  -8336,   0x59, 0x36, 0x48, 0xff
vertex     38,    327,     46,  -1715,  -8336,   0x59, 0x36, 0x48, 0xff
vertex     38,    327,     46,   3763,  -8336,   0xa7, 0x35, 0xb8, 0xff
vertex     41,    327,     43,   3563,  -8336,   0xa7, 0x35, 0xb8, 0xff
vertex     38,    323,     43,   3563,  -8068,   0xa7, 0x35, 0xb8, 0xff
vertex     38,    321,     41,  -1416,  -7938,   0x59, 0x36, 0x47, 0xff
vertex     38,    318,     43,  -1516,  -7808,   0x59, 0x36, 0x47, 0xff
vertex     41,    314,     43,  -1515,  -7539,   0x59, 0x36, 0x47, 0xff
vertex     41,    321,     38,  -1216,  -7938,   0x59, 0x36, 0x47, 0xff

bonfire_vertex_22: /* 11 vertices out of 15 */
vertex     38,    321,     34,   3064,  -7938,   0x81, 0x00, 0x00, 0xff
vertex     38,    314,     39,   3362,  -7539,   0x81, 0x00, 0x00, 0xff
vertex     38,    318,     43,   3564,  -7808,   0x81, 0x00, 0x00, 0xff
vertex     38,    321,     41,   3464,  -7938,   0x81, 0x00, 0x00, 0xff
vertex     41,    321,     38,  -1216,  -7938,   0x59, 0xca, 0xb8, 0xff
vertex     41,    314,     43,  -1515,  -7539,   0x59, 0xca, 0xb8, 0xff
vertex     38,    314,     39,  -1314,  -7539,   0x59, 0xca, 0xb8, 0xff
vertex     38,    321,     34,  -1016,  -7938,   0x59, 0xca, 0xb8, 0xff
vertex     38,    327,     46,  -1715,  -8336,   0x59, 0xca, 0x48, 0xff
vertex     38,    321,     41,  -1416,  -7938,   0x59, 0xca, 0x48, 0xff
vertex     41,    321,     38,  -1216,  -7938,   0x59, 0xca, 0x48, 0xff

bonfire_vertex_23: /* 11 vertices out of 15 */
vertex     38,    327,     46,  -1715,  -8336,   0x59, 0xca, 0x48, 0xff
vertex     41,    321,     38,  -1216,  -7938,   0x59, 0xca, 0x48, 0xff
vertex     41,    327,     43,  -1515,  -8336,   0x59, 0xca, 0x48, 0xff
vertex     38,    327,     39,   3362,  -8336,   0x81, 0x00, 0x00, 0xff
vertex     38,    321,     34,   3064,  -7938,   0x81, 0x00, 0x00, 0xff
vertex     38,    321,     41,   3464,  -7938,   0x81, 0x00, 0x00, 0xff
vertex     38,    327,     46,   3763,  -8336,   0x81, 0x00, 0x00, 0xff
vertex     41,    327,     43,  -1515,  -8336,   0x59, 0x36, 0xb8, 0xff
vertex     41,    321,     38,  -1216,  -7938,   0x59, 0x36, 0xb8, 0xff
vertex     38,    321,     34,  -1016,  -7938,   0x59, 0x36, 0xb8, 0xff
vertex     38,    327,     39,  -1314,  -8336,   0x59, 0x36, 0xb8, 0xff

bonfire_vertex_24: /* 8 vertices out of 15 */
vertex     38,    327,     46,   4365,   1715,   0x00, 0x7f, 0x00, 0xff
vertex     41,    327,     43,   4526,   1515,   0x00, 0x7f, 0x00, 0xff
vertex     38,    327,     39,   4365,   1314,   0x00, 0x7f, 0x00, 0xff
vertex     39,    -34,     43,   1536,  -1536,   0x00, 0x7f, 0x00, 0xff
vertex    364,   -171,     43,   3734,  -1535,   0x31, 0x75, 0x00, 0xff
vertex    139,   -171,   -266,   2215,  -3626,   0x0f, 0x75, 0xd2, 0xff
vertex   -224,   -171,   -147,   -242,  -2828,   0xd9, 0x75, 0xe4, 0xff
vertex   -224,   -171,    234,   -242,   -243,   0xd9, 0x75, 0x1c, 0xff

bonfire_vertex_25: /* 4 vertices out of 6 */
vertex     39,    -34,     43,   1536,  -1536,   0x00, 0x7f, 0x00, 0xff
vertex   -224,   -171,    234,   -242,   -243,   0xd9, 0x75, 0x1c, 0xff
vertex    139,   -171,    353,   2215,    554,   0x0f, 0x75, 0x2e, 0xff
vertex    364,   -171,     43,   3734,  -1535,   0x31, 0x75, 0x00, 0xff

/* Render order: 1 */

glabel bonfire_dl_opaque
gsSPClearGeometryMode G_LIGHTING
/* #LIGHTING 08 - Default */
gsDPPipeSync
gsSPSetGeometryMode G_LIGHTING
gsSPNumLights NUMLIGHTS_1
gsSPLight bonfire_diffuse_light, 1
gsSPLight bonfire_ambient_light, 2
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock bonfire_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSPVertex bonfire_vertex_0, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_1, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 6, 8, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_2, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_3, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_4, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_5, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_6, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_7, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_8, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_9, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_10, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
/* #LIGHTING 07 - Default */
gsDPPipeSync
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock bonfire_texture_1, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsDPTileSync
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 6, 8, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_11, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_12, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_13, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_14, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_15, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_16, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_17, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_18, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_19, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_20, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_21, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_22, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_23, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_24, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 0, 0x00
/* #LIGHTING 03 - Default */
gsDPPipeSync
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock bonfire_texture_2, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsDPTileSync
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 3, 6, 7, 0x00
gsSPVertex bonfire_vertex_25, 4, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPEndDisplayList
