/* Generated by modconv 2 */

bonfire_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
bonfire_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bonfire_texture_0:
.incbin "actors/bonfire/bonfireBone.rgba16"

bonfire_texture_1:
.incbin "actors/bonfire/copper.rgba16"

bonfire_texture_2:
.incbin "actors/bonfire/bonfireAsh.rgba16"

bonfire_vertex_0: /* 11 vertices out of 15 */
vertex    -15,     -6,     -4,   4659,  -7613,   0xee, 0x7a, 0x1b, 0xff
vertex    -75,    -57,    -48,   4659,      0,   0xb2, 0x63, 0xf9, 0xff
vertex    -11,    -16,      1,   5580,  -7613,   0x29, 0xe7, 0x75, 0xff
vertex    -71,    -67,    -42,   5580,      0,   0xfa, 0xb2, 0x63, 0xff
vertex    -11,    -16,      1,   4587,  -7613,   0x29, 0xe7, 0x75, 0xff
vertex    -65,    -64,    -53,   5652,      0,   0x54, 0xeb, 0xa5, 0xff
vertex     -5,    -13,     -9,   5652,  -7613,   0x75, 0x15, 0xd6, 0xff
vertex    -71,    -67,    -42,   4587,      0,   0xfa, 0xb2, 0x63, 0xff
vertex     -5,    -13,     -9,   4659,  -7613,   0x75, 0x15, 0xd6, 0xff
vertex    -75,    -57,    -48,   5580,      0,   0xb2, 0x63, 0xf9, 0xff
vertex    -15,     -6,     -4,   5580,  -7613,   0xee, 0x7a, 0x1b, 0xff

bonfire_vertex_1: /* 13 vertices out of 15 */
vertex    -75,    -57,    -48,   5580,      0,   0xb2, 0x63, 0xf9, 0xff
vertex     -5,    -13,     -9,   4659,  -7613,   0x75, 0x15, 0xd6, 0xff
vertex    -65,    -64,    -53,   4659,      0,   0x54, 0xeb, 0xa5, 0xff
vertex     -5,    -13,     -9,   4659,  -4587,   0x75, 0x15, 0xd6, 0xff
vertex    -15,     -6,     -4,   5580,  -5119,   0xee, 0x7a, 0x1b, 0xff
vertex    -11,    -16,      1,   4659,  -5652,   0x29, 0xe7, 0x75, 0xff
vertex    -12,     10,      4,   5068,  -5961,   0x9c, 0x4e, 0xfe, 0xff
vertex    -16,    -57,     19,   5068,      0,   0x83, 0x0b, 0x0f, 0xff
vertex     -8,     10,      6,   5376,  -5961,   0x45, 0x52, 0x43, 0xff
vertex    -12,    -57,     21,   5376,      0,   0x4d, 0x10, 0x62, 0xff
vertex     -8,     10,      6,   4942,  -5961,   0x45, 0x52, 0x43, 0xff
vertex    -13,    -58,     17,   5297,      0,   0x2f, 0xe4, 0x8e, 0xff
vertex     -8,     10,      2,   5297,  -5961,   0x2c, 0x2d, 0x92, 0xff

bonfire_vertex_2: /* 13 vertices out of 15 */
vertex    -13,    -58,     17,   5297,      0,   0x2f, 0xe4, 0x8e, 0xff
vertex     -8,     10,      6,   4942,  -5961,   0x45, 0x52, 0x43, 0xff
vertex    -12,    -57,     21,   4942,      0,   0x4d, 0x10, 0x62, 0xff
vertex     -8,     10,      2,   4864,  -5961,   0x2c, 0x2d, 0x92, 0xff
vertex    -16,    -57,     19,   5171,      0,   0x83, 0x0b, 0x0f, 0xff
vertex    -12,     10,      4,   5171,  -5961,   0x9c, 0x4e, 0xfe, 0xff
vertex    -13,    -58,     17,   4864,      0,   0x2f, 0xe4, 0x8e, 0xff
vertex     -8,     10,      2,   4864,  -4942,   0x2c, 0x2d, 0x92, 0xff
vertex    -12,     10,      4,   5171,  -5120,   0x9c, 0x4e, 0xfe, 0xff
vertex     -8,     10,      6,   4864,  -5297,   0x45, 0x52, 0x43, 0xff
vertex     -8,     10,      4,   5068,  -5961,   0x98, 0x47, 0xfe, 0xff
vertex     -8,    -58,     19,   5068,      0,   0x82, 0x03, 0x0f, 0xff
vertex     -4,     11,      6,   5376,  -5961,   0x40, 0x56, 0x43, 0xff

bonfire_vertex_3: /* 11 vertices out of 15 */
vertex     -4,     11,      6,   5376,  -5961,   0x40, 0x56, 0x43, 0xff
vertex     -8,    -58,     19,   5068,      0,   0x82, 0x03, 0x0f, 0xff
vertex     -4,    -57,     21,   5376,      0,   0x4c, 0x15, 0x62, 0xff
vertex     -4,     11,      6,   4942,  -5961,   0x40, 0x56, 0x43, 0xff
vertex     -5,    -58,     17,   5297,      0,   0x31, 0xe7, 0x8e, 0xff
vertex     -4,     10,      2,   5297,  -5961,   0x29, 0x2f, 0x92, 0xff
vertex     -4,    -57,     21,   4942,      0,   0x4c, 0x15, 0x62, 0xff
vertex     -4,     10,      2,   4864,  -5961,   0x29, 0x2f, 0x92, 0xff
vertex     -5,    -58,     17,   4864,      0,   0x31, 0xe7, 0x8e, 0xff
vertex     -8,     10,      4,   5171,  -5961,   0x98, 0x47, 0xfe, 0xff
vertex     -8,    -58,     19,   5171,      0,   0x82, 0x03, 0x0f, 0xff

bonfire_vertex_4: /* 11 vertices out of 15 */
vertex     -4,     10,      2,   4864,  -4942,   0x29, 0x2f, 0x92, 0xff
vertex     -8,     10,      4,   5171,  -5120,   0x98, 0x47, 0xfe, 0xff
vertex     -4,     11,      6,   4864,  -5297,   0x40, 0x56, 0x43, 0xff
vertex      2,     -6,      0,   4917,  -4798,   0x17, 0x7c, 0x05, 0xff
vertex     42,    -46,      9,   4917,      0,   0x57, 0x5a, 0x13, 0xff
vertex      0,    -11,     -4,   5451,  -4798,   0xbf, 0x0c, 0x94, 0xff
vertex     38,    -51,      4,   5451,      0,   0xed, 0xd4, 0x8b, 0xff
vertex      0,    -11,     -4,   4811,  -4798,   0xbf, 0x0c, 0x94, 0xff
vertex     37,    -51,     11,   5428,      0,   0xbd, 0xd3, 0x61, 0xff
vertex     -2,    -11,      3,   5428,  -4798,   0x97, 0x0b, 0x46, 0xff
vertex     38,    -51,      4,   4811,      0,   0xed, 0xd4, 0x8b, 0xff

bonfire_vertex_5: /* 11 vertices out of 15 */
vertex     -2,    -11,      3,   4788,  -4798,   0x97, 0x0b, 0x46, 0xff
vertex     37,    -51,     11,   4788,      0,   0xbd, 0xd3, 0x61, 0xff
vertex      2,     -6,      0,   5322,  -4798,   0x17, 0x7c, 0x05, 0xff
vertex     42,    -46,      9,   5322,      0,   0x57, 0x5a, 0x13, 0xff
vertex     -2,    -11,      3,   4788,  -4811,   0x97, 0x0b, 0x46, 0xff
vertex      2,     -6,      0,   5322,  -5120,   0x17, 0x7c, 0x05, 0xff
vertex      0,    -11,     -4,   4788,  -5428,   0xbf, 0x0c, 0x94, 0xff
vertex      3,      7,     -4,   4917,  -4798,   0x4e, 0x63, 0x08, 0xff
vertex     11,    -44,    -27,   5451,      0,   0xa8, 0x0a, 0xa6, 0xff
vertex     -3,      6,     -6,   5451,  -4798,   0xa4, 0x47, 0xcf, 0xff
vertex     18,    -43,    -24,   4917,      0,   0x75, 0x2b, 0xeb, 0xff

bonfire_vertex_6: /* 11 vertices out of 15 */
vertex     -3,      6,     -6,   4811,  -4798,   0xa4, 0x47, 0xcf, 0xff
vertex     11,    -44,    -27,   4811,      0,   0xa8, 0x0a, 0xa6, 0xff
vertex     -1,      3,      0,   5428,  -4798,   0xd6, 0x11, 0x76, 0xff
vertex     13,    -46,    -20,   5428,      0,   0xe4, 0xca, 0x6f, 0xff
vertex     -1,      3,      0,   4788,  -4798,   0xd6, 0x11, 0x76, 0xff
vertex     13,    -46,    -20,   4788,      0,   0xe4, 0xca, 0x6f, 0xff
vertex      3,      7,     -4,   5322,  -4798,   0x4e, 0x63, 0x08, 0xff
vertex     18,    -43,    -24,   5322,      0,   0x75, 0x2b, 0xeb, 0xff
vertex     -1,      3,      0,   4788,  -4811,   0xd6, 0x11, 0x76, 0xff
vertex      3,      7,     -4,   5322,  -5120,   0x4e, 0x63, 0x08, 0xff
vertex     -3,      6,     -6,   4788,  -5428,   0xa4, 0x47, 0xcf, 0xff

bonfire_vertex_7: /* 11 vertices out of 15 */
vertex    -47,    -43,     15,   5376,  -4942,   0xdc, 0xb4, 0xa2, 0xff
vertex    -48,    -42,     19,   5376,  -5297,   0x98, 0xe6, 0x43, 0xff
vertex    -47,    -39,     16,   5068,  -5120,   0xca, 0x64, 0xca, 0xff
vertex     17,    -39,     43,   5068,  -5961,   0x4b, 0x66, 0x00, 0xff
vertex    -48,    -42,     19,   5376,      0,   0x98, 0xe6, 0x43, 0xff
vertex     16,    -41,     46,   5376,  -5961,   0x19, 0xe7, 0x79, 0xff
vertex    -47,    -39,     16,   5068,      0,   0xca, 0x64, 0xca, 0xff
vertex     16,    -41,     46,   4942,  -5961,   0x19, 0xe7, 0x79, 0xff
vertex    -48,    -42,     19,   4942,      0,   0x98, 0xe6, 0x43, 0xff
vertex     17,    -43,     43,   5297,  -5961,   0x5d, 0xb5, 0xd8, 0xff
vertex    -47,    -43,     15,   5297,      0,   0xdc, 0xb4, 0xa2, 0xff

bonfire_vertex_8: /* 13 vertices out of 15 */
vertex     17,    -43,     43,   4864,  -5961,   0x5d, 0xb5, 0xd8, 0xff
vertex    -47,    -39,     16,   5171,      0,   0xca, 0x64, 0xca, 0xff
vertex     17,    -39,     43,   5171,  -5961,   0x4b, 0x66, 0x00, 0xff
vertex    -47,    -43,     15,   4864,      0,   0xdc, 0xb4, 0xa2, 0xff
vertex     17,    -43,     43,   4864,  -4942,   0x5d, 0xb5, 0xd8, 0xff
vertex     17,    -39,     43,   5171,  -5120,   0x4b, 0x66, 0x00, 0xff
vertex     16,    -41,     46,   4864,  -5297,   0x19, 0xe7, 0x79, 0xff
vertex    -19,    -42,    -35,   5376,  -4942,   0x9b, 0xbf, 0xda, 0xff
vertex    -18,    -41,    -31,   5376,  -5297,   0xde, 0xf8, 0x7a, 0xff
vertex    -18,    -38,    -34,   5068,  -5120,   0xc5, 0x6f, 0xf2, 0xff
vertex     22,    -46,    -49,   5068,  -3815,   0x46, 0x56, 0xc4, 0xff
vertex    -18,    -38,    -34,   5068,      0,   0xc5, 0x6f, 0xf2, 0xff
vertex     23,    -49,    -46,   5376,  -3815,   0x60, 0xdf, 0x4b, 0xff

bonfire_vertex_9: /* 11 vertices out of 15 */
vertex     23,    -49,    -46,   5376,  -3815,   0x60, 0xdf, 0x4b, 0xff
vertex    -18,    -38,    -34,   5068,      0,   0xc5, 0x6f, 0xf2, 0xff
vertex    -18,    -41,    -31,   5376,      0,   0xde, 0xf8, 0x7a, 0xff
vertex     23,    -49,    -46,   4942,  -3815,   0x60, 0xdf, 0x4b, 0xff
vertex    -18,    -41,    -31,   4942,      0,   0xde, 0xf8, 0x7a, 0xff
vertex     22,    -50,    -50,   5297,  -3815,   0x1c, 0xa6, 0xac, 0xff
vertex    -19,    -42,    -35,   5297,      0,   0x9b, 0xbf, 0xda, 0xff
vertex     22,    -50,    -50,   4864,  -3815,   0x1c, 0xa6, 0xac, 0xff
vertex    -18,    -38,    -34,   5171,      0,   0xc5, 0x6f, 0xf2, 0xff
vertex     22,    -46,    -49,   5171,  -3815,   0x46, 0x56, 0xc4, 0xff
vertex    -19,    -42,    -35,   4864,      0,   0x9b, 0xbf, 0xda, 0xff

bonfire_vertex_10: /* 13 vertices out of 15 */
vertex     22,    -50,    -50,   4864,  -4942,   0x1c, 0xa6, 0xac, 0xff
vertex     22,    -46,    -49,   5171,  -5120,   0x46, 0x56, 0xc4, 0xff
vertex     23,    -49,    -46,   4864,  -5297,   0x60, 0xdf, 0x4b, 0xff
vertex     -8,    -25,      4,   1514,   -250,   0xcc, 0xba, 0x5b, 0xff
vertex     -8,    -25,     -4,   1514,  -1797,   0xcc, 0xba, 0xa5, 0xff
vertex     -1,    -25,      0,    175,  -1023,   0x69, 0xba, 0x00, 0xff
vertex     -1,     35,      0,    175, -11763,   0x7e, 0x06, 0x00, 0xff
vertex     -1,    -25,      0,    175,   -717,   0x69, 0xba, 0x00, 0xff
vertex     -8,     35,     -4,   1514, -11763,   0xc1, 0x06, 0x93, 0xff
vertex     -8,    -25,     -4,   1514,   -717,   0xcc, 0xba, 0xa5, 0xff
vertex     -8,     35,     -4,    250, -11763,   0xc1, 0x06, 0x93, 0xff
vertex     -8,    -25,     -4,    250,   -717,   0xcc, 0xba, 0xa5, 0xff
vertex     -8,     35,      4,   1797, -11763,   0xc1, 0x06, 0x6d, 0xff

bonfire_vertex_11: /* 11 vertices out of 15 */
vertex     -8,     35,      4,   1797, -11763,   0xc1, 0x06, 0x6d, 0xff
vertex     -8,    -25,     -4,    250,   -717,   0xcc, 0xba, 0xa5, 0xff
vertex     -8,    -25,      4,   1797,   -717,   0xcc, 0xba, 0x5b, 0xff
vertex     -8,     35,      4,    533, -11763,   0xc1, 0x06, 0x6d, 0xff
vertex     -1,    -25,      0,   1872,   -717,   0x69, 0xba, 0x00, 0xff
vertex     -1,     35,      0,   1872, -11763,   0x7e, 0x06, 0x00, 0xff
vertex     -8,    -25,      4,    533,   -717,   0xcc, 0xba, 0x5b, 0xff
vertex      3,     38,     -7,   -640, -12294,   0x5b, 0x56, 0xf0, 0xff
vertex     -4,     34,    -12,    698, -11519,   0xe8, 0xc6, 0x92, 0xff
vertex     -4,     38,    -12,    698, -12294,   0xe1, 0x56, 0xa9, 0xff
vertex      3,     34,     -7,   -640, -11519,   0x6b, 0xc6, 0xde, 0xff

bonfire_vertex_12: /* 11 vertices out of 15 */
vertex    -17,     38,      4,   1797, -12294,   0xc4, 0x56, 0x47, 0xff
vertex    -17,     38,     -4,    250, -12294,   0xc4, 0x56, 0xb9, 0xff
vertex    -17,     34,     -4,    250, -11519,   0xad, 0xc6, 0xb5, 0xff
vertex    -17,     34,      4,   1797, -11519,   0xad, 0xc6, 0x4b, 0xff
vertex      3,     38,      7,   2688, -12294,   0x5b, 0x56, 0x10, 0xff
vertex     -4,     38,     12,   1349, -12294,   0xe1, 0x56, 0x57, 0xff
vertex     -4,     34,     12,   1349, -11519,   0xe8, 0xc6, 0x6e, 0xff
vertex      3,     34,      7,   2688, -11519,   0x6b, 0xc6, 0x22, 0xff
vertex     -4,     34,    -12,    698,  -3210,   0xe8, 0xc6, 0x92, 0xff
vertex     -1,     31,      0,    175,  -1023,   0x54, 0xa2, 0x00, 0xff
vertex     -8,     31,     -4,   1514,  -1797,   0xd6, 0xa2, 0xb7, 0xff

bonfire_vertex_13: /* 11 vertices out of 15 */
vertex     -1,     31,      0,    175,  -1023,   0x54, 0xa2, 0x00, 0xff
vertex     -4,     34,    -12,    698,  -3210,   0xe8, 0xc6, 0x92, 0xff
vertex      3,     34,     -7,   -640,  -2437,   0x6b, 0xc6, 0xde, 0xff
vertex     -8,     35,     -4,    250, -11702,   0xd5, 0x5c, 0xb5, 0xff
vertex     -4,     34,    -12,  -1162, -11519,   0xe8, 0xc6, 0x92, 0xff
vertex     -8,     31,     -4,    250, -10927,   0xd6, 0xa2, 0xb7, 0xff
vertex     -4,     38,    -12,  -1162, -12294,   0xe1, 0x56, 0xa9, 0xff
vertex      3,     38,     -7,   2688,  -2437,   0x5b, 0x56, 0xf0, 0xff
vertex     -8,     35,     -4,    533,  -1797,   0xd5, 0x5c, 0xb5, 0xff
vertex     -1,     35,      0,   1872,  -1023,   0x57, 0x5c, 0x00, 0xff
vertex     -4,     38,    -12,   1349,  -3210,   0xe1, 0x56, 0xa9, 0xff

bonfire_vertex_14: /* 9 vertices out of 15 */
vertex     -1,     31,      0,   1023, -10927,   0x54, 0xa2, 0x00, 0xff
vertex      3,     34,     -7,   2437, -11519,   0x6b, 0xc6, 0xde, 0xff
vertex     -1,     35,      0,   1023, -11702,   0x57, 0x5c, 0x00, 0xff
vertex      3,     38,     -7,   2437, -12294,   0x5b, 0x56, 0xf0, 0xff
vertex     -1,     31,      0,    175,  -1023,   0x54, 0xa2, 0x00, 0xff
vertex     -4,     34,     12,    698,   1162,   0xe8, 0xc6, 0x6e, 0xff
vertex     -8,     31,      4,   1514,   -250,   0xd6, 0xa2, 0x49, 0xff
vertex      3,     34,      7,   -640,    389,   0x6b, 0xc6, 0x22, 0xff
vertex      3,     34,      7,   -389, -11519,   0x6b, 0xc6, 0x22, 0xff

bonfire_vertex_15: /* 11 vertices out of 15 */
vertex      3,     34,      7,   -389, -11519,   0x6b, 0xc6, 0x22, 0xff
vertex     -1,     35,      0,   1023, -11702,   0x57, 0x5c, 0x00, 0xff
vertex      3,     38,      7,   -389, -12294,   0x5b, 0x56, 0x10, 0xff
vertex     -8,     35,      4,    533,   -250,   0xd5, 0x5c, 0x4b, 0xff
vertex      3,     38,      7,   2688,    389,   0x5b, 0x56, 0x10, 0xff
vertex     -1,     35,      0,   1872,  -1023,   0x57, 0x5c, 0x00, 0xff
vertex     -4,     38,     12,   1349,   1162,   0xe1, 0x56, 0x57, 0xff
vertex     -8,     31,      4,   1797, -10927,   0xd6, 0xa2, 0x49, 0xff
vertex     -4,     34,     12,   3210, -11519,   0xe8, 0xc6, 0x6e, 0xff
vertex     -8,     35,      4,   1797, -11702,   0xd5, 0x5c, 0x4b, 0xff
vertex     -4,     38,     12,   3210, -12294,   0xe1, 0x56, 0x57, 0xff

bonfire_vertex_16: /* 11 vertices out of 15 */
vertex     -8,     31,      4,   1514,   -250,   0xd6, 0xa2, 0x49, 0xff
vertex    -17,     34,     -4,   3147,  -1797,   0xad, 0xc6, 0xb5, 0xff
vertex     -8,     31,     -4,   1514,  -1797,   0xd6, 0xa2, 0xb7, 0xff
vertex    -17,     34,      4,   3147,   -250,   0xad, 0xc6, 0x4b, 0xff
vertex     -8,     35,      4,    533, -11702,   0xd5, 0x5c, 0x4b, 0xff
vertex    -17,     34,      4,  -1099, -11519,   0xad, 0xc6, 0x4b, 0xff
vertex     -8,     31,      4,    533, -10927,   0xd6, 0xa2, 0x49, 0xff
vertex    -17,     38,      4,  -1099, -12294,   0xc4, 0x56, 0x47, 0xff
vertex     -8,     35,     -4,    533,  -1797,   0xd5, 0x5c, 0xb5, 0xff
vertex    -17,     38,      4,  -1099,   -250,   0xc4, 0x56, 0x47, 0xff
vertex     -8,     35,      4,    533,   -250,   0xd5, 0x5c, 0x4b, 0xff

bonfire_vertex_17: /* 13 vertices out of 15 */
vertex    -17,     38,      4,  -1099,   -250,   0xc4, 0x56, 0x47, 0xff
vertex     -8,     35,     -4,    533,  -1797,   0xd5, 0x5c, 0xb5, 0xff
vertex    -17,     38,     -4,  -1099,  -1797,   0xc4, 0x56, 0xb9, 0xff
vertex     -8,     31,     -4,   1514, -10927,   0xd6, 0xa2, 0xb7, 0xff
vertex    -17,     34,     -4,   3147, -11519,   0xad, 0xc6, 0xb5, 0xff
vertex     -8,     35,     -4,   1514, -11702,   0xd5, 0x5c, 0xb5, 0xff
vertex    -17,     38,     -4,   3147, -12294,   0xc4, 0x56, 0xb9, 0xff
vertex     -7,     64,     -1,    820,  -1299,   0xcd, 0x4b, 0xa8, 0xff
vertex     -7,     64,      1,    820,   -748,   0xcd, 0x4b, 0x58, 0xff
vertex     -4,     64,      0,   1298,  -1023,   0x66, 0x4b, 0x00, 0xff
vertex     -4,     64,      0,    749, -16861,   0x66, 0x4b, 0x00, 0xff
vertex     -8,     35,     -4,   1514, -11763,   0xc1, 0x06, 0x93, 0xff
vertex     -7,     64,     -1,   1227, -16861,   0xcd, 0x4b, 0xa8, 0xff

bonfire_vertex_18: /* 11 vertices out of 15 */
vertex     -8,     35,     -4,   1514, -11763,   0xc1, 0x06, 0x93, 0xff
vertex     -4,     64,      0,    749, -16861,   0x66, 0x4b, 0x00, 0xff
vertex     -1,     35,      0,    175, -11763,   0x7e, 0x06, 0x00, 0xff
vertex     -7,     64,     -1,    748, -16861,   0xcd, 0x4b, 0xa8, 0xff
vertex     -8,     35,     -4,    250, -11763,   0xc1, 0x06, 0x93, 0xff
vertex     -7,     64,      1,   1299, -16861,   0xcd, 0x4b, 0x58, 0xff
vertex     -8,     35,      4,   1797, -11763,   0xc1, 0x06, 0x6d, 0xff
vertex     -7,     64,      1,    820, -16861,   0xcd, 0x4b, 0x58, 0xff
vertex     -8,     35,      4,    533, -11763,   0xc1, 0x06, 0x6d, 0xff
vertex     -4,     64,      0,   1298, -16861,   0x66, 0x4b, 0x00, 0xff
vertex     -1,     35,      0,   1872, -11763,   0x7e, 0x06, 0x00, 0xff

bonfire_vertex_19: /* 9 vertices out of 15 */
vertex     -5,     64,      0,  -1515,  -7539,   0x79, 0x16, 0xe2, 0xff
vertex     -6,     64,      0,  -1314,  -7539,   0xe6, 0x4a, 0x9d, 0xff
vertex     -6,     65,      0,  -1613,  -7938,   0xbb, 0x00, 0x96, 0xff
vertex     -5,     65,      1,  -1814,  -7938,   0x7b, 0x00, 0x1e, 0xff
vertex     -6,     64,      0,   3362,  -7539,   0xe6, 0x4a, 0x9d, 0xff
vertex     -6,     64,      0,   3763,  -7539,   0xc6, 0xbd, 0x5a, 0xff
vertex     -6,     65,      2,   4062,  -7938,   0xe0, 0x00, 0x7a, 0xff
vertex     -6,     65,      0,   3661,  -7938,   0xbb, 0x00, 0x96, 0xff
vertex     -6,     64,      0,  -1715,  -7539,   0xc6, 0xbd, 0x5a, 0xff

bonfire_vertex_20: /* 10 vertices out of 15 */
vertex     -6,     64,      0,  -1715,  -7539,   0xc6, 0xbd, 0x5a, 0xff
vertex     -5,     65,      1,  -1814,  -7938,   0x7b, 0x00, 0x1e, 0xff
vertex     -6,     65,      2,  -2014,  -7938,   0xe0, 0x00, 0x7a, 0xff
vertex     -6,     65,      0,  -1613,  -7938,   0xbb, 0x00, 0x96, 0xff
vertex     -6,     66,      0,  -1515,  -8068,   0xd0, 0xd9, 0x92, 0xff
vertex     -5,     67,      0,  -1515,  -8336,   0x3d, 0x54, 0xb8, 0xff
vertex     -6,     65,      0,   3661,  -7938,   0xbb, 0x00, 0x96, 0xff
vertex     -6,     65,      2,   4062,  -7938,   0xe0, 0x00, 0x7a, 0xff
vertex     -6,     67,      0,   3763,  -8336,   0xd0, 0x6c, 0x2c, 0xff
vertex     -6,     66,      0,   3563,  -8068,   0xd0, 0xd9, 0x92, 0xff

bonfire_vertex_21: /* 11 vertices out of 15 */
vertex     -6,     65,      2,  -2014,  -7938,   0xe0, 0x00, 0x7a, 0xff
vertex     -5,     65,      1,  -1814,  -7938,   0x7b, 0x00, 0x1e, 0xff
vertex     -5,     67,      0,  -1515,  -8336,   0x3d, 0x54, 0xb8, 0xff
vertex     -6,     67,      0,  -1715,  -8336,   0xd0, 0x6c, 0x2c, 0xff
vertex     -6,     67,      0,   3763,  -8336,   0xd0, 0x6c, 0x2c, 0xff
vertex     -5,     67,      0,   3563,  -8336,   0x3d, 0x54, 0xb8, 0xff
vertex     -6,     66,      0,   3563,  -8068,   0xd0, 0xd9, 0x92, 0xff
vertex     -6,     65,      0,  -1416,  -7938,   0xbb, 0x00, 0x6a, 0xff
vertex     -6,     65,      0,  -1516,  -7808,   0xf1, 0x4b, 0x64, 0xff
vertex     -5,     64,      0,  -1515,  -7539,   0x7d, 0xf6, 0xf2, 0xff
vertex     -5,     65,     -1,  -1216,  -7938,   0x7b, 0x00, 0xe2, 0xff

bonfire_vertex_22: /* 10 vertices out of 15 */
vertex     -6,     65,     -2,   3064,  -7938,   0xe0, 0x00, 0x86, 0xff
vertex     -6,     64,      0,   3362,  -7539,   0x0e, 0xb5, 0x9c, 0xff
vertex     -6,     65,      0,   3564,  -7808,   0xf1, 0x4b, 0x64, 0xff
vertex     -6,     65,      0,   3464,  -7938,   0xbb, 0x00, 0x6a, 0xff
vertex     -5,     65,     -1,  -1216,  -7938,   0x7b, 0x00, 0xe2, 0xff
vertex     -5,     64,      0,  -1515,  -7539,   0x7d, 0xf6, 0xf2, 0xff
vertex     -6,     64,      0,  -1314,  -7539,   0x0e, 0xb5, 0x9c, 0xff
vertex     -6,     65,     -2,  -1016,  -7938,   0xe0, 0x00, 0x86, 0xff
vertex     -6,     67,      0,  -1715,  -8336,   0xf9, 0x7b, 0x1c, 0xff
vertex     -6,     65,      0,  -1416,  -7938,   0xbb, 0x00, 0x6a, 0xff

bonfire_vertex_23: /* 9 vertices out of 15 */
vertex     -6,     67,      0,  -1715,  -8336,   0xf9, 0x7b, 0x1c, 0xff
vertex     -5,     65,     -1,  -1216,  -7938,   0x7b, 0x00, 0xe2, 0xff
vertex     -5,     67,      0,  -1515,  -8336,   0x69, 0x41, 0x1a, 0xff
vertex     -6,     67,      0,   3362,  -8336,   0xd2, 0x5e, 0xb9, 0xff
vertex     -6,     65,     -2,   3064,  -7938,   0xe0, 0x00, 0x86, 0xff
vertex     -6,     65,      0,   3464,  -7938,   0xbb, 0x00, 0x6a, 0xff
vertex     -6,     67,      0,   3763,  -8336,   0xf9, 0x7b, 0x1c, 0xff
vertex     -6,     65,     -2,  -1016,  -7938,   0xe0, 0x00, 0x86, 0xff
vertex     -6,     67,      0,  -1314,  -8336,   0xd2, 0x5e, 0xb9, 0xff

bonfire_vertex_24: /* 8 vertices out of 15 */
vertex     -6,     67,      0,   4365,   1715,   0xf9, 0x7b, 0x1c, 0xff
vertex     -5,     67,      0,   4526,   1515,   0x69, 0x41, 0x1a, 0xff
vertex     -6,     67,      0,   4365,   1314,   0xd2, 0x5e, 0xb9, 0xff
vertex     -6,    -22,      0,   2729,  -1540,   0x00, 0x7f, 0x00, 0xff
vertex     57,    -57,    -24,   5707,  -2685,   0x37, 0x71, 0xf2, 0xff
vertex     36,    -57,    -52,   4738,  -4018,   0x1f, 0x75, 0xdc, 0xff
vertex     57,    -57,     24,   5707,   -395,   0x2c, 0x75, 0x12, 0xff
vertex     -9,    -57,    -68,   2561,  -4726,   0x03, 0x71, 0xc7, 0xff

bonfire_vertex_25: /* 7 vertices out of 15 */
vertex    -43,    -57,    -57,    993,  -4217,   0xe7, 0x75, 0xd7, 0xff
vertex     -6,    -22,      0,   2729,  -1540,   0x00, 0x7f, 0x00, 0xff
vertex     -9,    -57,    -68,   2561,  -4726,   0x03, 0x71, 0xc7, 0xff
vertex    -72,    -57,    -17,   -352,  -2364,   0xcb, 0x71, 0xec, 0xff
vertex    -72,    -57,     17,   -352,   -715,   0xd2, 0x75, 0x0b, 0xff
vertex    -43,    -57,     57,    993,   1136,   0xdc, 0x71, 0x2c, 0xff
vertex     -9,    -57,     68,   2561,   1646,   0xfd, 0x75, 0x2f, 0xff

bonfire_vertex_26: /* 4 vertices out of 6 */
vertex     57,    -57,     24,   5707,   -395,   0x2c, 0x75, 0x12, 0xff
vertex     -6,    -22,      0,   2729,  -1540,   0x00, 0x7f, 0x00, 0xff
vertex     36,    -57,     52,   4738,    938,   0x1f, 0x71, 0x30, 0xff
vertex     -9,    -57,     68,   2561,   1646,   0xfd, 0x75, 0x2f, 0xff

/* Render order: 1 */

glabel bonfire_dl_opaque
gsSPClearGeometryMode G_LIGHTING
/* #LIGHTING 08 - Default */
gsDPPipeSync
gsSPSetGeometryMode G_LIGHTING
gsSPNumLights NUMLIGHTS_1
gsSPLight bonfire_diffuse_light, 1
gsSPLight bonfire_ambient_light, 2
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock bonfire_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSPVertex bonfire_vertex_0, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 1, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_1, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 8, 7, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_2, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_3, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 8, 10, 0x00
gsSPVertex bonfire_vertex_4, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 4, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 8, 7, 10, 0x00
gsSPVertex bonfire_vertex_5, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 1, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 8, 7, 10, 0x00
gsSPVertex bonfire_vertex_6, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 1, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_7, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 8, 10, 0x00
gsSPVertex bonfire_vertex_8, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_9, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 4, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 8, 7, 10, 0x00
gsSPVertex bonfire_vertex_10, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
/* #LIGHTING 07 - Default */
gsDPPipeSync
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock bonfire_texture_1, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsDPTileSync
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 8, 7, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_11, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 8, 7, 10, 0x00
gsSPVertex bonfire_vertex_12, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_13, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 8, 7, 10, 0x00
gsSPVertex bonfire_vertex_14, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 2, 1, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 2, 8, 0, 0x00
gsSPVertex bonfire_vertex_15, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 10, 9, 8, 0x00
gsSPVertex bonfire_vertex_16, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 5, 4, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex bonfire_vertex_17, 13, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 5, 4, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 10, 11, 12, 0x00
gsSPVertex bonfire_vertex_18, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 6, 5, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 8, 10, 9, 0x00
gsSPVertex bonfire_vertex_19, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 0, 3, 0x00
gsSPVertex bonfire_vertex_20, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 4, 0x00
gsSP1Triangle 1, 4, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSP1Triangle 6, 8, 9, 0x00
gsSPVertex bonfire_vertex_21, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex bonfire_vertex_22, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 4, 0x00
gsSPVertex bonfire_vertex_23, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 2, 1, 7, 0x00
gsSP1Triangle 2, 7, 8, 0x00
gsSPVertex bonfire_vertex_24, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 0, 0x00
/* #LIGHTING 03 - Default */
gsDPPipeSync
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock bonfire_texture_2, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsDPTileSync
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 4, 3, 6, 0x00
gsSP1Triangle 5, 7, 3, 0x00
gsSPVertex bonfire_vertex_25, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
gsSP1Triangle 1, 3, 4, 0x00
gsSP1Triangle 5, 1, 4, 0x00
gsSP1Triangle 1, 5, 6, 0x00
gsSPVertex bonfire_vertex_26, 4, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 3, 2, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPEndDisplayList
