/* Generated by modconv 2 */

glabel pipeMimic_collision
colInit
colVertexInit 32
colVertex 50, -37, 0
colVertex 35, -37, -36
colVertex 35, 21, -36
colVertex 50, 21, 0
colVertex 0, -37, -51
colVertex 0, 21, -51
colVertex -36, -37, -36
colVertex -36, 21, -36
colVertex -51, -37, 0
colVertex -51, 21, 0
colVertex -36, -37, 35
colVertex -36, 21, 35
colVertex 0, -37, 50
colVertex 0, 21, 50
colVertex 35, -37, 35
colVertex 35, 21, 35
colVertex 25, 21, -26
colVertex 36, 21, 0
colVertex 0, 21, -37
colVertex -26, 21, -26
colVertex -37, 21, 0
colVertex -26, 21, 25
colVertex 0, 21, 36
colVertex 25, 21, 25
colVertex 25, -37, -26
colVertex 36, -37, 0
colVertex 0, -37, -37
colVertex -26, -37, -26
colVertex -37, -37, 0
colVertex -26, -37, 25
colVertex 0, -37, 36
colVertex 25, -37, 25

colTriInit SURFACE_DEFAULT, 54
colTri      0,      1,      2
colTri      2,      3,      0
colTri      1,      4,      5
colTri      5,      2,      1
colTri      4,      6,      7
colTri      7,      5,      4
colTri      6,      8,      9
colTri      9,      7,      6
colTri      8,     10,     11
colTri     11,      9,      8
colTri     10,     12,     13
colTri     13,     11,     10
colTri     12,     14,     15
colTri     15,     13,     12
colTri     14,      0,      3
colTri      3,     15,     14
colTri      2,     16,     17
colTri     17,      3,      2
colTri      5,     18,     16
colTri     16,      2,      5
colTri      7,     19,     18
colTri     18,      5,      7
colTri      9,     20,     19
colTri     19,      7,      9
colTri     11,     21,     20
colTri     20,      9,     11
colTri     13,     22,     21
colTri     21,     11,     13
colTri     15,     23,     22
colTri     22,     13,     15
colTri      3,     17,     23
colTri     23,     15,      3
colTri     17,     16,     24
colTri     24,     25,     17
colTri     16,     18,     26
colTri     26,     24,     16
colTri     18,     19,     27
colTri     27,     26,     18
colTri     19,     20,     28
colTri     28,     27,     19
colTri     20,     21,     29
colTri     29,     28,     20
colTri     21,     22,     30
colTri     30,     29,     21
colTri     22,     23,     31
colTri     31,     30,     22
colTri     23,     17,     25
colTri     25,     31,     23
colTri     26,     27,     28
colTri     28,     29,     30
colTri     30,     31,     25
colTri     28,     30,     25
colTri     26,     28,     25
colTri     24,     26,     25
colTriStop
colEnd
