/* Generated by modconv 2 */

glabel pipeMimic_collision
colInit
colVertexInit 32
colVertex 178, -139, 0
colVertex 126, -139, -126
colVertex 126, 75, -126
colVertex 178, 75, 0
colVertex 0, -139, -178
colVertex 0, 75, -178
colVertex -125, -139, -126
colVertex -125, 75, -126
colVertex -177, -139, 0
colVertex -177, 75, 0
colVertex -125, -139, 125
colVertex -125, 75, 125
colVertex 0, -139, 177
colVertex 0, 75, 177
colVertex 126, -139, 125
colVertex 126, 75, 125
colVertex 91, 75, -91
colVertex 128, 75, 0
colVertex 0, 75, -128
colVertex -90, 75, -91
colVertex -127, 75, 0
colVertex -90, 75, 90
colVertex 0, 75, 127
colVertex 91, 75, 90
colVertex 128, -130, 0
colVertex 91, -130, -91
colVertex 0, -130, -128
colVertex -90, -130, -91
colVertex -127, -130, 0
colVertex -90, -130, 90
colVertex 0, -130, 127
colVertex 91, -130, 90

colTriInit SURFACE_DEFAULT, 54
colTri      0,      1,      2
colTri      2,      3,      0
colTri      1,      4,      5
colTri      5,      2,      1
colTri      4,      6,      7
colTri      7,      5,      4
colTri      6,      8,      9
colTri      9,      7,      6
colTri      8,     10,     11
colTri     11,      9,      8
colTri     10,     12,     13
colTri     13,     11,     10
colTri     12,     14,     15
colTri     15,     13,     12
colTri     14,      0,      3
colTri      3,     15,     14
colTri      2,     16,     17
colTri     17,      3,      2
colTri      5,     18,     16
colTri     16,      2,      5
colTri      7,     19,     18
colTri     18,      5,      7
colTri      9,     20,     19
colTri     19,      7,      9
colTri     11,     21,     20
colTri     20,      9,     11
colTri     13,     22,     21
colTri     21,     11,     13
colTri     15,     23,     22
colTri     22,     13,     15
colTri      3,     17,     23
colTri     23,     15,      3
colTri     24,     17,     16
colTri     16,     25,     24
colTri     25,     16,     18
colTri     18,     26,     25
colTri     26,     18,     19
colTri     19,     27,     26
colTri     27,     19,     20
colTri     20,     28,     27
colTri     28,     20,     21
colTri     21,     29,     28
colTri     29,     21,     22
colTri     22,     30,     29
colTri     30,     22,     23
colTri     23,     31,     30
colTri     31,     23,     17
colTri     17,     24,     31
colTri     26,     27,     28
colTri     28,     29,     30
colTri     30,     31,     24
colTri     28,     30,     24
colTri     26,     28,     24
colTri     25,     26,     24
colTriStop
colEnd
