/* Generated by modconv 2 */

glabel pipeMimic_geo
    geo_shadow SHADOW_CIRCLE_4_VERTS, 0xC8, 125
        geo_open_node
            geo_scale 0x00, 16384
            geo_open_node
                geo_display_list LAYER_OPAQUE pipeMimic_dl_opaque
            geo_close_node
        geo_close_node
    geo_end
