/* Generated by modconv 2 */

model_vertex_0: /* 11 vertices out of 15 */
vertex    695,      0,   2450,  20447,   4608,   0xff, 0xff, 0xff, 0xff
vertex    695,      0,  -2564,  20447, -32068,   0xff, 0xff, 0xff, 0xff
vertex   -139,      0,  -2564,  14337, -32068,   0xff, 0xff, 0xff, 0xff
vertex   -139,      0,   2450,  14337,   4607,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   2450,  20447,   2560,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   2450,  21115,   2560,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   1636,  21115,  -3387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   1636,  20447,  -3387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   1636,  13668,  -3387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   2450,  13668,   2559,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   2450,  14337,   2559,   0xff, 0xff, 0xff, 0xff

model_vertex_1: /* 11 vertices out of 15 */
vertex   -139,    280,   2450,  14337,   2559,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   1636,  14337,  -3387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   1636,  13668,  -3387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   1286,  20447, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   1286,  21115, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   1286,  21115, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   1286,  20447, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   1286,  20447,  -5947,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   1636,  20447,  -3387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   1636,  21115,  -3387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   1286,  21115,  -5947,   0xff, 0xff, 0xff, 0xff

model_vertex_2: /* 11 vertices out of 15 */
vertex    786,    280,   1636,   9604, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   1636,   9604, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   1636,  10272, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   1636,  10272, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   1286,  13668, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   1286,  13668, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   1286,  14337, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   1286,  14337, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   1286,  13668,  -5947,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   1636,  13668,  -3387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   1636,  14337,  -3387,   0xff, 0xff, 0xff, 0xff

model_vertex_3: /* 11 vertices out of 15 */
vertex   -139,    144,   1636,  14337,  -3387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   1286,  14337,  -5947,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   1286,  13668,  -5947,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   1636,  16382, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   1636,  17051, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   1636,  17051, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   1636,  16382, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    937,  21115,  -8505,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,    937,  20447,  -8505,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   1286,  20447,  -5947,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   1286,  21115,  -5947,   0xff, 0xff, 0xff, 0xff

model_vertex_4: /* 11 vertices out of 15 */
vertex   -139,    280,    937,  14337,  -8505,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,    937,  13668,  -8505,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   1286,  13668,  -5947,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   1286,  14337,  -5947,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,    587,  13668, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    587,  13668, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    587,  14337, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,    587,  14337, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    587,  13668, -11065,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    937,  13668,  -8505,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    937,  14337,  -8505,   0xff, 0xff, 0xff, 0xff

model_vertex_5: /* 11 vertices out of 15 */
vertex   -139,    144,    937,  14337,  -8505,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    587,  14337, -11065,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    587,  13668, -11065,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    937,  16382, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    937,  17051, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,    937,  17051, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,    937,  16382, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    587,  21115, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,    587,  20447, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    587,  20447, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    587,  21115, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_6: /* 11 vertices out of 15 */
vertex    695,    144,    587,  20447, -11065,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    937,  20447,  -8505,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    937,  21115,  -8505,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    587,  21115, -11065,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    937,   9604, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    937,   9604, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    937,  10272, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,    937,  10272, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    237,  21115, -13624,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,    237,  20447, -13624,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,    587,  20447, -11065,   0xff, 0xff, 0xff, 0xff

model_vertex_7: /* 11 vertices out of 15 */
vertex    695,    280,    587,  20447, -11065,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    587,  21115, -11065,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    237,  21115, -13624,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,    237,  14337, -13624,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,    237,  13668, -13624,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,    587,  13668, -11065,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,    587,  14337, -11065,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -112,  13668, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -112,  13668, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -112,  14337, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   -112,  14337, -16387,   0xff, 0xff, 0xff, 0xff

model_vertex_8: /* 11 vertices out of 15 */
vertex   -231,    144,   -112,  13668, -16184,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    237,  13668, -13624,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    237,  14337, -13624,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -112,  14337, -16184,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    237,  16382, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    237,  17051, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,    237,  17051, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,    237,  16382, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -112,  21115, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   -112,  20447, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -112,  20447, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_9: /* 11 vertices out of 15 */
vertex    695,    144,   -112,  20447, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -112,  21115, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -112,  21115, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -112,  20447, -16184,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    237,  20447, -13624,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    237,  21115, -13624,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -112,  21115, -16184,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    237,   9604, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    237,   9604, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    237,  10272, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,    237,  10272, -16387,   0xff, 0xff, 0xff, 0xff

model_vertex_10: /* 11 vertices out of 15 */
vertex    786,    280,   -462,  21115, -18743,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   -462,  20447, -18743,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   -112,  20447, -16184,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -112,  21115, -16184,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   -462,  14337, -18743,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -462,  13668, -18743,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -112,  13668, -16184,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   -112,  14337, -16184,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -812,  13668, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -812,  13668, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -812,  14337, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_11: /* 11 vertices out of 15 */
vertex   -139,    144,   -812,  14337, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   -812,  14337, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -812,  13668, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -812,  13668, -21303,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -462,  13668, -18743,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -462,  14337, -18743,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -812,  14337, -21303,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -462,  16382, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -462,  17051, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -462,  17051, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   -462,  16382, -16387,   0xff, 0xff, 0xff, 0xff

model_vertex_12: /* 11 vertices out of 15 */
vertex    786,    280,   -812,  21115, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   -812,  20447, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -812,  20447, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -812,  21115, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -812,  20447, -21303,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -462,  20447, -18743,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -462,  21115, -18743,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -812,  21115, -21303,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -462,   9604, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -462,   9604, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -462,  10272, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_13: /* 11 vertices out of 15 */
vertex    695,    144,   -462,  10272, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   -462,  10272, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -462,   9604, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -1162,  21115, -23861,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1162,  20447, -23861,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   -812,  20447, -21303,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -812,  21115, -21303,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1162,  14337, -23861,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -1162,  13668, -23861,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -812,  13668, -21303,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   -812,  14337, -21303,   0xff, 0xff, 0xff, 0xff

model_vertex_14: /* 11 vertices out of 15 */
vertex   -231,    280,  -1512,  13668, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1512,  13668, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1512,  14337, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1512,  14337, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1512,  13668, -26421,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1162,  13668, -23861,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1162,  14337, -23861,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1512,  14337, -26421,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1162,  16382, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1162,  17051, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -1162,  17051, -16387,   0xff, 0xff, 0xff, 0xff

model_vertex_15: /* 11 vertices out of 15 */
vertex   -231,    280,  -1162,  17051, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1162,  16382, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1162,  16382, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -1512,  21115, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1512,  20447, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1512,  20447, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1512,  21115, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1512,  20447, -26421,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1162,  20447, -23861,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1162,  21115, -23861,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1512,  21115, -26421,   0xff, 0xff, 0xff, 0xff

model_vertex_16: /* 11 vertices out of 15 */
vertex    786,    280,  -1162,   9604, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1162,   9604, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1162,  10272, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1162,  10272, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -1862,  21115, -28980,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1862,  20447, -28980,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1512,  20447, -26421,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -1512,  21115, -26421,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1862,  14337, -28980,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -1862,  13668, -28980,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -1512,  13668, -26421,   0xff, 0xff, 0xff, 0xff

model_vertex_17: /* 11 vertices out of 15 */
vertex   -231,    280,  -1512,  13668, -26421,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1512,  14337, -26421,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1862,  14337, -28980,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -2212,  13668, -29492,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -2212,  14337, -29492,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -2564,  14337, -32068,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -2564,  13668, -32068,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -2212,  20447, -29492,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -2212,  21115, -29492,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -2564,  21115, -32068,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -2564,  20447, -32068,   0xff, 0xff, 0xff, 0xff

model_vertex_18: /* 11 vertices out of 15 */
vertex   -231,    280,  -2212,  13668, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -2212,  13668, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -2212,  14337, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -2212,  14337, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -2212,  14337, -31540,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -2212,  13668, -31540,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1862,  13668, -28980,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1862,  14337, -28980,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1862,  16382, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1862,  17051, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -1862,  17051, -16387,   0xff, 0xff, 0xff, 0xff

model_vertex_19: /* 11 vertices out of 15 */
vertex   -231,    280,  -1862,  17051, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1862,  16382, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1862,  16382, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -2212,  21115, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -2212,  20447, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -2212,  20447, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -2212,  21115, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -2212,  21115, -31540,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -2212,  20447, -31540,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1862,  20447, -28980,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1862,  21115, -28980,   0xff, 0xff, 0xff, 0xff

model_vertex_20: /* 11 vertices out of 15 */
vertex    786,    280,  -1862,   9604, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1862,   9604, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1862,  10272, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1862,  10272, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -2212,   -820, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -2212,   -820, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -2564,  -3396, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    -10,  -2564,  -3396, -14259,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -2212,  -2868, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    -10,  -2564,  -5444, -14259,   0xff, 0xff, 0xff, 0xff
vertex   -231,    -10,   2450,  31231, -14259,   0xff, 0xff, 0xff, 0xff

model_vertex_21: /* 10 vertices out of 15 */
vertex   -231,    144,  -1862,   -309, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -2212,  -2868, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    -10,   2450,  31231, -14259,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   2450,  31231, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   1636,  25284, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   1636,  25284, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   1286,  22724, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   1286,  24772, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,    937,  22214, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    937,  22214, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_22: /* 11 vertices out of 15 */
vertex   -231,    144,   1286,  24772, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   1286,  24772, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    937,  22214, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    -10,   2450,  31231, -14259,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   1286,  22724, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    937,  20166, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    587,  17606, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    587,  19654, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,    587,  19654, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,    237,  17095, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    237,  17095, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_23: /* 9 vertices out of 15 */
vertex   -231,    -10,   2450,  31231, -14259,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    587,  17606, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,    237,  15047, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -112,  12487, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -112,  14535, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -462,  11976, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -462,  11976, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -112,  14535, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -462,   9928, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_24: /* 9 vertices out of 15 */
vertex   -231,    -10,   2450,  31231, -14259,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -462,   9928, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -812,   7368, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,   -812,   9416, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,   -812,   9416, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -1162,   6858, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1162,   6858, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1162,   4810, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1512,   2250, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_25: /* 11 vertices out of 15 */
vertex   -231,    144,  -1862,   -309, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    -10,   2450,  31231, -14259,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1512,   2250, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -1862,   1739, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1862,   1739, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    144,  -1512,   4298, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -231,    280,  -1512,   4298, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   1636,   3387, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   1636,   3387, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   2450,  -2559, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,      0,   2450,  -2559, -14336,   0xff, 0xff, 0xff, 0xff

model_vertex_26: /* 10 vertices out of 15 */
vertex   -139,    144,   1286,   5947, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   1636,   3387, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,      0,   2450,  -2559, -14336,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -2564,  32068, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -2212,  29492, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -2212,  29492, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,      0,  -2564,  32068, -14336,   0xff, 0xff, 0xff, 0xff
vertex   -139,      0,   2450,  -4607, -14336,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -2212,  31540, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1862,  28980, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_27: /* 9 vertices out of 15 */
vertex   -139,    144,  -1862,  28980, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1862,  28980, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1512,  26421, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1512,  26421, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,      0,   2450,  -2559, -14336,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,  -1162,  23861, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1162,  23861, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   -812,  21303, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -812,  21303, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_28: /* 8 vertices out of 15 */
vertex   -139,    144,  -1162,  23861, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,  -1162,  23861, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -812,  21303, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,      0,   2450,  -2559, -14336,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -462,  18743, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   -462,  18743, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   -112,  16184, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -112,  16184, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_29: /* 7 vertices out of 15 */
vertex   -139,      0,   2450,  -2559, -14336,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -462,  18743, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   -112,  16184, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    237,  13624, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,    237,  13624, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,    587,  11065, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    587,  11065, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_30: /* 9 vertices out of 15 */
vertex   -139,      0,   2450,  -2559, -14336,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    587,  11065, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,    937,   8505, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    144,   1286,   5947, -15396,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,   1286,   5947, -16387,   0xff, 0xff, 0xff, 0xff
vertex   -139,    280,    937,   8505, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   1636,   3387, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   1636,   3387, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   2450,  -2560, -16387,   0xff, 0xff, 0xff, 0xff

model_vertex_31: /* 9 vertices out of 15 */
vertex    786,    144,   1636,   3387, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   2450,  -2560, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    -10,   2450,  -2560, -14259,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   1286,   5947, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -2564,  32068, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -2212,  29492, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -2212,  29492, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    -10,  -2564,  32068, -14259,   0xff, 0xff, 0xff, 0xff
vertex    786,    -10,   2450,  -4608, -14259,   0xff, 0xff, 0xff, 0xff

model_vertex_32: /* 7 vertices out of 15 */
vertex    786,    -10,   2450,  -2560, -14259,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -2212,  31540, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1862,  28980, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -1862,  28980, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,  -1512,  26421, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1512,  26421, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1162,  23861, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_33: /* 9 vertices out of 15 */
vertex    786,    280,  -1162,  23861, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -812,  21303, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -812,  21303, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,  -1162,  23861, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    -10,   2450,  -2560, -14259,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -462,  18743, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -462,  18743, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -112,  16184, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -112,  16184, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_34: /* 8 vertices out of 15 */
vertex    786,    144,   -462,  18743, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   -462,  18743, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   -112,  16184, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    -10,   2450,  -2560, -14259,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    237,  13624, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    237,  13624, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    587,  11065, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    587,  11065, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_35: /* 7 vertices out of 15 */
vertex    786,    -10,   2450,  -2560, -14259,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    237,  13624, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    587,  11065, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,    937,   8505, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    144,   1286,   5947, -15396,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,   1286,   5947, -16387,   0xff, 0xff, 0xff, 0xff
vertex    786,    280,    937,   8505, -16387,   0xff, 0xff, 0xff, 0xff

model_vertex_36: /* 11 vertices out of 15 */
vertex    695,    144,  -2212,   -820, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -2212,   -820, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -2564,  -3396, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,      0,  -2564,  -3396, -14336,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -2212,  -2868, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,      0,  -2564,  -5444, -14336,   0xff, 0xff, 0xff, 0xff
vertex    695,      0,   2450,  31232, -14336,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1862,   -309, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   2450,  31232, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   1636,  25284, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   1636,  25284, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_37: /* 9 vertices out of 15 */
vertex    695,      0,   2450,  31232, -14336,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   2450,  31232, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   1636,  25284, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   1286,  22724, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   1286,  24772, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,    937,  22214, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    937,  22214, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   1286,  24772, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    937,  20166, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_38: /* 9 vertices out of 15 */
vertex    695,      0,   2450,  31232, -14336,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    937,  20166, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    587,  17606, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    587,  19654, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,    587,  19654, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,    237,  17095, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    237,  17095, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,    237,  15047, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -112,  12487, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_39: /* 11 vertices out of 15 */
vertex    695,    280,   -112,  14535, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   -462,  11976, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -462,  11976, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -112,  14535, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,      0,   2450,  31232, -14336,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -112,  12487, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -462,   9928, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -812,   7368, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -812,   9416, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,   -812,   9416, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1162,   6858, -16387,   0xff, 0xff, 0xff, 0xff

model_vertex_40: /* 11 vertices out of 15 */
vertex    695,    144,   -812,   9416, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1162,   6858, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1162,   6858, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,      0,   2450,  31232, -14336,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,   -812,   7368, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1162,   4810, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1512,   2250, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1862,   -309, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1862,   1739, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1862,   1739, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1512,   4298, -15396,   0xff, 0xff, 0xff, 0xff

model_vertex_41: /* 10 vertices out of 15 */
vertex    695,    280,  -1862,   1739, -16387,   0xff, 0xff, 0xff, 0xff
vertex    695,    144,  -1512,   4298, -15396,   0xff, 0xff, 0xff, 0xff
vertex    695,    280,  -1512,   4298, -16387,   0xff, 0xff, 0xff, 0xff
vertex    789,  -4917,   1939,   9583,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -234,  -4917,   1939,  17072,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -234,   1506,   1939,  17072, -28022,   0xff, 0xff, 0xff, 0xff
vertex    789,   1506,   1939,   9583, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -787,  -4917,   2493,  25404,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -787,  -4917,   3340,  31602,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -787,   1506,   3340,  31602, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_42: /* 7 vertices out of 15 */
vertex   -787,   1506,   3340,  31602, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -787,   1506,   2493,  25404, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -787,  -4917,   2493,  25404,  18964,   0xff, 0xff, 0xff, 0xff
vertex   1343,   1506,   3340,  -9074, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1343,  -4917,   3340,  -9074,  18964,   0xff, 0xff, 0xff, 0xff
vertex   1343,  -4917,   2493,  -2876,  18964,   0xff, 0xff, 0xff, 0xff
vertex   1343,   1506,   2493,  -2876, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_43: /* 8 vertices out of 15 */
vertex    789,   1506,   3894,  21136, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -234,   1506,   3894,  13647, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -234,  -4917,   3894,  13647,  18964,   0xff, 0xff, 0xff, 0xff
vertex    789,  -4917,   3894,  21136,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -787,  -4917,   3340,  27506,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -234,  -4917,   3894,  31556,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -234,   1506,   3894,  31556, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -787,   1506,   3340,  27506, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_44: /* 7 vertices out of 15 */
vertex   -787,  -4917,   3340,  27506,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -234,   1506,   3894,  31556, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -787,   1506,   3340,  27506, -28022,   0xff, 0xff, 0xff, 0xff
vertex    789,   1506,   3894, -13124, -28022,   0xff, 0xff, 0xff, 0xff
vertex    789,  -4917,   3894, -13124,  18964,   0xff, 0xff, 0xff, 0xff
vertex   1343,  -4917,   3340,  -9074,  18964,   0xff, 0xff, 0xff, 0xff
vertex   1343,   1506,   3340,  -9074, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_45: /* 8 vertices out of 15 */
vertex   -234,  -4917,   1939,  17072,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -787,  -4917,   2493,  21122,  18964,   0xff, 0xff, 0xff, 0xff
vertex   -787,   1506,   2493,  21122, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -234,   1506,   1939,  17072, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1343,  -4917,   2493,  -2876,  18964,   0xff, 0xff, 0xff, 0xff
vertex    789,  -4917,   1939,   1174,  18964,   0xff, 0xff, 0xff, 0xff
vertex    789,   1506,   1939,   1174, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1343,   1506,   2493,  -2876, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_46: /* 11 vertices out of 15 */
vertex   1205,   1673,   2354,  -1863, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1205,   1506,   2354,  -1863, -28022,   0xff, 0xff, 0xff, 0xff
vertex    928,   1506,   2077,    161, -28022,   0xff, 0xff, 0xff, 0xff
vertex    928,   1673,   2077,    161, -29248,   0xff, 0xff, 0xff, 0xff
vertex    533,   1673,   1939,  11455, -29248,   0xff, 0xff, 0xff, 0xff
vertex    533,   1506,   1939,  11455, -28022,   0xff, 0xff, 0xff, 0xff
vertex     21,   1506,   1939,  15199, -28022,   0xff, 0xff, 0xff, 0xff
vertex     21,   1673,   1939,  15199, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -372,   1673,   2077,  18084, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -372,   1506,   2077,  18084, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -649,   1506,   2354,  20109, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_47: /* 11 vertices out of 15 */
vertex   -372,   1673,   2077,  18084, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -649,   1506,   2354,  20109, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -649,   1673,   2354,  20109, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1205,   1673,   2354,  24174, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1081,   1673,   2478,  23269, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1081,   1506,   2478,  23269, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1205,   1506,   2354,  24174, -28022,   0xff, 0xff, 0xff, 0xff
vertex    928,   1506,   2077,   8570, -28022,   0xff, 0xff, 0xff, 0xff
vertex    804,   1506,   2201,   9475, -28022,   0xff, 0xff, 0xff, 0xff
vertex    804,   1673,   2201,   9475, -29248,   0xff, 0xff, 0xff, 0xff
vertex    928,   1673,   2077,   8570, -29248,   0xff, 0xff, 0xff, 0xff

model_vertex_48: /* 11 vertices out of 15 */
vertex    533,   1673,   1939,   1174, -29248,   0xff, 0xff, 0xff, 0xff
vertex    533,   1673,   2114,   -105, -29248,   0xff, 0xff, 0xff, 0xff
vertex    533,   1506,   2114,   -105, -28022,   0xff, 0xff, 0xff, 0xff
vertex    533,   1506,   1939,   1174, -28022,   0xff, 0xff, 0xff, 0xff
vertex     21,   1506,   1939,  29545, -28022,   0xff, 0xff, 0xff, 0xff
vertex     21,   1506,   2114,  30825, -28022,   0xff, 0xff, 0xff, 0xff
vertex     21,   1673,   2114,  30825, -29248,   0xff, 0xff, 0xff, 0xff
vertex     21,   1673,   1939,  29545, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -372,   1673,   2077,    161, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -248,   1673,   2201,   -743, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -248,   1506,   2201,   -743, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_49: /* 11 vertices out of 15 */
vertex   -372,   1673,   2077,    161, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -248,   1506,   2201,   -743, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -372,   1506,   2077,    161, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -649,   1506,   2354,  30535, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -525,   1506,   2478,  31440, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -525,   1673,   2478,  31440, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -649,   1673,   2354,  30535, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -787,   1673,   2705,  21122, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -612,   1673,   2705,  19842, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -612,   1506,   2705,  19842, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -787,   1506,   2705,  21122, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_50: /* 11 vertices out of 15 */
vertex   -787,   1506,   3128,   9597, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -612,   1506,   3128,  10877, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -612,   1673,   3128,  10877, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -787,   1673,   3128,   9597, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -649,   1673,   3479,  20109, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -525,   1673,   3355,  19204, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -525,   1506,   3355,  19204, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -649,   1506,   3479,  20109, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -372,   1506,   3755,  12635, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -248,   1506,   3632,  13540, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -248,   1673,   3632,  13540, -29248,   0xff, 0xff, 0xff, 0xff

model_vertex_51: /* 11 vertices out of 15 */
vertex   -372,   1506,   3755,  12635, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -248,   1673,   3632,  13540, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -372,   1673,   3755,  12635, -29248,   0xff, 0xff, 0xff, 0xff
vertex     21,   1673,   3894,  31556, -29248,   0xff, 0xff, 0xff, 0xff
vertex     21,   1673,   3719,  30276, -29248,   0xff, 0xff, 0xff, 0xff
vertex     21,   1506,   3719,  30276, -28022,   0xff, 0xff, 0xff, 0xff
vertex     21,   1506,   3894,  31556, -28022,   0xff, 0xff, 0xff, 0xff
vertex    533,   1506,   3894, -13124, -28022,   0xff, 0xff, 0xff, 0xff
vertex    533,   1506,   3719, -11844, -28022,   0xff, 0xff, 0xff, 0xff
vertex    533,   1673,   3719, -11844, -29248,   0xff, 0xff, 0xff, 0xff
vertex    533,   1673,   3894, -13124, -29248,   0xff, 0xff, 0xff, 0xff

model_vertex_52: /* 11 vertices out of 15 */
vertex   1343,   1673,   3128,  25187, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1168,   1673,   3128,  23907, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1168,   1506,   3128,  23907, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1343,   1506,   3128,  25187, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1343,   1506,   2705,   5532, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1168,   1506,   2705,   6812, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1168,   1673,   2705,   6812, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1343,   1673,   2705,   5532, -29248,   0xff, 0xff, 0xff, 0xff
vertex    928,   1673,   3755,  32591, -29248,   0xff, 0xff, 0xff, 0xff
vertex    804,   1673,   3632,  31686, -29248,   0xff, 0xff, 0xff, 0xff
vertex    804,   1506,   3632,  31686, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_53: /* 11 vertices out of 15 */
vertex    928,   1673,   3755,  32591, -29248,   0xff, 0xff, 0xff, 0xff
vertex    804,   1506,   3632,  31686, -28022,   0xff, 0xff, 0xff, 0xff
vertex    928,   1506,   3755,  32591, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1205,   1506,   3479, -10086, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1081,   1506,   3355,  -9181, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1081,   1673,   3355,  -9181, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1205,   1673,   3479, -10086, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -612,   1673,   2705,  -4425, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -612,   1673,   3128,  -7524, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -612,   1506,   3128,  -7524, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -612,   1506,   2705,  -4425, -28022,   0xff, 0xff, 0xff, 0xff

model_vertex_54: /* 11 vertices out of 15 */
vertex   1168,   1506,   2705,  29001, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1168,   1506,   3128,  32100, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1168,   1673,   3128,  32100, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1168,   1673,   2705,  29001, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -525,   1673,   3355,  -9181, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -248,   1673,   3632, -11206, -29248,   0xff, 0xff, 0xff, 0xff
vertex   -248,   1506,   3632, -11206, -28022,   0xff, 0xff, 0xff, 0xff
vertex   -525,   1506,   3355,  -9181, -28022,   0xff, 0xff, 0xff, 0xff
vertex   1081,   1506,   3355,  29661, -28022,   0xff, 0xff, 0xff, 0xff
vertex    804,   1506,   3632,  31686, -28022,   0xff, 0xff, 0xff, 0xff
vertex    804,   1673,   3632,  31686, -29248,   0xff, 0xff, 0xff, 0xff

model_vertex_55: /* 11 vertices out of 15 */
vertex   1081,   1506,   3355,  29661, -28022,   0xff, 0xff, 0xff, 0xff
vertex    804,   1673,   3632,  31686, -29248,   0xff, 0xff, 0xff, 0xff
vertex   1081,   1673,   3355,  29661, -29248,   0xff, 0xff, 0xff, 0xff
vertex     21,   1673,   3719,  15199, -29248,   0xff, 0xff, 0xff, 0xff
vertex    533,   1673,   3719,  11455, -29248,   0xff, 0xff, 0xff, 0xff
vertex    533,   1506,   3719,  11455, -28022,   0xff, 0xff, 0xff, 0xff
vertex     21,   1506,   3719,  15199, -28022,   0xff, 0xff, 0xff, 0xff
vertex -17500,  -6999,  17500,      0,      0,   0x00, 0x7f, 0x00, 0xff
vertex  17500,  -6999,  17500,      0,      0,   0x00, 0x7f, 0x00, 0xff
vertex  17500,  -7000, -17500,      0,      0,   0x00, 0x7f, 0x00, 0xff
vertex -17500,  -7000, -17500,      0,      0,   0x00, 0x7f, 0x00, 0xff

/* Render order: 1 */

glabel bob_dl
gsSPClearGeometryMode G_LIGHTING
/* 01 - Default */
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock model_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSPVertex model_vertex_0, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
/* Material #11 */
gsDPPipeSync
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock model_texture_1, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsDPTileSync
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_1, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_2, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_3, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_4, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_5, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_6, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_7, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_8, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_9, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_10, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_11, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_12, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_13, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_14, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_15, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_16, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_17, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_18, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_19, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 3, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 9, 10, 7, 0x00
gsSPVertex model_vertex_20, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 0, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_21, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 2, 3, 5, 0x00
gsSP1Triangle 2, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex model_vertex_22, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex model_vertex_23, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 4, 6, 0x00
gsSP1Triangle 0, 3, 8, 0x00
gsSPVertex model_vertex_24, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 0, 2, 7, 0x00
gsSP1Triangle 0, 7, 8, 0x00
gsSPVertex model_vertex_25, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex model_vertex_26, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 6, 3, 5, 0x00
gsSP1Triangle 7, 6, 5, 0x00
gsSP1Triangle 2, 8, 9, 0x00
gsSPVertex model_vertex_27, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 0, 3, 0x00
gsSP1Triangle 4, 3, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex model_vertex_28, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 4, 5, 7, 0x00
gsSPVertex model_vertex_29, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 3, 4, 6, 0x00
gsSP1Triangle 0, 3, 6, 0x00
gsSPVertex model_vertex_30, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 3, 2, 0x00
gsSP1Triangle 4, 2, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex model_vertex_31, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 4, 6, 0x00
gsSP1Triangle 8, 7, 6, 0x00
gsSPVertex model_vertex_32, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 4, 0x00
gsSP1Triangle 2, 4, 5, 0x00
gsSP1Triangle 0, 2, 5, 0x00
gsSP1Triangle 0, 5, 6, 0x00
gsSPVertex model_vertex_33, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 3, 2, 0x00
gsSP1Triangle 4, 2, 5, 0x00
gsSP1Triangle 6, 7, 8, 0x00
gsSPVertex model_vertex_34, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 3, 2, 4, 0x00
gsSP1Triangle 5, 6, 7, 0x00
gsSP1Triangle 4, 5, 7, 0x00
gsSPVertex model_vertex_35, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 0, 3, 0x00
gsSP1Triangle 5, 4, 3, 0x00
gsSP1Triangle 5, 3, 6, 0x00
gsSPVertex model_vertex_36, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 4, 6, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_37, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 7, 4, 6, 0x00
gsSP1Triangle 0, 3, 8, 0x00
gsSPVertex model_vertex_38, 9, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 0, 2, 7, 0x00
gsSP1Triangle 0, 7, 8, 0x00
gsSPVertex model_vertex_39, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_40, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 3, 6, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_41, 10, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 6, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSPVertex model_vertex_42, 7, 0
gsSP1Triangle 0, 1, 1, 0x00
gsSP1Triangle 2, 0, 1, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 6, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSPVertex model_vertex_43, 8, 0
gsSP1Triangle 0, 1, 1, 0x00
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 0, 2, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 7, 0x00
gsSPVertex model_vertex_44, 7, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 6, 6, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 3, 6, 3, 0x00
gsSPVertex model_vertex_45, 8, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 2, 3, 3, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 7, 4, 0x00
gsSPVertex model_vertex_46, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_47, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex model_vertex_48, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_49, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex model_vertex_50, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_51, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex model_vertex_52, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_53, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPVertex model_vertex_54, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 0, 2, 3, 0x00
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 4, 6, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex model_vertex_55, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 3, 5, 6, 0x00
/* DefaultMaterial #LIGHTING */
gsDPPipeSync
gsSPSetGeometryMode G_LIGHTING
gsSPNumLights NUMLIGHTS_1
gsSPLight model_diffuse_light, 1
gsSPLight model_ambient_light, 2
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPVertex model_vertex_55, 11, 0
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 7, 9, 10, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPEndDisplayList
