/* Generated by modconv 2 */

glabel unstablePlatform_collision
colInit
colVertexInit 12
colVertex -79, 89, 33
colVertex 78, 102, 51
colVertex 78, 89, 33
colVertex -79, 102, 51
colVertex 78, -1361, -52
colVertex 78, 102, -52
colVertex 78, 89, -34
colVertex 78, -1361, 51
colVertex -79, 102, -52
colVertex -79, -1361, -52
colVertex -79, -1361, 51
colVertex -79, 89, -34

colTriInit SURFACE_DEFAULT, 16
colTri      0,      1,      2
colTri      1,      0,      3
colTri      4,      5,      6
colTri      7,      6,      2
colTri      6,      7,      4
colTri      1,      7,      2
colTri      5,      4,      8
colTri      8,      4,      9
colTri     10,      3,      0
colTri     11,     10,      0
colTri     10,     11,      9
colTri      8,      9,     11
colTri      3,      7,      1
colTri      7,      3,     10
colTri      8,      6,      5
colTri      6,      8,     11

colTriInit SURFACE_DEFAULT, 2
colTri     11,      2,      6
colTri      2,     11,      0
colTriStop
colEnd
