/* Generated by modconv 2 */

glabel unstablePlatform_collision
colInit
colVertexInit 8
colVertex -79, 89, -52
colVertex 78, 89, 51
colVertex 78, 89, -52
colVertex -79, 89, 51
colVertex 78, -90, 51
colVertex 78, -90, -52
colVertex -79, -90, -52
colVertex -79, -90, 51

colTriInit SURFACE_DEFAULT, 2
colTri      0,      1,      2
colTri      1,      0,      3

colTriInit SURFACE_DEFAULT, 8
colTri      1,      4,      2
colTri      2,      4,      5
colTri      2,      5,      0
colTri      0,      5,      6
colTri      0,      6,      3
colTri      3,      6,      7
colTri      3,      4,      1
colTri      4,      3,      7
colTriStop
colEnd
