/* Generated by modconv 2 */

glabel unstablePlatform_geo
    geo_culling_radius 3000
geo_open_node
geo_shadow SHADOW_CIRCLE_4_VERTS, 0xC8, 60
        geo_open_node
            geo_scale 0x00, 16384
            geo_open_node
                geo_display_list LAYER_OPAQUE unstablePlatform_dl_opaque
            geo_close_node
        geo_close_node
    geo_close_node
geo_end
