/* Generated by modconv 2 */

unstablePlatform_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
unstablePlatform_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

unstablePlatform_texture_0:
.incbin "actors/unstablePlatform/mossyTileUnstable.rgba16"

unstablePlatform_texture_1:
.incbin "actors/unstablePlatform/mossyBrickUnstable.rgba16"

unstablePlatform_vertex_0: /* 11 vertices out of 15 */
vertex   -316,    363,   -207,  -7050,   9510,   0x00, 0x7f, 0x00, 0x00
vertex    316,    363,    207,  -2422,  12551,   0x00, 0x7f, 0x00, 0x00
vertex    316,    363,   -207,  -2422,   9510,   0x00, 0x7f, 0x00, 0x00
vertex   -316,    363,    207,  -7050,  12551,   0x00, 0x7f, 0x00, 0x00
vertex    316,    363,    207, -12551, -21304,   0x7f, 0x00, 0x00, 0x00
vertex    316,   -363,    207, -12551, -15990,   0x7f, 0x00, 0x00, 0x00
vertex    316,    363,   -207,  -9510, -21304,   0x7f, 0x00, 0x00, 0x00
vertex    316,   -363,   -207,  -9510, -15990,   0x7f, 0x00, 0x00, 0x00
vertex    316,    363,   -207,  26998, -21304,   0x00, 0x00, 0x81, 0x00
vertex    316,   -363,   -207,  26998, -15990,   0x00, 0x00, 0x81, 0x00
vertex   -316,    363,   -207,  31626, -21304,   0x00, 0x00, 0x81, 0x00

unstablePlatform_vertex_1: /* 11 vertices out of 15 */
vertex   -316,    363,   -207,  31626, -21304,   0x00, 0x00, 0x81, 0x00
vertex    316,   -363,   -207,  26998, -15990,   0x00, 0x00, 0x81, 0x00
vertex   -316,   -363,   -207,  31626, -15990,   0x00, 0x00, 0x81, 0x00
vertex   -316,    363,   -207,  27942, -21304,   0x81, 0x00, 0x00, 0x00
vertex   -316,   -363,   -207,  27942, -15990,   0x81, 0x00, 0x00, 0x00
vertex   -316,    363,    207,  30983, -21304,   0x81, 0x00, 0x00, 0x00
vertex   -316,   -363,    207,  30983, -15990,   0x81, 0x00, 0x00, 0x00
vertex   -316,    363,    207,  -7050, -21304,   0x00, 0x00, 0x7f, 0x00
vertex    316,   -363,    207,  -2422, -15990,   0x00, 0x00, 0x7f, 0x00
vertex    316,    363,    207,  -2422, -21304,   0x00, 0x00, 0x7f, 0x00
vertex   -316,   -363,    207,  -7050, -15990,   0x00, 0x00, 0x7f, 0x00

/* Render order: 1 */

glabel unstablePlatform_dl_opaque
gsSPClearGeometryMode G_LIGHTING
/* #LIGHTING 01 - Default */
gsDPPipeSync
gsSPSetGeometryMode G_LIGHTING
gsSPNumLights NUMLIGHTS_1
gsSPLight unstablePlatform_diffuse_light, 1
gsSPLight unstablePlatform_ambient_light, 2
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock unstablePlatform_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSPVertex unstablePlatform_vertex_0, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 1, 0, 3, 0x00
/* #LIGHTING 02 - Default */
gsDPPipeSync
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock unstablePlatform_texture_1, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsDPTileSync
gsSP1Triangle 4, 5, 6, 0x00
gsSP1Triangle 6, 5, 7, 0x00
gsSP1Triangle 8, 9, 10, 0x00
gsSPVertex unstablePlatform_vertex_1, 11, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSP1Triangle 3, 4, 5, 0x00
gsSP1Triangle 5, 4, 6, 0x00
gsSP1Triangle 7, 8, 9, 0x00
gsSP1Triangle 8, 7, 10, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPEndDisplayList
